#!/usr/bin/env node
// Generates src/lib/supabase/database.types.ts from a live database in the same shape
// as `supabase gen types typescript` (Tables Row/Insert/Update/Relationships, Functions).
// Use this when the Supabase CLI's Docker-based generator is unavailable:
//   DATABASE_URL=postgresql://... node scripts/db/gen-types.mjs
// Prefer `supabase gen types typescript --linked` when you can run it; the output is compatible.
import pg from "pg";
import { writeFileSync } from "node:fs";

const url = process.env.DATABASE_URL ?? "postgresql://postgres@127.0.0.1:54329/postgres";
const out = process.argv[2] ?? "src/lib/supabase/database.types.ts";
const client = new pg.Client({ connectionString: url });
await client.connect();

const q = async (sql, params = []) => (await client.query(sql, params)).rows;

const columns = await q(`
  select c.relname as table, a.attname as name, a.attnum,
         format_type(a.atttypid, a.atttypmod) as fmt, t.typname, t.typcategory, et.typname as elem,
         not a.attnotnull as nullable, a.atthasdef as has_default, a.attidentity <> '' as identity,
         a.attgenerated <> '' as generated
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  join pg_type t on t.oid = a.atttypid
  left join pg_type et on et.oid = t.typelem and t.typcategory = 'A'
  where n.nspname = 'public' and c.relkind in ('r','p') and a.attnum > 0 and not a.attisdropped
  order by c.relname, a.attnum`);

const fks = await q(`
  select con.conname, src.relname as table, tgt.relname as ref_table,
         array(select a.attname from unnest(con.conkey) with ordinality k(n, i) join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k.n order by k.i)::text[] as cols,
         array(select a.attname from unnest(con.confkey) with ordinality k(n, i) join pg_attribute a on a.attrelid = con.confrelid and a.attnum = k.n order by k.i)::text[] as ref_cols,
         exists (
           select 1 from pg_index ix where ix.indrelid = con.conrelid and ix.indisunique and ix.indpred is null
             and (select array_agg(x order by x) from unnest(ix.indkey::int2[]) x) = (select array_agg(x order by x) from unnest(con.conkey) x)
         ) as one_to_one
  from pg_constraint con
  join pg_class src on src.oid = con.conrelid
  join pg_class tgt on tgt.oid = con.confrelid
  join pg_namespace n on n.oid = src.relnamespace
  join pg_namespace tn on tn.oid = tgt.relnamespace
  where con.contype = 'f' and n.nspname = 'public' and tn.nspname = 'public'
  order by src.relname, con.conname`);

const fns = await q(`
  select p.proname as name, p.proretset as returns_set,
         coalesce(p.proargnames, '{}')::text[] as argnames, coalesce(p.proargmodes::text[], '{}') as argmodes,
         array(select format_type(x, null) from unnest(coalesce(p.proallargtypes, p.proargtypes::oid[])) x) as argtypes,
         format_type(p.prorettype, null) as rettype, p.pronargdefaults as ndefaults, p.pronargs as nargs
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
  order by p.proname`);

await client.end();

function tsType(fmt) {
  if (fmt.endsWith("[]")) return `${tsType(fmt.slice(0, -2))}[]`;
  const base = fmt.replace(/\(.*\)/, "").trim();
  switch (base) {
    case "smallint": case "integer": case "bigint": case "real": case "double precision": case "numeric":
      return "number";
    case "boolean": return "boolean";
    case "json": case "jsonb": return "Json";
    case "uuid": case "text": case "character varying": case "character": case "date": case "citext":
    case "timestamp with time zone": case "timestamp without time zone": case "time without time zone": case "interval": case "inet":
      return "string";
    case "tsvector": return "unknown";
    case "void": return "undefined";
    default: return "unknown";
  }
}

const tables = new Map();
for (const c of columns) {
  if (!tables.has(c.table)) tables.set(c.table, []);
  tables.get(c.table).push(c);
}

const ind = (n) => "  ".repeat(n);
let s = "";
s += `// GENERATED by scripts/db/gen-types.mjs from the migrations in supabase/migrations. Do not edit.\n`;
s += `// Regenerate: pnpm db:types\n\n`;
s += `export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\n\n`;
s += `export type Database = {\n${ind(1)}__InternalSupabase: {\n${ind(2)}PostgrestVersion: "12";\n${ind(1)}};\n${ind(1)}public: {\n${ind(2)}Tables: {\n`;
for (const [table, cols] of tables) {
  s += `${ind(3)}${table}: {\n`;
  s += `${ind(4)}Row: {\n`;
  for (const c of cols) s += `${ind(5)}${c.name}: ${tsType(c.fmt)}${c.nullable ? " | null" : ""};\n`;
  s += `${ind(4)}};\n${ind(4)}Insert: {\n`;
  for (const c of cols) {
    if (c.generated) { s += `${ind(5)}${c.name}?: never;\n`; continue; }
    const opt = c.nullable || c.has_default || c.identity;
    s += `${ind(5)}${c.name}${opt ? "?" : ""}: ${tsType(c.fmt)}${c.nullable ? " | null" : ""};\n`;
  }
  s += `${ind(4)}};\n${ind(4)}Update: {\n`;
  for (const c of cols) {
    if (c.generated) { s += `${ind(5)}${c.name}?: never;\n`; continue; }
    s += `${ind(5)}${c.name}?: ${tsType(c.fmt)}${c.nullable ? " | null" : ""};\n`;
  }
  s += `${ind(4)}};\n${ind(4)}Relationships: [\n`;
  for (const f of fks.filter((f) => f.table === table)) {
    s += `${ind(5)}{\n${ind(6)}foreignKeyName: "${f.conname}";\n${ind(6)}columns: [${f.cols.map((c) => `"${c}"`).join(", ")}];\n`;
    s += `${ind(6)}isOneToOne: ${f.one_to_one};\n${ind(6)}referencedRelation: "${f.ref_table}";\n`;
    s += `${ind(6)}referencedColumns: [${f.ref_cols.map((c) => `"${c}"`).join(", ")}];\n${ind(5)}},\n`;
  }
  s += `${ind(4)}];\n${ind(3)}};\n`;
}
s += `${ind(2)}};\n${ind(2)}Views: {\n${ind(3)}[_ in never]: never;\n${ind(2)}};\n${ind(2)}Functions: {\n`;
for (const f of fns) {
  const ins = f.argnames
    .map((name, i) => ({ name, mode: f.argmodes[i] ?? "i", type: f.argtypes[i] }))
    .filter((a) => a.mode === "i" || a.mode === "b");
  const outs = f.argnames
    .map((name, i) => ({ name, mode: f.argmodes[i] ?? "i", type: f.argtypes[i] }))
    .filter((a) => a.mode === "t" || a.mode === "o");
  const firstDefault = f.nargs - f.ndefaults;
  s += `${ind(3)}${f.name}: {\n${ind(4)}Args: `;
  if (ins.length === 0) s += `never;\n`;
  else {
    s += `{\n`;
    ins.forEach((a, i) => (s += `${ind(5)}${a.name}${i >= firstDefault ? "?" : ""}: ${tsType(a.type)};\n`));
    s += `${ind(4)}};\n`;
  }
  let ret;
  if (outs.length) ret = `{\n${outs.map((o) => `${ind(5)}${o.name}: ${tsType(o.type)};`).join("\n")}\n${ind(4)}}[]`;
  else ret = tsType(f.rettype) + (f.returns_set ? "[]" : "");
  s += `${ind(4)}Returns: ${ret};\n${ind(3)}};\n`;
}
s += `${ind(2)}};\n${ind(2)}Enums: {\n${ind(3)}[_ in never]: never;\n${ind(2)}};\n${ind(2)}CompositeTypes: {\n${ind(3)}[_ in never]: never;\n${ind(2)}};\n${ind(1)}};\n};\n\n`;
s += `type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type DbFunctions = PublicSchema["Functions"];
`;
writeFileSync(out, s);
console.log(`wrote ${out}: ${tables.size} tables, ${fns.length} functions`);
