import { z } from "zod";
import { normalizeHost } from "@/lib/tenant/host";

/**
 * DNS-over-HTTPS (RFC 8484 JSON flavour, as served by Cloudflare) for custom-domain
 * verification. Parsing is pure and unit tested; the single fetch helper has a hard
 * timeout and never throws (null = lookup failed, try again later).
 */

export const DOH_ENDPOINT = "https://cloudflare-dns.com/dns-query";
export const DNS_TYPE = { A: 1, CNAME: 5, TXT: 16, AAAA: 28 } as const;
export type DnsRecordType = keyof typeof DNS_TYPE;

const answerSchema = z.object({ name: z.string(), type: z.number().int(), TTL: z.number().optional(), data: z.string() });
const responseSchema = z.object({ Status: z.number().int(), Answer: z.array(answerSchema).optional() });
export type DohResponse = z.infer<typeof responseSchema>;

/** RCODEs we care about. Anything else (SERVFAIL, REFUSED…) is a transient error. */
export const DNS_RCODE = { NOERROR: 0, NXDOMAIN: 3 } as const;

export function parseDohResponse(json: unknown): DohResponse | null {
  const parsed = responseSchema.safeParse(json);
  return parsed.success ? parsed.data : null;
}

/**
 * TXT `data` arrives in presentation format: one or more quoted character-strings
 * (`"abc" "def"`), with `\"`, `\\` and `\DDD` escapes. Long values are split into
 * 255-byte strings that must be concatenated. Unquoted data is returned as-is.
 */
export function decodeTxtData(data: string): string {
  const s = data.trim();
  if (!s.startsWith('"')) return s;
  let out = "";
  let i = 0;
  while (i < s.length) {
    if (s[i] !== '"') {
      i++;
      continue;
    }
    i++; // opening quote
    while (i < s.length && s[i] !== '"') {
      const ch = s[i]!;
      if (ch === "\\" && i + 1 < s.length) {
        const dec = /^\d{3}/.exec(s.slice(i + 1, i + 4));
        if (dec) {
          out += String.fromCharCode(Number(dec[0]));
          i += 4;
        } else {
          out += s[i + 1];
          i += 2;
        }
      } else {
        out += ch;
        i++;
      }
    }
    i++; // closing quote
  }
  return out;
}

/** DNS names compare case-insensitively and ignore the root dot (`_x.brand.in.` == `_X.brand.in`). */
function sameName(a: string, b: string): boolean {
  return a.replace(/\.$/, "").toLowerCase() === b.replace(/\.$/, "").toLowerCase();
}

/** Decoded TXT strings for exactly `name` (other names in the answer, e.g. CNAME chains, are ignored). */
export function txtValues(resp: DohResponse, name: string): string[] {
  return (resp.Answer ?? []).filter((a) => a.type === DNS_TYPE.TXT && sameName(a.name, name)).map((a) => decodeTxtData(a.data).trim());
}

/** CNAME targets (normalised, no trailing dot) found anywhere in the answer. */
export function cnameTargets(resp: DohResponse): string[] {
  return (resp.Answer ?? [])
    .filter((a) => a.type === DNS_TYPE.CNAME)
    .map((a) => normalizeHost(a.data))
    .filter((h): h is string => !!h);
}

export type RecordCheck = "match" | "mismatch" | "missing" | "error" | "skipped";

export type VerificationResult = {
  verified: boolean;
  txt: RecordCheck;
  cname: RecordCheck;
  /** User-facing explanation when not verified (null when verified). */
  message: string | null;
};

function classify(resp: DohResponse | null, values: (r: DohResponse) => string[], matches: (v: string) => boolean): RecordCheck {
  if (!resp) return "error";
  if (resp.Status === DNS_RCODE.NXDOMAIN) return "missing";
  if (resp.Status !== DNS_RCODE.NOERROR) return "error";
  const found = values(resp);
  if (found.length === 0) return "missing";
  return found.some(matches) ? "match" : "mismatch";
}

/**
 * Ownership = TXT `_paliya-verify.<host>` equals the token. Routing = CNAME `<host>` points
 * at the platform target (skipped when no target is configured, e.g. local dev). Both must
 * pass. Token comparison is exact (tokens are hex, generated by the database).
 */
export function evaluateVerification(input: {
  hostname: string;
  token: string;
  cnameTarget: string | null | undefined;
  txtResponse: DohResponse | null;
  cnameResponse: DohResponse | null;
}): VerificationResult {
  const recordName = `_paliya-verify.${input.hostname}`;
  const txt = classify(input.txtResponse, (r) => txtValues(r, recordName), (v) => v === input.token);
  const target = input.cnameTarget ? normalizeHost(input.cnameTarget) : null;
  const cname = target ? classify(input.cnameResponse, cnameTargets, (v) => v === target) : "skipped";

  const verified = txt === "match" && (cname === "match" || cname === "skipped");
  let message: string | null = null;
  if (!verified) {
    if (txt === "error" || cname === "error") message = "We couldn't reach DNS just now. Please try again in a few minutes.";
    else if (txt === "missing") message = `TXT record ${recordName} was not found yet. DNS changes can take up to an hour to appear.`;
    else if (txt === "mismatch") message = `TXT record ${recordName} exists but its value doesn't match your verification code.`;
    else if (cname === "missing") message = `CNAME record for ${input.hostname} was not found. Point it at ${target}.`;
    else if (cname === "mismatch") message = `CNAME record for ${input.hostname} points somewhere else. Point it at ${target}.`;
  }
  return { verified, txt, cname, message };
}

/** One DoH lookup. Returns null on network error, timeout, non-200 or malformed JSON. */
export async function dohQuery(
  name: string,
  type: DnsRecordType,
  opts: { fetchImpl?: typeof fetch; timeoutMs?: number; endpoint?: string } = {},
): Promise<DohResponse | null> {
  const url = new URL(opts.endpoint ?? DOH_ENDPOINT);
  url.searchParams.set("name", name);
  url.searchParams.set("type", type);
  try {
    const res = await (opts.fetchImpl ?? fetch)(url, {
      headers: { accept: "application/dns-json" },
      signal: AbortSignal.timeout(opts.timeoutMs ?? 4000),
      cache: "no-store",
    });
    if (!res.ok) return null;
    return parseDohResponse(await res.json());
  } catch {
    return null;
  }
}

/** Runs both lookups in parallel and evaluates them. */
export async function checkDomainDns(
  hostname: string,
  token: string,
  cnameTarget: string | null | undefined,
  opts: { fetchImpl?: typeof fetch; timeoutMs?: number } = {},
): Promise<VerificationResult> {
  const [txtResponse, cnameResponse] = await Promise.all([
    dohQuery(`_paliya-verify.${hostname}`, "TXT", opts),
    cnameTarget ? dohQuery(hostname, "CNAME", opts) : Promise.resolve(null),
  ]);
  return evaluateVerification({ hostname, token, cnameTarget, txtResponse, cnameResponse });
}
