import {
  Activity,
  BrainCircuit,
  MessagesSquare,
  MapPinned,
  BadgePercent,
  Bell,
  Boxes,
  ChartNoAxesCombined,
  CircleHelp,
  CreditCard,
  FileText,
  Flag,
  FolderTree,
  Globe,
  HardDrive,
  Images,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Menu,
  Newspaper,
  Package,
  Palette,
  Plug,
  Receipt,
  Ruler,
  ScrollText,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Star,
  Store,
  TicketPercent,
  Truck,
  Undo2,
  Users,
  UsersRound,
  SearchCheck,
  Radar,
  Share2,
  Sparkles,
  Brush,
  type LucideIcon,
} from "lucide-react";

/**
 * One icon library (lucide), one stroke width (1.75), one size (16px in nav). Navigation configs
 * reference icons by name so they stay serialisable from server to client components.
 */
export const NAV_ICONS = {
  dashboard: LayoutDashboard,
  orders: ShoppingBag,
  returns: Undo2,
  products: Package,
  collections: Layers,
  categories: FolderTree,
  inventory: Boxes,
  sizeCharts: Ruler,
  customers: Users,
  coupons: TicketPercent,
  reviews: Star,
  theme: Palette,
  media: Images,
  pages: FileText,
  menus: Menu,
  blog: Newspaper,
  faqs: CircleHelp,
  analytics: ChartNoAxesCombined,
  settings: Settings,
  payments: CreditCard,
  shipping: Truck,
  taxes: Receipt,
  domains: Globe,
  notifications: Bell,
  team: UsersRound,
  roles: ShieldCheck,
  stores: Store,
  support: LifeBuoy,
  plans: BadgePercent,
  flags: Flag,
  usage: HardDrive,
  audit: ScrollText,
  integrations: Plug,
  users: Users,
  activity: Activity,
  seo: SearchCheck,
  tracking: Radar,
  social: Share2,
  inbox: MessagesSquare,
  ai: BrainCircuit,
  gbp: MapPinned,
  creative: Sparkles,
  themes: Brush,
} satisfies Record<string, LucideIcon>;

export type NavIconName = keyof typeof NAV_ICONS;
export const NAV_ICON_STROKE = 1.75;
