import type { MarketplaceTheme } from "../types";

/**
 * Automotive accessories. Content slots (scripts/dev/showcase/data/gearbay.ts): hero, marquee,
 * categories, collections, trending, riding, car-care, interior, electronics, deals, bestsellers,
 * new, feature, feature-2, promo, story, lookbook, brands, trust, faq, newsletter, sale.
 */
const DEMO = "gearbay";
const ADDED = "2026-10-01";

export const AUTOMOTIVE_THEMES: MarketplaceTheme[] = [
  {
    key: "redline-garage",
    name: "Redline Garage",
    tagline: "Dark, loud and built for enthusiasts",
    description: "A performance layout on a near-black canvas: full-screen hero, a large scrolling strip of promises, tall portrait category tiles, a four-up trending grid, a garage story on a raised panel and a riding-gear carousel. Uppercase grotesk headings, square buttons and sharp cards in signal orange.",
    industry: "automotive",
    style: "bold",
    bestFor: ["Performance accessories", "Riding gear", "Enthusiast brands"],
    features: ["Dark canvas", "Large scrolling strip", "Portrait category tiles", "Square buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#ff5418", secondary: "#2a2c31", accent: "#ffb21a", background: "#131417", text: "#ecedef", border: "#2c2e33", sale: "#ff5418" }, headingFont: "grotesk", bodyFont: "modern-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "filled", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 6 }, "hero"],
        ["Marquee", { size: "large", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 5 }, "categories"],
        ["ProductGrid", { limit: 4, columns: 4 }, "trending"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["ProductCarousel", { limit: 10 }, "riding"],
        ["PromoBanner", { aspect: "portrait" }, "promo"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "trending"]],
    },
  },
  {
    key: "spares-market",
    name: "Spares Market",
    tagline: "Every accessory, every vehicle, one aisle",
    description: "A dense marketplace layout for big accessory catalogues: full-width container, mega menu, compact spacing, round department shortcuts, five-column grids for car care and gadgets, an interiors carousel and a strip of product lines. Built for shoppers who know what they want.",
    industry: "automotive",
    style: "marketplace",
    bestFor: ["Multi-category accessory stores", "Cars and two-wheelers", "Large catalogues"],
    features: ["Mega menu", "Round department shortcuts", "5-column grids", "Product-line strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#12355b", secondary: "#1f4e7f", accent: "#ffc21a", background: "#f3f5f8", text: "#13212f", border: "#dfe4eb", sale: "#d7263d" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "car-care"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductCarousel", { limit: 12 }, "interior"],
        ["ProductGrid", { limit: 8, columns: 5 }, "electronics"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "pit-stop-deals",
    name: "Pit Stop Deals",
    tagline: "Offers first, checkout fast",
    description: "Conversion-first for accessory stores running offers: centred logo with a drawer menu, a fast offer strip and coupon band before anything else, a deals grid with green discount pills, a best-seller carousel, quick add on every card and trust signals on collection and product pages.",
    industry: "automotive",
    style: "conversion",
    bestFor: ["Sale events", "Value accessories", "High-volume sellers"],
    features: ["Coupon sale band", "Discount pills", "Quick add", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#c1121f", secondary: "#8f0d17", accent: "#ffd60a", background: "#ffffff", text: "#1d1d1f", border: "#ececec", sale: "#c1121f" }, headingFont: "humanist-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free fitment help" },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 5 }, "categories"],
        ["FAQ", { limit: 4 }, "faq"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
  {
    key: "grand-tourer",
    name: "Grand Tourer",
    tagline: "Considered accessories for the long drive",
    description: "A premium, story-led layout: centred logo over a menu bar, a large hero, three collection tiles, a cabin-comfort story, a three-column interior grid, the brand story with numbers and a row gallery. Serif capitals, warm stone tones and a muted footer make it feel like a tailored cabin.",
    industry: "automotive",
    style: "premium",
    bestFor: ["Premium interiors", "Leather and cabin comfort", "Gifting for drivers"],
    features: ["Collection tiles", "Brand story with numbers", "Row gallery", "Serif capitals"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2420", secondary: "#6e5a48", accent: "#b08a5a", background: "#f8f5f0", text: "#26201c", border: "#e6dfd4", sale: "#8f3b2a" }, headingFont: "marcellus", bodyFont: "humanist-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "landscape", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 7 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["ProductGrid", { limit: 6, columns: 3 }, "interior"],
        ["BrandStory", {}, "story"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["TrustBadges", { layout: "grid", tone: "light" }, "trust"], ["ProductCarousel", { limit: 8 }, "interior"]],
    },
  },
  {
    key: "clean-cabin",
    name: "Clean Cabin",
    tagline: "Quiet, tidy and easy to shop",
    description: "A minimal layout for focused accessory brands: logo left with a drawer menu on every screen, a medium hero with a soft overlay, three-column grids without badges, one feature story about car care and an FAQ. Clean sans type, outline pill buttons and a light footer.",
    industry: "automotive",
    style: "minimal",
    bestFor: ["Car-care brands", "Small catalogues", "D2C accessory labels"],
    features: ["Drawer menu", "Three-column grids", "No badges", "FAQ block"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f2a30", secondary: "#56656d", accent: "#2f8f83", background: "#ffffff", text: "#1f2a30", border: "#e8ecee", sale: "#b4532a" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "outline", cardRadius: "lg", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: false, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 20, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "new"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 3, columns: 3 }, "car-care"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
];
