import type { MarketplaceTheme } from "../types";

/**
 * Bags & Travel. Content slots (scripts/dev/showcase/data/safarnama.ts): hero, marquee,
 * categories, collections, adventure, bestsellers, new, leather, luggage, accessories, deals,
 * feature, feature-2, story, lookbook, promo, sale, brands, trust, faq, newsletter.
 */
const DEMO = "safarnama";
const ADDED = "2026-10-01";

export const BAGS_THEMES: MarketplaceTheme[] = [
  {
    key: "trailhead",
    name: "Trailhead",
    tagline: "Loud, rugged and built for the outdoors",
    description: "An adventure layout for backpack and outdoor-gear brands: a scrolling offer strip above a full-screen hero, uppercase grotesk headings, square category tiles, a trail-ready backpack carousel, a dark feature story and a scrolling trust strip. Signal-orange on charcoal, square buttons and sharp-cornered cards.",
    industry: "bags",
    style: "bold",
    bestFor: ["Backpacks & rucksacks", "Outdoor and trekking gear", "Adventure travel brands"],
    features: ["Offer marquee", "Full-screen hero", "Backpack carousel", "Dark feature story"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1c1f1d", secondary: "#3b4a3f", accent: "#ff6a1a", background: "#f4f3ef", text: "#1c1f1d", border: "#dedbd2", sale: "#e2412b" }, headingFont: "grotesk", bodyFont: "modern-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "medium", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["Hero", { height: "full", overlay: 30, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "adventure"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["TrustBadges", { layout: "marquee", tone: "dark" }, "trust"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "adventure"], ["TrustBadges", { layout: "marquee", tone: "dark" }, "trust"]],
    },
  },
  {
    key: "saddle-and-stitch",
    name: "Saddle & Stitch",
    tagline: "Quiet luxury for full-grain leather",
    description: "A slow, premium layout for leather-goods makers: centred logo with a drawer menu, a large centred hero, a brand story about hides and stitching, a three-column leather edit, a masonry lookbook and an occasion grid. Display serif headings, cognac on cream, outline buttons and portrait cards without badges.",
    industry: "bags",
    style: "luxury",
    bestFor: ["Leather bags & briefcases", "Wallets & small leather goods", "Heritage workshops"],
    features: ["Drawer menu", "Craft story", "Masonry lookbook", "Badge-free portrait cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#3b2417", secondary: "#8a5a3b", accent: "#b9824f", background: "#f8f3ec", text: "#2e1f16", border: "#e8dccd", sale: "#9c3b23" }, headingFont: "playfair", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 6, columns: 3 }, "leather"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["CollectionGrid", { mode: "manual", columns: 4, limit: 4 }, "collections"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductGrid", { limit: 3, columns: 3 }, "leather"]],
    },
  },
  {
    key: "carry-light",
    name: "Carry Light",
    tagline: "Pared-back everyday carry",
    description: "A minimal, white-space-led layout for everyday bags: logo on the left with the menu bar beneath, a medium hero, new arrivals in a clean four-column grid, two collection tiles, one feature story and an FAQ about capacity and laptop fit. Manrope throughout, landscape cards with no badges, rounded outline buttons and a light footer.",
    industry: "bags",
    style: "minimal",
    bestFor: ["Laptop bags & backpacks", "Everyday carry", "D2C bag brands"],
    features: ["Landscape cards", "Two-tile collections", "Capacity FAQ", "Narrow container"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#22262a", secondary: "#5c6670", accent: "#4f7a8a", background: "#ffffff", text: "#22262a", border: "#eceef0", sale: "#c2412d" }, headingFont: "humanist-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "outline", cardRadius: "md", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "landscape", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["CollectionGrid", { mode: "manual", columns: 2, limit: 2 }, "collections"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 4, columns: 4 }, "accessories"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "luggage-bazaar",
    name: "Luggage Bazaar",
    tagline: "Every bag for every trip, in one aisle",
    description: "A dense marketplace layout for large bag and luggage catalogues: full-width container, menu bar with mega menu, compact spacing, a coupon band under a medium hero, portrait department tiles, five-column grids for best sellers and luggage, an accessories carousel and a scrolling strip of in-house ranges. Pill discount badges and quick add on every card.",
    industry: "bags",
    style: "marketplace",
    bestFor: ["Multi-category bag stores", "Luggage retailers", "Large catalogues and sales"],
    features: ["Mega menu", "Coupon sale band", "5-column grids", "Range strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14324f", secondary: "#2c5a85", accent: "#f2a516", background: "#f3f5f8", text: "#172434", border: "#dfe5ec", sale: "#d7263d" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["SaleBanner", {}, "sale"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "bestsellers"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 5 }, "deals"],
        ["ProductCarousel", { limit: 12 }, "luggage"],
        ["ProductCarousel", { limit: 12 }, "accessories"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 10 }, "deals"], ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"]],
    },
  },
  {
    key: "travel-journal",
    name: "Travel Journal",
    tagline: "Stories from the road, with bags to match",
    description: "An editorial, magazine-style layout for travel-led bag brands: centred logo with an inline menu, a full-screen hero, alternating long-form feature stories around a weekender edit, a row lookbook and promo tiles. Cormorant serif headings, tall cards, pill buttons and a muted footer.",
    industry: "bags",
    style: "editorial",
    bestFor: ["Duffels & weekenders", "Travel accessories", "Story-led brands"],
    features: ["Alternating feature stories", "Row lookbook", "Promo tiles", "Tall cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#26343a", secondary: "#6b7d6f", accent: "#c0703f", background: "#f5f1e8", text: "#22292c", border: "#e3dccd", sale: "#a83f2a" }, headingFont: "editorial-serif", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "sm", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "rotate",
      productCard: { imageRatio: "tall", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 25, autoplay: 7 }, "hero"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 4, columns: 4 }, "luggage"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature-2"],
        ["PromoBanner", { aspect: "portrait" }, "promo"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      collection: [["PageContent", {}], ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"]],
    },
  },
];
