import type { MarketplaceTheme } from "../types";

/**
 * Beauty & Cosmetics. Content slots (scripts/dev/showcase/data/dewbloom.ts): hero, concerns,
 * categories, new, bestsellers, skincare, makeup, routine, ingredients, feature, promo, lookbook,
 * social, trust, faq, newsletter, marquee, sale.
 */
const DEMO = "dewbloom";
const ADDED = "2026-09-30";

export const BEAUTY_THEMES: MarketplaceTheme[] = [
  {
    key: "luxury-beauty",
    name: "Luxury Beauty",
    tagline: "Hushed, gilded and ritual-led",
    description: "A prestige-counter feel: high-contrast serif headings, full-screen hero, an ingredient story with figures, three-column best sellers and a slow editorial pace. Black, ivory and antique gold.",
    industry: "beauty",
    style: "luxury",
    bestFor: ["Prestige skincare", "Fragrance", "Gift sets"],
    features: ["Full-screen hero", "Ingredient story", "Centred cards", "Dark footer"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#16130f", secondary: "#5a4a3a", accent: "#b08d57", background: "#fbf9f5", text: "#16130f", border: "#e9e2d6", sale: "#8c2f39" }, headingFont: "didone", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bestsellers"],
        ["BrandStory", {}, "ingredients"],
        ["CollectionGrid", { mode: "manual", columns: 4, limit: 4 }, "concerns"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "routine"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "clean-skincare",
    name: "Clean Skincare",
    tagline: "Calm, clinical, concern-led",
    description: "Shop-by-concern first: soft sand palette, rounded cards, a four-up concern grid, skincare essentials, a step-by-step routine story and FAQs about skin types. Clear hierarchy, no clutter.",
    industry: "beauty",
    style: "minimal",
    bestFor: ["Skincare brands", "Dermatologist-led lines", "Small catalogues"],
    features: ["Shop by concern", "Routine story", "FAQ", "Rounded cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2f3a36", secondary: "#7b8c84", accent: "#c28e6a", background: "#f6f2ec", text: "#26302c", border: "#e6ded3", sale: "#b5543b" }, headingFont: "humanist-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showQuickAdd: true, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 4, limit: 4 }, "concerns"],
        ["ProductGrid", { limit: 8, columns: 4 }, "skincare"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "routine"],
        ["ProductCarousel", { limit: 8 }, "bestsellers"],
        ["FAQ", { limit: 6 }, "faq"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
    },
  },
  {
    key: "modern-cosmetics",
    name: "Modern Cosmetics",
    tagline: "Colour-forward, social and fast",
    description: "Loud and playful for makeup: scrolling offer strip, drawer menu with centred logo, bold uppercase type, a makeup carousel, split promo tiles, new launches and an Instagram grid. Built for drops and social traffic.",
    industry: "beauty",
    style: "bold",
    bestFor: ["Makeup", "Nail & lip", "Gen Z brands"],
    features: ["Offer marquee", "Promo tiles", "Instagram grid", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1b1020", secondary: "#6d2e5c", accent: "#e84a8a", background: "#ffffff", text: "#1b1020", border: "#f1e4ec", sale: "#e11d48" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["Hero", { height: "large", overlay: 20, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "makeup"],
        ["PromoBanner", { aspect: "portrait" }, "promo"],
        ["ProductCarousel", { limit: 10 }, "new"],
        ["SocialProof", { layout: "mosaic", showProfile: true }, "social"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "bestsellers"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
  {
    key: "organic-beauty",
    name: "Organic Beauty",
    tagline: "Botanical, warm and ingredient-honest",
    description: "Earthy and reassuring: soft serif headings, leaf-green palette, an ingredients story with sourcing figures, concern tiles, best sellers and a newsletter band. Pairs with natural and Ayurvedic ranges.",
    industry: "beauty",
    style: "heritage",
    bestFor: ["Natural skincare", "Ayurvedic ranges", "Handmade soaps"],
    features: ["Ingredient story", "Concern tiles", "Serif headings", "Muted footer"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2e4630", secondary: "#6b7f4f", accent: "#b9772e", background: "#f5f1e8", text: "#263226", border: "#e2dccd", sale: "#a23b2a" }, headingFont: "classic-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      footerDecor: "none",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 25, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "ingredients"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "routine"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "editorial-beauty",
    name: "Editorial Beauty",
    tagline: "A magazine that happens to sell",
    description: "Story-first: elegant serif display type, full-bleed hero, a lookbook, alternating feature spreads and two-up product rows. For brands whose content sells as much as their products.",
    industry: "beauty",
    style: "editorial",
    bestFor: ["Content-led brands", "Founder stories", "Seasonal edits"],
    features: ["Lookbook", "Feature spreads", "Serif display type", "Two-up grid"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1c1917", secondary: "#57534e", accent: "#9f1239", background: "#ffffff", text: "#1c1917", border: "#e7e5e4", sale: "#9f1239" }, headingFont: "editorial-serif", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: false, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "tall", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 20, autoplay: 0 }, "hero"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["ProductGrid", { limit: 4, columns: 2 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "routine"],
        ["ProductCarousel", { limit: 8 }, "bestsellers"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
];
