import type { MarketplaceTheme } from "../types";

/**
 * Books & Stationery. Content slots (scripts/dev/showcase/data/pustak-ghar.ts): hero, marquee,
 * categories, collections, journals, writing, art, paper, new, bestsellers, deals, story,
 * feature, feature-2, lookbook, promo, brands, trust, faq, newsletter.
 */
const DEMO = "pustak-ghar";
const ADDED = "2026-10-01";

export const BOOKS_THEMES: MarketplaceTheme[] = [
  {
    key: "margin-notes",
    name: "Margin Notes",
    tagline: "A literary journal for paper lovers",
    description: "An editorial, magazine-like layout for journal and fine-paper brands: centred masthead logo, display-serif headings, long-form image-and-text stories between airy three-column grids and a masonry lookbook of desk details. Outline buttons and a light footer keep it quiet and readerly.",
    industry: "books",
    style: "editorial",
    bestFor: ["Journal & notebook brands", "Fine paper studios", "Independent bookshops"],
    features: ["Masthead logo", "Alternating stories", "Masonry lookbook", "Three-column grid"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2622", secondary: "#8c5a3c", accent: "#b23a2b", background: "#fbf8f2", text: "#2b2622", border: "#e9e1d4", sale: "#a3321f" }, headingFont: "playfair", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 0 }, "hero"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 6, columns: 3 }, "journals"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"], ["ProductCarousel", { limit: 8 }, "journals"]],
    },
  },
  {
    key: "blank-page",
    name: "Blank Page",
    tagline: "White space, sharp type, nothing extra",
    description: "A stripped-back minimal layout for design-led stationery: logo left with a drawer menu on every screen, a short centred hero, a four-column best-seller grid with no badges, square category tiles and a brand story. Grotesk headings, black-on-white and square buttons.",
    industry: "books",
    style: "minimal",
    bestFor: ["Design stationery", "Pens & desk tools", "Small D2C catalogues"],
    features: ["Drawer menu", "Badge-free cards", "Square category tiles", "FAQ block"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#111111", secondary: "#555555", accent: "#111111", background: "#ffffff", text: "#161616", border: "#ececec", sale: "#c2410c" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 5 }, "categories"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 4, columns: 4 }, "writing"],
        ["FAQ", { limit: 6 }, "faq"],
      ],
    },
  },
  {
    key: "old-library",
    name: "Old Library",
    tagline: "Brass lamps, leather spines and ink",
    description: "A heritage reading-room layout: centred logo with an inline menu, classic capitals on a cream page with bottle-green and oxblood, a full-screen hero, the shop's story up front, three collection tiles, a writing-instruments grid and a row lookbook. Dark footer and a grid of trust badges.",
    industry: "books",
    style: "heritage",
    bestFor: ["Heritage stationers", "Fountain pens & ink", "Bookshops with history"],
    features: ["Full-screen hero", "Story up front", "Collection tiles", "Row lookbook"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f3b2d", secondary: "#6b2a2a", accent: "#b08d57", background: "#f6f0e3", text: "#2a2620", border: "#e2d6bf", sale: "#8f2d24" }, headingFont: "marcellus", bodyFont: "classic-serif", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "sm", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "filled", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 35, autoplay: 7 }, "hero"],
        ["BrandStory", {}, "story"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 6, columns: 3 }, "writing"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["BrandStory", {}, "story"], ["ProductCarousel", { limit: 8 }, "writing"]],
    },
  },
  {
    key: "desk-studio",
    name: "Desk Studio",
    tagline: "Bright, friendly and made for makers",
    description: "A modern lifestyle layout for art and craft stationery: logo left with an inline menu, round category bubbles under a large hero, an art-supplies carousel, square promo tiles and a four-column new-arrivals grid. Geometric sans, pill buttons, rounded cards and quick add.",
    industry: "books",
    style: "modern",
    bestFor: ["Art & craft supplies", "Students and hobbyists", "Gift stationery"],
    features: ["Round category bubbles", "Square promo tiles", "Quick add", "Pill buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#23395b", secondary: "#406e8e", accent: "#f2a541", background: "#ffffff", text: "#1d2b40", border: "#e4eaf2", sale: "#e4572e" }, headingFont: "geometric-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 25, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "art"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
    },
  },
  {
    key: "stationery-bazaar",
    name: "Stationery Bazaar",
    tagline: "Every notebook, pen and paper in one aisle",
    description: "A dense marketplace layout for big stationery catalogues: full-width container, mega menu, compact spacing, an offers ticker, square department tiles, five-column deal and best-seller grids, a paper-and-desk carousel and a scrolling strip of house ranges. Built for quick back-to-school browsing.",
    industry: "books",
    style: "marketplace",
    bestFor: ["Multi-category stationers", "School & office supplies", "Large catalogues"],
    features: ["Mega menu", "Offers ticker", "5-column grids", "House-range strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14213d", secondary: "#2f4b7c", accent: "#fca311", background: "#f5f6f8", text: "#14213d", border: "#e2e5eb", sale: "#d62828" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: false, offerBadge: "Free cover & label" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "accent", separator: "dot" }, "marquee"],
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "deals"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 5 }, "bestsellers"],
        ["ProductCarousel", { limit: 12 }, "paper"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
