import type { MarketplaceTheme } from "../types";

/**
 * Electronics & Gadgets. Content slots (see scripts/dev/showcase/data/voltnest.ts):
 * hero, categories, trending, new, bestsellers, deals, audio, smart-home, feature, feature-2,
 * promo, sale, brands, trust, faq, newsletter, collections, marquee.
 */
const DEMO = "voltnest";
const ADDED = "2026-09-30";

export const ELECTRONICS_THEMES: MarketplaceTheme[] = [
  {
    key: "premium-tech",
    name: "Premium Tech",
    tagline: "Clean, confident, product-first",
    description: "A calm premium layout for considered electronics: inline navigation, full-bleed hero, square category tiles, a trending carousel, an editorial feature story and a brand strip. Grotesk type, generous spacing, soft rounded cards.",
    industry: "electronics",
    style: "premium",
    bestFor: ["Audio", "Premium accessories", "D2C tech brands"],
    features: ["Inline menu", "Editorial feature story", "Trending carousel", "Brand strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#111418", secondary: "#3a4250", accent: "#2563eb", background: "#ffffff", text: "#111418", border: "#e5e7eb", sale: "#d92d20" }, headingFont: "grotesk", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showQuickAdd: true, showRating: true, showSizes: false, showBrand: true, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 35, autoplay: 7 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "trending"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["BrandStrip", { layout: "row", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "trending"], ["TrustBadges", { layout: "grid", tone: "light" }, "trust"]],
    },
  },
  {
    key: "smart-living",
    name: "Smart Living",
    tagline: "Lifestyle-led smart home merchandising",
    description: "Warm, airy and lifestyle-first: centred logo, large hero, room-style collection tiles, a smart-home carousel, two alternating feature stories and FAQs that answer compatibility questions before they're asked.",
    industry: "electronics",
    style: "modern",
    bestFor: ["Smart home", "Connected lighting", "Home office"],
    features: ["Collection tiles", "Alternating feature stories", "FAQ block", "Pill buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f3b3a", secondary: "#5b7b6f", accent: "#e0a458", background: "#f7f5f1", text: "#1d2524", border: "#e4dfd6", sale: "#b4432e" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 0 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductCarousel", { limit: 8 }, "smart-home"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 6, columns: 3 }, "new"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature-2"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "gadget-marketplace",
    name: "Gadget Marketplace",
    tagline: "Dense, fast, built for browsing",
    description: "A product-dense marketplace layout: full-width container, mega menu, compact spacing, round department shortcuts, a deals band, five-column grids and a scrolling brand strip. Made for large catalogues and quick comparison.",
    industry: "electronics",
    style: "marketplace",
    bestFor: ["Large catalogues", "Multi-brand retailers", "Accessories"],
    features: ["Mega menu", "Department shortcuts", "5-column grids", "Deals band"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0f172a", secondary: "#334155", accent: "#f59e0b", background: "#f3f4f6", text: "#0f172a", border: "#e2e8f0", sale: "#dc2626" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: false, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 10, columns: 5 }, "deals"],
        ["ProductCarousel", { limit: 12 }, "trending"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 10, columns: 5 }, "bestsellers"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "minimal-electronics",
    name: "Minimal Electronics",
    tagline: "Quiet design, nothing but the product",
    description: "Stripped back and gallery-like: narrow container, uppercase headings, three-column grids, no badges, one feature story. Lets beautifully shot products carry the store.",
    industry: "electronics",
    style: "minimal",
    bestFor: ["Single-brand stores", "Design-led gadgets", "Small catalogues"],
    features: ["Narrow container", "Three-column grid", "Outline buttons", "No badges"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1a1a1a", secondary: "#6b6b6b", accent: "#1a1a1a", background: "#fafaf9", text: "#1a1a1a", border: "#e7e5e4", sale: "#9a3412" }, headingFont: "geometric-sans", bodyFont: "humanist-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 20, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 6, columns: 3 }, "audio"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "tech-deals",
    name: "Tech Deals",
    tagline: "Urgency, offers and fast checkout",
    description: "Conversion-focused: scrolling offer strip, drawer menu with a centred logo, a sale band with coupon code up top, deal grids with green discount pills, quick add everywhere and trust signals on every page.",
    industry: "electronics",
    style: "conversion",
    bestFor: ["Sale events", "Value brands", "High-volume sellers"],
    features: ["Offer marquee", "Coupon sale band", "Discount pills", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#111111", secondary: "#1f2937", accent: "#ea580c", background: "#ffffff", text: "#111111", border: "#e5e5e5", sale: "#e11d48" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "sm", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "dark", separator: "star" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 25, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "new"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "star" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
