import type { MarketplaceTheme } from "../types";

/**
 * Fashion additions (the ten original fashion presets live in ../catalog.ts). Content slots
 * (scripts/dev/showcase/data/kaya-studio.ts): hero, categories, collections, new, bestsellers,
 * feature, lookbook, promo, sale, social, trust, faq, newsletter, marquee.
 */
const DEMO = "kaya-studio";
const ADDED = "2026-09-30";

export const FASHION_THEMES: MarketplaceTheme[] = [
  {
    key: "runway-editorial",
    name: "Runway Editorial",
    tagline: "Campaign imagery, magazine pacing",
    description: "A fashion-magazine layout: full-bleed campaign hero, editorial serif display type, a masonry lookbook, a two-up feature spread and tall product cards without badges. For labels whose imagery is the brand.",
    industry: "fashion",
    style: "editorial",
    bestFor: ["Designer labels", "Seasonal collections", "Campaign-led brands"],
    features: ["Campaign hero", "Masonry lookbook", "Tall cards", "Drawer menu"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#111111", secondary: "#555555", accent: "#111111", background: "#ffffff", text: "#111111", border: "#e8e8e8", sale: "#b91c1c" }, headingFont: "editorial-serif", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "full", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: false, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "tall", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 15, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 4, columns: 4 }, "new"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 4, columns: 2 }, "bestsellers"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "fashion-marketplace",
    name: "Fashion Marketplace",
    tagline: "Big range, easy filtering, fast add",
    description: "A dense multi-category fashion layout: full-width container, mega menu, round category shortcuts, sale band, five-column grids with sizes on the card and quick add. For wide catalogues across women, men and kids.",
    industry: "fashion",
    style: "marketplace",
    bestFor: ["Multi-brand fashion", "Wide catalogues", "Value fashion"],
    features: ["Mega menu", "Category shortcuts", "Sizes on cards", "5-column grids"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f1f2e", secondary: "#45455a", accent: "#ff3f6c", background: "#ffffff", text: "#1f1f2e", border: "#eaeaf0", sale: "#ff3f6c" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "uppercase", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: true, showBrand: true, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 20, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 10, columns: 5 }, "bestsellers"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 10, columns: 5 }, "new"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
{
    key: "sutra-atelier",
    name: "Sutra Atelier",
    tagline: "Heirloom editorial, arches and curves",
    description: "A luxury ethnic-wear editorial: a full-bleed hero with a numbered slide counter, an italic ribbon, arch-topped category tiles, a tilted carousel, six-column grids, a deep wavy band, compact Add to bag rows, a product spotlight, overlay occasion tiles, a black-and-white reel strip and a full-bleed story banner. Maroon, ink and cream with Cormorant, DM Sans and bold condensed display type.",
    industry: "fashion",
    style: "luxury",
    bestFor: ["Sarees and ethnic wear", "Bridal and festive labels", "Heritage boutiques"],
    features: ["Hero slide counter", "Arch category tiles", "Tilted carousel", "Product spotlight", "Wavy feature band", "Compact add-to-bag rows"],
    demo: null,
    version: "1.0.0",
    added: "2026-10-02",
    preset: {
      tokens: { colors: { primary: "#680624", secondary: "#3a0617", accent: "#a8873a", background: "#fffdf7", text: "#292820", border: "#e7dfd3", sale: "#9b1c1c" }, headingFont: "editorial-serif", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "default", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showAccount: false, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "tall", textAlign: "left", badgeStyle: "minimal", showBadges: true, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, showWishlist: true, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 22, autoplay: 6, counter: true }, "hero"],
        ["Marquee", { size: "small", speed: "slow", tone: "dark", separator: "sparkle", fontStyle: "italic-serif" }, "marquee"],
        ["CategoryGrid", { shape: "arch", limit: 6, headingStyle: "condensed" }, "categories"],
        ["ProductCarousel", { variant: "tilt", limit: 10 }],
        ["ProductGrid", { columns: 6, limit: 6 }, "new"],
        ["ProductGrid", { columns: 6, limit: 6 }, "bestsellers"],
        ["FeatureBand", { edge: "wave", tone: "deep", limit: 4 }],
        ["CompactProducts", { columns: 4, limit: 4 }],
        ["CompactProducts", { columns: 4, limit: 4 }],
        ["Lookbook", { layout: "arches" }, "lookbook"],
        ["ProductSpotlight", { buttonStyle: "curved", limit: 3, headingStyle: "italic" }],
        ["CollectionGrid", { variant: "overlay", columns: 4, limit: 4, headingStyle: "condensed" }, "collections"],
        ["SocialProof", { layout: "strip", filter: "greyscale", showProfile: false, headingStyle: "italic" }, "social"],
        ["EditorialImageText", { variant: "fullbleed", showLogo: true, tone: "dark" }, "feature"],
        ["EditorialImageText", { variant: "journal", headingStyle: "condensed", tone: "light" }],
        ["TrustBadges", { layout: "line", tone: "light" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", speed: "slow", tone: "dark", separator: "sparkle", fontStyle: "italic-serif" }, "marquee"], ["PageContent", {}], ["CompactProducts", { columns: 4, limit: 4 }], ["TrustBadges", { layout: "line", tone: "light" }, "trust"]],
      product: [["PageContent", {}], ["ProductSpotlight", { buttonStyle: "curved", limit: 3, headingStyle: "italic" }], ["ProductCarousel", { variant: "tilt", limit: 10 }], ["TrustBadges", { layout: "line", tone: "light" }, "trust"]],
    },
  },
];
