import type { MarketplaceTheme } from "../types";

/**
 * Footwear. Content slots (scripts/dev/showcase/data/kadam.ts): hero, categories, collections,
 * drops, sneakers, running, bestsellers, new, deals, handcrafted, lookbook, craft, feature, fit,
 * promo, sale, brands, trust, faq, newsletter, marquee.
 */
const DEMO = "kadam";
const ADDED = "2026-10-01";

export const FOOTWEAR_THEMES: MarketplaceTheme[] = [
  {
    key: "street-drop",
    name: "Street Drop",
    tagline: "Loud, fast and built for sneaker drops",
    description: "A streetwear layout for sneaker and casual-shoe labels: a scrolling drop ticker, a full-screen hero, tall uncropped product cards with size chips, a two-up promo pair, a lookbook row and a dark footer. Bold uppercase grotesk type, square buttons and an acid-lime accent on near-black.",
    industry: "footwear",
    style: "bold",
    bestFor: ["Sneaker labels", "Streetwear brands", "Limited drops"],
    features: ["Drop ticker", "Full-screen hero", "Size chips on cards", "Lookbook row"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0d0d0d", secondary: "#262626", accent: "#c8f031", background: "#f4f4f1", text: "#0d0d0d", border: "#dcdcd6", sale: "#ff3b1f" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "tall", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: true, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "large", speed: "fast", tone: "dark", separator: "star" }, "marquee"],
        ["Hero", { height: "full", overlay: 35, autoplay: 6 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "drops"],
        ["PromoBanner", { aspect: "portrait" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 4 }, "sneakers"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["ProductCarousel", { limit: 10 }, "running"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      collection: [["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "star" }, "marquee"], ["PageContent", {}]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "drops"]],
    },
  },
  {
    key: "cobbler-atelier",
    name: "Cobbler Atelier",
    tagline: "Hand-lasted leather, presented like a boutique",
    description: "A premium atelier look for leather shoemakers: centred logo with a drawer menu, a large hero, a three-up edit of best sellers, a craft story with numbers, a feature on fit, collection tiles and a dark newsletter. High-contrast didone headings, outline buttons and portrait cards with no clutter.",
    industry: "footwear",
    style: "premium",
    bestFor: ["Handmade leather shoes", "Formal & wedding footwear", "Made-to-order"],
    features: ["Drawer menu", "Craft story with stats", "Three-up edit", "Collection tiles"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b1d14", secondary: "#6b4a33", accent: "#a8743f", background: "#faf7f2", text: "#231812", border: "#e7ddd0", sale: "#8c2f1f" }, headingFont: "didone", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 35, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bestsellers"],
        ["BrandStory", {}, "craft"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "fit"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["BrandStory", {}, "craft"]],
    },
  },
  {
    key: "minimal-sole",
    name: "Minimal Sole",
    tagline: "Quiet pages, landscape shoe shots",
    description: "A pared-back layout for small catalogues of everyday shoes: narrow container, centred logo with an inline menu, a medium hero, landscape product cards without badges in three columns, a single fit-guide story and size FAQs. Geometric sans, pill outline buttons and a light footer.",
    industry: "footwear",
    style: "minimal",
    bestFor: ["Everyday sneakers", "Single-product brands", "Small catalogues"],
    features: ["Landscape cards", "Fit-guide story", "Size FAQs", "No badges"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1c1c1c", secondary: "#737373", accent: "#1c1c1c", background: "#ffffff", text: "#1c1c1c", border: "#ececec", sale: "#b4532a" }, headingFont: "geometric-sans", bodyFont: "geometric-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "outline", cardRadius: "sm", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-center",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "landscape", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "new"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "fit"],
        ["ProductGrid", { limit: 3, columns: 3 }, "sneakers"],
        ["FAQ", { limit: 5 }, "faq"],
      ],
    },
  },
  {
    key: "shoe-bazaar",
    name: "Shoe Bazaar",
    tagline: "Every size, every style, one dense aisle",
    description: "A marketplace layout for multi-brand shoe stores: full-width container with a mega menu, a banner hero, round category shortcuts, a sale band, five-column deal and running grids with discount pills and size chips, promo tiles, a scrolling label strip and trust badges. Compact spacing and rounded cards for fast browsing.",
    industry: "footwear",
    style: "marketplace",
    bestFor: ["Multi-brand shoe stores", "Family footwear", "Large size ranges"],
    features: ["Mega menu", "Category shortcuts", "5-column grids", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14213d", secondary: "#2c3e63", accent: "#fca311", background: "#f5f6f8", text: "#14213d", border: "#e1e4ea", sale: "#e63946" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: true, secondImageOnHover: false, offerBadge: "Extra 10% on 2+" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 20, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 10, columns: 5 }, "deals"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 10, columns: 5 }, "running"],
        ["ProductCarousel", { limit: 12 }, "bestsellers"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 10 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
  {
    key: "kolhapur-heritage",
    name: "Kolhapur Heritage",
    tagline: "Craft-first footwear with an Indian soul",
    description: "A warm heritage layout for handcrafted Indian footwear: cream and terracotta palette, Marcellus capitals, centred logo with a mega menu, a large hero, the maker's story up front, portrait category tiles, a handcrafted edit in four columns, a feature spread and an ethnic-pattern footer.",
    industry: "footwear",
    style: "heritage",
    bestFor: ["Kolhapuri & handmade chappals", "Juttis and ethnic footwear", "Artisan collectives"],
    features: ["Maker's story first", "Portrait category tiles", "Ethnic footer decoration", "Rounded warm cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#5a2a17", secondary: "#8a4b2a", accent: "#c98a2b", background: "#fbf3e6", text: "#3a2116", border: "#ead9bf", sale: "#a3361f" }, headingFont: "marcellus", bodyFont: "classic-serif", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "lg", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      footerDecor: "ethnic",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "minimal", showQuickAdd: true, showRating: false, showSizes: true, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 7 }, "hero"],
        ["BrandStory", {}, "craft"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "handcrafted"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
];
