import type { MarketplaceTheme } from "../types";

/**
 * Home & Furniture. Content slots (scripts/dev/showcase/data/kasa-living.ts): hero, rooms,
 * categories, new, bestsellers, living, bedroom, workspace, decor, materials, feature, lookbook,
 * promo, sale, trust, faq, newsletter, marquee.
 */
const DEMO = "kasa-living";
const ADDED = "2026-09-30";

export const FURNITURE_THEMES: MarketplaceTheme[] = [
  {
    key: "scandinavian-home",
    name: "Scandinavian Home",
    tagline: "Light wood, soft light, calm rooms",
    description: "Pale and restful: oat background, humanist sans, rounded cards, shop-by-room tiles, a materials story about the wood and finishes, and a living-room edit. Lets natural textures lead.",
    industry: "furniture",
    style: "minimal",
    bestFor: ["Solid-wood furniture", "Small-space living", "Nordic-inspired brands"],
    features: ["Shop by room", "Materials story", "Rounded cards", "Inline menu"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2a26", secondary: "#77705f", accent: "#a4825a", background: "#f7f4ee", text: "#2b2a26", border: "#e7e1d5", sale: "#a3452f" }, headingFont: "humanist-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "lg", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 20, autoplay: 0 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 4, limit: 4 }, "rooms"],
        ["ProductGrid", { limit: 8, columns: 4 }, "living"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "luxury-interiors",
    name: "Luxury Interiors",
    tagline: "Gallery-scale rooms, dark and warm",
    description: "A showroom mood: full-screen hero, didone headings, deep walnut palette, a lookbook of styled rooms, three-up statement pieces and a craftsmanship story. For high-ticket, made-to-order furniture.",
    industry: "furniture",
    style: "luxury",
    bestFor: ["Statement furniture", "Made-to-order", "Interior studios"],
    features: ["Full-screen hero", "Room lookbook", "Craft story", "Dark footer"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f1a16", secondary: "#5c4a3c", accent: "#b88a4a", background: "#f4efe8", text: "#1f1a16", border: "#e2d8ca", sale: "#8c2f2f" }, headingFont: "didone", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 35, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bestsellers"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["BrandStory", {}, "materials"],
        ["ProductCarousel", { limit: 8 }, "bedroom"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
    },
  },
  {
    key: "modern-living",
    name: "Modern Living",
    tagline: "Graphic, confident, room-by-room",
    description: "Bold contemporary: uppercase grotesk headings, charcoal and terracotta, a wide promo pair, alternating room stories, square category tiles and a workspace edit. Good for design-forward D2C furniture.",
    industry: "furniture",
    style: "modern",
    bestFor: ["D2C furniture", "Work-from-home", "Urban apartments"],
    features: ["Promo tiles", "Category tiles", "Alternating room stories", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1d1d1b", secondary: "#4a4a45", accent: "#c4633b", background: "#ffffff", text: "#1d1d1b", border: "#e6e6e3", sale: "#c4332b" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "sm", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "workspace"],
        ["FAQ", { limit: 6 }, "faq"],
      ],
      product: [["PageContent", {}], ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"], ["ProductCarousel", { limit: 8 }, "bestsellers"]],
    },
  },
  {
    key: "home-decor-market",
    name: "Home Décor Market",
    tagline: "Everything for the home, easy to browse",
    description: "A dense home-store layout: full-width container, mega menu, round department shortcuts, a sale band, five-column décor grids and trust marquee. For big décor, lighting and furnishing catalogues.",
    industry: "furniture",
    style: "marketplace",
    bestFor: ["Home décor", "Lighting & furnishings", "Large catalogues"],
    features: ["Mega menu", "Department shortcuts", "Sale band", "5-column grids"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#23302b", secondary: "#4e5e57", accent: "#d08a2e", background: "#f5f4f0", text: "#1f2622", border: "#e3e1da", sale: "#c2410c" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 10, columns: 5 }, "decor"],
        ["CollectionGrid", { mode: "manual", columns: 4, limit: 4 }, "rooms"],
        ["ProductGrid", { limit: 10, columns: 5 }, "bestsellers"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "artisan-home",
    name: "Artisan Home",
    tagline: "Handmade, storied, slow-made",
    description: "Warm and editorial: soft serif headings, terracotta and clay, centred logo, a maker story, lookbook and two-up product rows. For handcrafted, small-batch and heritage home goods.",
    industry: "furniture",
    style: "heritage",
    bestFor: ["Handcrafted furniture", "Small-batch décor", "Maker brands"],
    features: ["Maker story", "Lookbook", "Serif headings", "Two-up grid"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#3b2a20", secondary: "#7a5a44", accent: "#b5562f", background: "#f6efe6", text: "#33241b", border: "#e6d9c8", sale: "#a3361f" }, headingFont: "classic-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "md", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "materials"],
        ["ProductGrid", { limit: 4, columns: 2 }, "new"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "decor"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
];
