import type { MarketplaceTheme } from "../types";

/**
 * General / Multi-category. Content slots (scripts/dev/showcase/data/sabkuch.ts): marquee, hero,
 * categories, collections, new, bestsellers, deals, kitchen, home, care, desk, gadgets, addons,
 * promo, story, feature, feature-2, lookbook, social, faq, trust, brands, sale, newsletter.
 */
const DEMO = "sabkuch";
const ADDED = "2026-10-01";

export const GENERAL_THEMES: MarketplaceTheme[] = [
  {
    key: "sabkuch-bazaar",
    name: "Sabkuch Bazaar",
    tagline: "Every aisle on one busy, easy page",
    description: "A dense marketplace layout for stores that sell a bit of everything: full-width container, mega menu, compact spacing, square department tiles, five-column grids for kitchen and home, a gadgets carousel, a strip of house ranges and trust badges. Built for shoppers who arrive knowing what they need.",
    industry: "general",
    style: "marketplace",
    bestFor: ["Multi-category stores", "Large catalogues", "Repeat everyday shoppers"],
    features: ["Mega menu", "Department tiles", "5-column grids", "House-range strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0f3b5f", secondary: "#1f5f8b", accent: "#f5a623", background: "#f4f6f9", text: "#14263a", border: "#dde3ec", sale: "#d7263d" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "kitchen"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 5 }, "home"],
        ["ProductCarousel", { limit: 12 }, "gadgets"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "plain-shelf",
    name: "Plain Shelf",
    tagline: "White space and well-chosen things",
    description: "A minimal layout for small, curated general stores: a short hero, new arrivals first, an editorial note on the desk edit, a two-column grid with large photos and an FAQ. Clean sans type, sharp badge-free cards, a narrow column and a light footer let mixed products sit together calmly.",
    industry: "general",
    style: "minimal",
    bestFor: ["Curated concept stores", "Small mixed catalogues", "Design-led gifting"],
    features: ["Short hero", "Two-column feature grid", "FAQ block", "Badge-free cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1d1d1b", secondary: "#5b5b57", accent: "#8a9a82", background: "#ffffff", text: "#1d1d1b", border: "#ebebe8", sale: "#b8452f" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["ProductGrid", { limit: 4, columns: 2 }, "desk"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "everyday-modern",
    name: "Everyday Modern",
    tagline: "Bright, friendly and organised by room",
    description: "A modern lifestyle layout that shops like a well-arranged home: centred logo with an inline menu, a large hero, round category bubbles, a best-seller carousel, three curated edits, a three-column kitchen grid, a story about the store and a masonry lookbook. Geometric sans headings and rounded cards.",
    industry: "general",
    style: "modern",
    bestFor: ["Home & lifestyle stores", "Gift shops", "Instagram-led D2C"],
    features: ["Round category bubbles", "Curated edit tiles", "Brand story with stats", "Masonry lookbook"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#23443b", secondary: "#3e6b5d", accent: "#e98a5d", background: "#fbf8f4", text: "#1f2e29", border: "#ece4da", sale: "#c8462e" }, headingFont: "geometric-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "lg", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "filled", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 6, columns: 3 }, "kitchen"],
        ["BrandStory", {}, "story"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "bestsellers"]],
    },
  },
  {
    key: "loud-aisle",
    name: "Loud Aisle",
    tagline: "High contrast, big type, impossible to scroll past",
    description: "A bold, poster-like layout for general stores with attitude: a scrolling offer strip, a full-screen hero, chunky grotesk capitals, a four-column gadgets grid, square promo tiles, a dark editorial feature, a photo mosaic and an add-on carousel. Electric yellow on near-black with pill buttons.",
    industry: "general",
    style: "bold",
    bestFor: ["Youth-led lifestyle brands", "Gadgets & accessories", "Drop-style launches"],
    features: ["Offer marquee", "Full-screen hero", "Photo mosaic", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#111111", secondary: "#2b2b2b", accent: "#ffd23f", background: "#fafaf7", text: "#111111", border: "#e4e4de", sale: "#ff3b30" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "large", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["Hero", { height: "full", overlay: 30, autoplay: 6 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "gadgets"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature"],
        ["SocialProof", { layout: "mosaic", showProfile: false }, "social"],
        ["ProductCarousel", { limit: 10 }, "addons"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
    },
  },
  {
    key: "deal-dhamaka",
    name: "Deal Dhamaka",
    tagline: "Offers up top, checkout in a tap",
    description: "Conversion-first for general stores that run offers: centred logo with a drawer menu, a fast offer ticker, a coupon sale band, a deals grid with discount pills, an under-₹499 add-on carousel, tall category cards, an FAQ and trust signals on every page.",
    industry: "general",
    style: "conversion",
    bestFor: ["Sale events", "Value multi-category stores", "WhatsApp & social traffic"],
    features: ["Coupon sale band", "Discount pills", "Add-on carousel", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#7a1037", secondary: "#a3204f", accent: "#1fb36b", background: "#ffffff", text: "#2a0f1b", border: "#f1e2e8", sale: "#e01e5a" }, headingFont: "humanist-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free delivery ₹599+" },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "addons"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["FAQ", { limit: 4 }, "faq"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
