import type { MarketplaceTheme } from "../types";

/**
 * Bakery & Gourmet Food. Content slots (scripts/dev/showcase/data/crumb-and-co.ts): hero, story,
 * collections, cakes, feature, chocolates, lookbook, newsletter, trust, categories, breads,
 * feature-2, bestsellers, faq, marquee, cookies, promo, social, new, sale, deals, treats, hampers,
 * brands.
 */
const DEMO = "crumb-and-co";
const ADDED = "2026-10-01";

export const GOURMET_THEMES: MarketplaceTheme[] = [
  {
    key: "patisserie-noir",
    name: "Pâtisserie Noir",
    tagline: "Dark chocolate, gold leaf and a slow scroll",
    description: "A luxury layout for patisseries and chocolatiers: centred logo, a full-screen hero, the baker's story with numbers, three gifting edits, a three-column cake counter in tall portrait cards, a dark editorial on tempering and a row lookbook. High-contrast Didone headings, outline buttons and a cocoa-black footer.",
    industry: "gourmet",
    style: "luxury",
    bestFor: ["Patisseries & cake studios", "Chocolatiers", "Premium gifting boxes"],
    features: ["Full-screen hero", "Brand story with stats", "Portrait cake cards", "Lookbook row"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1e1512", secondary: "#4a3229", accent: "#c09a5b", background: "#f7f2ec", text: "#1e1512", border: "#e6dccf", sale: "#8f2f24" }, headingFont: "didone", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 6, columns: 3 }, "cakes"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature"],
        ["ProductGrid", { limit: 3, columns: 3 }, "chocolates"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductGrid", { limit: 3, columns: 3 }, "chocolates"]],
    },
  },
  {
    key: "hearth-and-crust",
    name: "Hearth & Crust",
    tagline: "A neighbourhood bakery, open since dawn",
    description: "A heritage layout for bread-first bakeries: logo left with an inline menu, a large left-aligned hero, a baker's-promise strip right under it, tall portrait aisle cards, a four-column bread shelf, a flour-dusted story, a best-seller carousel and a long FAQ about freshness and storage. Soft Fraunces serif on warm wheat.",
    industry: "gourmet",
    style: "heritage",
    bestFor: ["Sourdough & bread bakeries", "Cafe-bakeries", "Daily fresh orders"],
    features: ["Baker's promise strip", "Portrait aisle cards", "Bread shelf grid", "Freshness FAQ"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#5b3a1e", secondary: "#8a5a2b", accent: "#c7802f", background: "#faf4e8", text: "#3a2614", border: "#ecdfc6", sale: "#b0412a" }, headingFont: "classic-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 4 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "breads"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature-2"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "frosted-pop",
    name: "Frosted Pop",
    tagline: "Sprinkles, cookies and a lot of pink",
    description: "A bold, playful layout for cookie, cupcake and dessert brands: a fast scrolling offer strip, berry pink on cocoa, round flavour bubbles, a cookie counter grid, square promo tiles for party boxes and a photo mosaic. Chunky grotesk capitals, pill buttons and quick add on every card.",
    industry: "gourmet",
    style: "bold",
    bestFor: ["Cookie & dessert brands", "Cloud kitchens", "Instagram-led bakers"],
    features: ["Offer marquee", "Round flavour bubbles", "Party-box promo tiles", "Photo mosaic"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#3b1f2b", secondary: "#6a2c48", accent: "#ff5c8a", background: "#fff6f8", text: "#3b1f2b", border: "#f6dbe3", sale: "#e0352b" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Marquee", { size: "large", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "cookies"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["ProductCarousel", { limit: 10 }, "new"],
        ["SocialProof", { layout: "mosaic", showProfile: false }, "social"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "cookies"]],
    },
  },
  {
    key: "hamper-counter",
    name: "Hamper Counter",
    tagline: "Festive gifting, offers and a fast checkout",
    description: "Conversion-first for gifting season: centred logo with a drawer menu, a coupon sale band up top, a gift-hamper grid, deal cards with discount pills, an under-₹499 add-on carousel, square aisle tiles and trust signals on every page. Built for Diwali, Rakhi and corporate orders.",
    industry: "gourmet",
    style: "conversion",
    bestFor: ["Festive & corporate gifting", "Hamper boxes", "Sale events"],
    features: ["Coupon sale band", "Hamper grid", "Add-on carousel", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14443a", secondary: "#1f6354", accent: "#e8a33d", background: "#ffffff", text: "#132a24", border: "#e2ece8", sale: "#d0342c" }, headingFont: "marcellus", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "sm", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Gift note free" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 6, columns: 3 }, "hampers"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "treats"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "treats"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
  {
    key: "flour-and-white",
    name: "Flour & White",
    tagline: "Quiet, white and all about the bake",
    description: "A minimal layout that lets the crumb do the talking: a short hero, new bakes first, an editorial note on slow fermentation, a two-column feature of gift boxes with big images, a strip of house ranges and an FAQ. One clean sans throughout, sharp badge-free cards and a light footer.",
    industry: "gourmet",
    style: "minimal",
    bestFor: ["Small-batch home bakers", "Single-product brands", "Curated pantries"],
    features: ["Short hero", "Two-column feature grid", "House-range strip", "Badge-free cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#262320", secondary: "#5f5a53", accent: "#b9a58a", background: "#ffffff", text: "#262320", border: "#ece9e4", sale: "#b4533c" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductGrid", { limit: 4, columns: 2 }, "hampers"],
        ["BrandStrip", { layout: "row", tone: "light" }, "brands"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
];
