import type { MarketplaceTheme } from "../types";

/**
 * Grocery & Food. Content slots (scripts/dev/showcase/data/harvest-basket.ts): hero, categories,
 * fresh, essentials, snacks, beverages, bestsellers, new, offers, story, feature, promo, sale, trust, faq,
 * newsletter, marquee, collections.
 */
const DEMO = "harvest-basket";
const ADDED = "2026-09-30";

export const GROCERY_THEMES: MarketplaceTheme[] = [
  {
    key: "fresh-market",
    name: "Fresh Market",
    tagline: "Bright, fresh, aisle-by-aisle",
    description: "A friendly neighbourhood-market feel: leaf-green palette, round department shortcuts, a fresh-produce carousel, an offers band and quick add on every card. Designed for quick weekly shops.",
    industry: "grocery",
    style: "modern",
    bestFor: ["Fresh produce", "Neighbourhood grocers", "Farm-to-home"],
    features: ["Department shortcuts", "Offers band", "Quick add", "Delivery info bar"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1e5631", secondary: "#3f7a4f", accent: "#f2a93b", background: "#ffffff", text: "#1b2a1f", border: "#e3ece4", sale: "#d9412b" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: false, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["ProductCarousel", { limit: 12 }, "fresh"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "essentials"],
        ["ProductCarousel", { limit: 12 }, "snacks"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 10 }, "bestsellers"]],
    },
  },
  {
    key: "organic-grocery",
    name: "Organic Grocery",
    tagline: "Slow food, honest sourcing",
    description: "Warm and trustworthy: cream background, soft serif headings, a sourcing story about the farms, collection tiles, three-column best sellers and an FAQ about freshness and delivery.",
    industry: "grocery",
    style: "heritage",
    bestFor: ["Organic staples", "Cold-pressed oils", "Millets & pulses"],
    features: ["Sourcing story", "Collection tiles", "FAQ", "Serif headings"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#3d4a2a", secondary: "#6f7a4a", accent: "#c07a2c", background: "#faf6ee", text: "#2f3522", border: "#e8e0cf", sale: "#b2452c" }, headingFont: "classic-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "minimal", showQuickAdd: true, showRating: true, showSizes: true, showBrand: false, secondImageOnHover: false },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bestsellers"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "supermarket",
    name: "Supermarket",
    tagline: "Big basket, fast browsing",
    description: "A dense supermarket layout: full-width container, compact spacing, mega menu, scrolling offer strip, five-column product grids by aisle and a promo tile pair. Built for large everyday catalogues.",
    industry: "grocery",
    style: "marketplace",
    bestFor: ["Supermarkets", "Large catalogues", "Everyday essentials"],
    features: ["Mega menu", "Offer marquee", "5-column grids", "Promo tiles"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0b3d2e", secondary: "#1f5b47", accent: "#e53935", background: "#f4f6f5", text: "#10231c", border: "#dfe6e2", sale: "#e53935" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "accent", separator: "dot" }, "marquee"],
        ["Hero", { height: "medium", overlay: 20, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 10, columns: 5 }, "essentials"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 10, columns: 5 }, "beverages"],
        ["ProductGrid", { limit: 10, columns: 5 }, "snacks"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "accent", separator: "dot" }, "marquee"], ["PageContent", {}]],
    },
  },
  {
    key: "gourmet-pantry",
    name: "Gourmet Pantry",
    tagline: "A specialty food hall, online",
    description: "Premium and editorial for fine foods: didone headings, deep aubergine and saffron, full-height hero, two-up curated picks, a feature on origins and a new-arrivals carousel. Fewer products, more story.",
    industry: "grocery",
    style: "premium",
    bestFor: ["Specialty foods", "Teas & coffee", "Gift hampers"],
    features: ["Origin story", "Two-up picks", "Gift-ready tone", "Dark footer"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2a1a24", secondary: "#5a3b4c", accent: "#d9a13b", background: "#fbf8f3", text: "#241820", border: "#ebe2d8", sale: "#a3283a" }, headingFont: "didone", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 35, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 4, columns: 2 }, "bestsellers"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["PromoBanner", { aspect: "portrait" }, "promo"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
    },
  },
  {
    key: "daily-deals-grocery",
    name: "Daily Deals",
    tagline: "Offers first, basket fast",
    description: "Conversion-first: bold uppercase headings, drawer menu, a coupon sale band at the top, deal grids with discount pills, quick add and trust signals on every page. For promotions-led grocers.",
    industry: "grocery",
    style: "conversion",
    bestFor: ["Value grocers", "Bulk packs", "Promotion-led stores"],
    features: ["Coupon sale band", "Discount pills", "Quick add", "Trust marquee"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14213d", secondary: "#2b3a5c", accent: "#fca311", background: "#ffffff", text: "#14213d", border: "#e5e7eb", sale: "#e11d48" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: true, showBrand: false, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "offers"],
        ["Hero", { height: "medium", overlay: 25, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["ProductCarousel", { limit: 12 }, "bestsellers"],
        ["ProductCarousel", { limit: 12 }, "fresh"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["SaleBanner", {}, "sale"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "offers"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
