import type { MarketplaceTheme } from "../types";

/**
 * Health & Wellness. Content slots (scripts/dev/showcase/data/aarogya.ts): hero, categories,
 * collections, bestsellers, new, ayurveda, teas, nutrition, yoga, self-care, offers, story,
 * feature, feature-2, promo, lookbook, sale, trust, faq, newsletter, marquee.
 */
const DEMO = "aarogya";
const ADDED = "2026-10-01";

export const HEALTH_THEMES: MarketplaceTheme[] = [
  {
    key: "ayurveda-heritage",
    name: "Ayurveda Heritage",
    tagline: "Warm, rooted and herb-led",
    description: "A calm, traditional feel for Ayurvedic and herbal ranges: classic capitals for headings, turmeric and deep leaf-green on cream, a centred hero, a sourcing story with figures, round category tiles, three-column herb grid and an FAQ that answers label questions honestly.",
    industry: "health",
    style: "heritage",
    bestFor: ["Ayurvedic churnas & herbs", "Herbal teas", "Traditional wellness brands"],
    features: ["Sourcing story with figures", "Round category tiles", "Three-column grid", "FAQ block"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2f4a2c", secondary: "#7a5a2e", accent: "#c98a1b", background: "#faf5ea", text: "#2a2f22", border: "#e7dcc6", sale: "#a5402a" }, headingFont: "marcellus", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 35, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 5 }, "categories"],
        ["ProductGrid", { limit: 3, columns: 3 }, "ayurveda"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "teas"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "bestsellers"]],
    },
  },
  {
    key: "clinical-wellness",
    name: "Clinical Wellness",
    tagline: "Clean, factual, label-first",
    description: "A pharmacy-clean layout for nutrition and everyday wellness: white and sea-teal, Inter throughout, inline menu, a short hero, need-based collection tiles, four-column grids with quick add, a trust strip and FAQs under every product. Clear labels, no hype.",
    industry: "health",
    style: "minimal",
    bestFor: ["Nutrition & superfoods", "Everyday wellness", "Label-led D2C brands"],
    features: ["Inline menu", "Shop by need tiles", "FAQ on product pages", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0f4c5c", secondary: "#4f7c86", accent: "#2a9d8f", background: "#ffffff", text: "#16262b", border: "#e2eaec", sale: "#c2410c" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "sm", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: true, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 40, autoplay: 0 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 4, columns: 4 }, "nutrition"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["FAQ", { limit: 8 }, "faq"],
      ],
      product: [["PageContent", {}], ["FAQ", { limit: 4 }, "faq"], ["ProductGrid", { limit: 4, columns: 4 }, "nutrition"]],
    },
  },
  {
    key: "studio-wellness",
    name: "Studio Wellness",
    tagline: "Bright, active, made for movement",
    description: "An energetic yoga-studio look: drawer menu on every screen, a full-screen hero slideshow, uppercase geometric headings, pill buttons, a yoga gear carousel, square promo tiles, a lookbook strip of practice moments and a scrolling trust bar. For active-living and yoga brands.",
    industry: "health",
    style: "modern",
    bestFor: ["Yoga & pilates gear", "Active lifestyle", "Fitness accessories"],
    features: ["Full-screen slideshow", "Drawer menu", "Lookbook strip", "Pill buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1d2a44", secondary: "#4b5f8a", accent: "#ff7a59", background: "#f7f8fb", text: "#1d2a44", border: "#e3e7ef", sale: "#e0453a" }, headingFont: "geometric-sans", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 6 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "yoga"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["ProductCarousel", { limit: 10 }, "new"],
        ["TrustBadges", { layout: "marquee", tone: "dark" }, "trust"],
      ],
      collection: [["PageContent", {}], ["PromoBanner", { aspect: "square" }, "promo"]],
    },
  },
  {
    key: "spa-sanctuary",
    name: "Spa Sanctuary",
    tagline: "Slow, quiet and indulgent",
    description: "A premium spa-counter mood for aromatherapy and self-care: Playfair display headings, espresso, sage and brushed gold, centred logo with a drawer menu, two-up curated picks, an alternating ritual story, three ritual collections and a dark newsletter band. Fewer products, more calm.",
    industry: "health",
    style: "premium",
    bestFor: ["Essential oils & aromatherapy", "Spa & bath rituals", "Gift sets"],
    features: ["Two-up curated grid", "Ritual story", "Dark newsletter band", "Centred cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2420", secondary: "#6b7b62", accent: "#b89560", background: "#f6f2ec", text: "#2b2420", border: "#e6ddd1", sale: "#8e3b2f" }, headingFont: "playfair", bodyFont: "geometric-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "tall", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 40, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 4, columns: 2 }, "self-care"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature-2"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "bestsellers"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"], ["ProductCarousel", { limit: 8 }, "self-care"]],
    },
  },
  {
    key: "wellness-deals",
    name: "Wellness Deals",
    tagline: "Offers first, restock fast",
    description: "A conversion-led wellness store: scrolling offer strip, mega menu, a banner hero that never crops, a coupon band, five-column deal grids with discount pills, square category tiles, promo tiles and trust signals on collection and product pages. Built for restocks and sale events.",
    industry: "health",
    style: "conversion",
    bestFor: ["Large wellness catalogues", "Sale events", "Subscription & restock buyers"],
    features: ["Offer marquee", "Coupon sale band", "5-column grids", "Trust strip on every page"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14532d", secondary: "#166534", accent: "#facc15", background: "#f5f7f4", text: "#132018", border: "#dfe7df", sale: "#dc2626" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: true, showSizes: true, showBrand: false, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "accent", separator: "dot" }, "marquee"],
        ["Hero", { height: "medium", overlay: 25, autoplay: 5 }, "hero"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 10, columns: 5 }, "offers"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 5 }, "categories"],
        ["ProductGrid", { limit: 10, columns: 5 }, "bestsellers"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductCarousel", { limit: 12 }, "nutrition"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["SaleBanner", {}, "sale"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 10 }, "offers"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
