import type { MarketplaceTheme } from "../types";

/**
 * Jewellery & Accessories. Content slots (scripts/dev/showcase/data/suvarna.ts): hero, bridal,
 * craft, collections, feature, new, newsletter, categories, heritage, marquee, lookbook, faq,
 * trust, everyday, styling, social, sale, offers, bestsellers, promo.
 */
const DEMO = "suvarna";
const ADDED = "2026-10-01";

export const JEWELLERY_THEMES: MarketplaceTheme[] = [
  {
    key: "gilded-luxe",
    name: "Gilded Luxe",
    tagline: "Black velvet, warm gold, slow reveal",
    description: "A high-jewellery salon online: full-screen hero, high-contrast serif headings, a three-up bridal edit, a craftsmanship story with figures, collection tiles and a dark footer. Generous spacing lets each piece breathe.",
    industry: "jewellery",
    style: "luxury",
    bestFor: ["Fine & bridal jewellery", "Gold and diamond houses", "High-value pieces"],
    features: ["Full-screen hero", "Craft story with figures", "Three-column bridal edit", "Centred cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14110d", secondary: "#4a3d2c", accent: "#b8924a", background: "#faf7f1", text: "#14110d", border: "#e8dfcf", sale: "#8a2b2b" }, headingFont: "didone", bodyFont: "geometric-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 35, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bridal"],
        ["BrandStory", {}, "craft"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["BrandStory", {}, "craft"], ["ProductCarousel", { limit: 8 }, "bridal"]],
    },
  },
  {
    key: "temple-heritage",
    name: "Temple Heritage",
    tagline: "Kundan, temple gold and festive maroon",
    description: "Rooted in South Indian temple jewellery and Rajasthani kundan: classic capitals, maroon and antique gold on ivory, round category shortcuts, a heritage edit, a scrolling festive strip, a lookbook row, FAQs and an ethnic footer.",
    industry: "jewellery",
    style: "heritage",
    bestFor: ["Temple & kundan jewellery", "Festive and wedding wear", "Family jewellers"],
    features: ["Round category shortcuts", "Festive marquee", "Lookbook row", "Ethnic footer"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#6b1d1d", secondary: "#8c5a2b", accent: "#c9a14a", background: "#fbf5ea", text: "#2e1a12", border: "#ead9bf", sale: "#a3261b" }, headingFont: "marcellus", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "filled", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      footerDecor: "ethnic",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 35, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 7 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "heritage"],
        ["Marquee", { size: "medium", speed: "slow", tone: "dark", separator: "star" }, "marquee"],
        ["BrandStory", {}, "craft"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["FAQ", { limit: 6 }, "faq"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", speed: "slow", tone: "dark", separator: "star" }, "marquee"], ["PageContent", {}]],
    },
  },
  {
    key: "everyday-fine",
    name: "Everyday Fine",
    tagline: "Light, clean, made to wear daily",
    description: "For demi-fine and silver brands: logo left with an inline menu, a compact hero, a four-up everyday edit straight after, square category tiles, a styling note and a scrolling trust strip. Outline pill buttons and a light footer keep it quiet.",
    industry: "jewellery",
    style: "minimal",
    bestFor: ["Sterling silver", "Demi-fine & daily wear", "Small D2C catalogues"],
    features: ["Compact hero", "Square category tiles", "Styling note", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#262626", secondary: "#737373", accent: "#a68a64", background: "#ffffff", text: "#262626", border: "#ececec", sale: "#b4532a" }, headingFont: "geometric-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "outline", cardRadius: "md", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "everyday"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "styling"],
        ["ProductGrid", { limit: 4, columns: 4 }, "new"],
        ["TrustBadges", { layout: "marquee", tone: "light" }, "trust"],
      ],
    },
  },
  {
    key: "jewel-journal",
    name: "Jewel Journal",
    tagline: "A lookbook first, a shop second",
    description: "Story-led and image-heavy: drawer menu on every screen, a tall photographic hero, an editorial feature spread, a masonry lookbook, two-up product rows on tall cards, a styling spread and a photo mosaic. For brands with a strong visual voice.",
    industry: "jewellery",
    style: "editorial",
    bestFor: ["Designer jewellery labels", "Seasonal campaigns", "Content-led brands"],
    features: ["Drawer menu", "Masonry lookbook", "Two-up grid", "Photo mosaic"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f1b18", secondary: "#5e554c", accent: "#9a3b2e", background: "#f7f3ee", text: "#1f1b18", border: "#e4ddd3", sale: "#9a3b2e" }, headingFont: "editorial-serif", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "tall", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 0 }, "hero"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["ProductGrid", { limit: 4, columns: 2 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "styling"],
        ["SocialProof", { layout: "mosaic", showProfile: false }, "social"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "jewel-bazaar",
    name: "Jewel Bazaar",
    tagline: "Offers up front, gifting made easy",
    description: "Built to convert festive and gifting traffic: scrolling offer strip, rotating announcements, autoplay hero, portrait category tiles, a sale band, an offers carousel, a dense five-column best-seller grid, gifting promo tiles and trust badges on every page.",
    industry: "jewellery",
    style: "conversion",
    bestFor: ["Fashion & imitation jewellery", "Festive sales", "Gifting stores"],
    features: ["Offer marquee", "Sale band", "Five-column grid", "Trust on every page"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#4a1942", secondary: "#7d3c6f", accent: "#e0a526", background: "#ffffff", text: "#231020", border: "#efe3ec", sale: "#d1263f" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free gift box" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "accent", separator: "dot" }, "marquee"],
        ["Hero", { height: "large", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["SaleBanner", {}, "sale"],
        ["ProductCarousel", { limit: 12 }, "offers"],
        ["ProductGrid", { limit: 10, columns: 5 }, "bestsellers"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["SaleBanner", {}, "sale"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "offers"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
