import type { MarketplaceTheme } from "../types";

/**
 * Kids & Baby. Content slots (scripts/dev/showcase/data/nanhe.ts): hero, marquee, categories,
 * toys, promo, bestsellers, trust, newsletter, story, baby, feature, feature-2, new, faq,
 * collections, learning, school, brands, sale, deals, gifts.
 */
const DEMO = "nanhe";
const ADDED = "2026-10-01";

export const KIDS_THEMES: MarketplaceTheme[] = [
  {
    key: "toybox-pop",
    name: "Toybox Pop",
    tagline: "Bright, bouncy and made for play",
    description: "A playful, high-energy layout for toy shops: a scrolling offer strip, sunshine-yellow accents on deep navy, round category bubbles, a toy carousel, chunky square promo tiles and pill buttons everywhere. Geometric uppercase headings keep it loud but tidy.",
    industry: "kids",
    style: "bold",
    bestFor: ["Toy stores", "Soft toys & plush", "Gifting for kids"],
    features: ["Offer marquee", "Round category bubbles", "Square promo tiles", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1d2a6b", secondary: "#e8505b", accent: "#ffc53d", background: "#fffaf0", text: "#1b2152", border: "#f2e6cc", sale: "#e8505b" }, headingFont: "geometric-sans", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Marquee", { size: "medium", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "toys"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["TrustBadges", { layout: "marquee", tone: "dark" }, "trust"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "toys"]],
    },
  },
  {
    key: "little-sprout",
    name: "Little Sprout",
    tagline: "Soft, natural and calm for the early years",
    description: "A quiet, organic layout for baby essentials: centred logo, cream background, soft serif headings, a short story about materials, three-column grids without badges and an FAQ that answers fabric and safety questions. Feels like a well-kept nursery.",
    industry: "kids",
    style: "minimal",
    bestFor: ["Organic baby clothing", "Muslin & cotton basics", "Baby care"],
    features: ["Materials story", "Three-column grid", "FAQ block", "Outline buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#4a5a46", secondary: "#8a9a7b", accent: "#d9a48f", background: "#faf7f1", text: "#3a4237", border: "#ebe4d8", sale: "#b8604a" }, headingFont: "classic-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "outline", cardRadius: "md", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: false },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: true, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 6, columns: 3 }, "baby"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductGrid", { limit: 6, columns: 3 }, "new"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "playground-modern",
    name: "Playground Modern",
    tagline: "Clean, colourful and story-led",
    description: "A modern lifestyle layout for design-minded kids' brands: full-screen hero, four collection tiles, a new-arrivals carousel and two alternating feature stories around a learning-toys grid. Clean sans type, portrait cards and a light footer.",
    industry: "kids",
    style: "modern",
    bestFor: ["Learning toys", "Books & art supplies", "D2C kids' brands"],
    features: ["Full-screen hero", "Collection tiles", "Alternating feature stories", "Portrait cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0f5c66", secondary: "#3d8c95", accent: "#ff8a5c", background: "#ffffff", text: "#16323a", border: "#e3eef0", sale: "#e0533d" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 7 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 4, limit: 4 }, "collections"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "learning"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "kids-bazaar",
    name: "Kids Bazaar",
    tagline: "Everything for kids, in one busy aisle",
    description: "A dense marketplace layout for large kids' catalogues: full-width container, mega menu, compact spacing, square department tiles, five-column grids, a back-to-school carousel and a scrolling strip of product lines. Built for browsing many ages and categories quickly.",
    industry: "kids",
    style: "marketplace",
    bestFor: ["Multi-category kids' stores", "Toys to school supplies", "Large catalogues"],
    features: ["Mega menu", "Department tiles", "5-column grids", "Product-line strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2d42", secondary: "#4a4e69", accent: "#3a86ff", background: "#f4f6fb", text: "#22243a", border: "#e1e5ef", sale: "#ef233c" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 10, columns: 5 }, "bestsellers"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 10, columns: 5 }, "toys"],
        ["ProductCarousel", { limit: 12 }, "school"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "tiny-deals",
    name: "Tiny Deals",
    tagline: "Offers, gift ideas and quick checkout",
    description: "Conversion-first for kids' stores running offers: centred logo with a drawer menu, a coupon sale band before anything else, deal grids with green discount pills, a gift-ideas carousel, quick add on every card and trust signals on every page.",
    industry: "kids",
    style: "conversion",
    bestFor: ["Sale events", "Birthday & gifting", "Value kids' brands"],
    features: ["Coupon sale band", "Discount pills", "Gift-ideas carousel", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#5b2a86", secondary: "#7d4fa8", accent: "#ff6f91", background: "#ffffff", text: "#2a1a3a", border: "#eee4f5", sale: "#e11d48" }, headingFont: "humanist-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "sm", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free gift wrap" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "gifts"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 5 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["FAQ", { limit: 4 }, "faq"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
