import type { MarketplaceTheme } from "../types";

/**
 * Organic & Natural Products. Content slots (scripts/dev/showcase/data/bhoomi-organics.ts): hero,
 * marquee, categories, collections, bestsellers, oils, pantry, home-care, new, refills, story,
 * feature, feature-2, promo, social, lookbook, sale, brands, trust, faq, newsletter.
 */
const DEMO = "bhoomi-organics";
const ADDED = "2026-10-01";

export const ORGANIC_THEMES: MarketplaceTheme[] = [
  {
    key: "mitti-roots",
    name: "Mitti Roots",
    tagline: "Warm, earthy and rooted in the farm",
    description: "A heritage layout in clay, turmeric and cream for farm-to-home organic brands: centred logo, a large farm hero, trust signals up front, round pantry bubbles, a best-seller grid, a brand story with farm numbers, a three-column oil edit and an editorial on how things are made. Soft serif headings and rounded buttons.",
    industry: "organic",
    style: "heritage",
    bestFor: ["Farm-to-home brands", "Wood-pressed oils & ghee", "Traceable sourcing stories"],
    features: ["Trust strip under the hero", "Round category bubbles", "Brand story with stats", "How-it's-made editorial"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#7a3b1f", secondary: "#9c5a2e", accent: "#d69a2d", background: "#fbf5ea", text: "#3a2416", border: "#ecdcc4", sale: "#b5381f" }, headingFont: "classic-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "md", containerWidth: "default", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "bestsellers"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 3, columns: 3 }, "oils"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["FAQ", { limit: 5 }, "faq"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "bestsellers"]],
    },
  },
  {
    key: "field-almanac",
    name: "Field Almanac",
    tagline: "A slow-living journal for natural goods",
    description: "An editorial, magazine-paced layout for brands that sell with stories: full-screen hero, two alternating image-and-text essays, a masonry lookbook of ingredients, three curated collection tiles and a new-season carousel, closing with the farm story. Cormorant headings, outline buttons, sharp cards and plenty of air.",
    industry: "organic",
    style: "editorial",
    bestFor: ["Story-led natural brands", "Seasonal small-batch makers", "Slow-living lifestyle shops"],
    features: ["Full-screen hero", "Alternating essays", "Masonry lookbook", "Collection tiles"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2e3a2c", secondary: "#5d6b53", accent: "#a8743f", background: "#f6f3ec", text: "#252b22", border: "#e2ddd0", sale: "#9a3b26" }, headingFont: "editorial-serif", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: false, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 25, autoplay: 0 }, "hero"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature-2"],
        ["ProductCarousel", { limit: 10 }, "new"],
        ["BrandStory", {}, "story"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "plastic-free",
    name: "Plastic Free",
    tagline: "Quiet, white and zero-waste",
    description: "A minimal layout for zero-waste and refill stores: a short hero, a slim text strip of your promises, new products in a calm three-column grid, a two-column home-care edit with big images, one editorial on a simple swap and an FAQ. One clean sans throughout, no badges, a narrow container and a light footer.",
    industry: "organic",
    style: "minimal",
    bestFor: ["Zero-waste & refill stores", "Small curated catalogues", "Home & body swaps"],
    features: ["Short hero", "Promise strip", "Two-column feature grid", "Badge-free cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#26302b", secondary: "#5f6f66", accent: "#8fae96", background: "#ffffff", text: "#26302b", border: "#e7ece8", sale: "#b4533c" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "sm", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["Marquee", { size: "small", speed: "slow", tone: "light", separator: "none" }, "marquee"],
        ["ProductGrid", { limit: 6, columns: 3 }, "home-care"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["ProductGrid", { limit: 4, columns: 2 }, "pantry"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "sprout-pop",
    name: "Sprout Pop",
    tagline: "Loud, leafy and fun to shop",
    description: "A bold layout for young natural brands that live on Instagram: lime on beetroot, a large hero followed by a scrolling promise ticker, tall category cards, a pantry grid with quick add, square promo tiles, a photo mosaic and a best-seller carousel. Uppercase grotesk headings and pill buttons.",
    industry: "organic",
    style: "bold",
    bestFor: ["D2C natural brands", "Instagram-led shops", "Snack & pantry start-ups"],
    features: ["Promise ticker", "Tall category cards", "Square promo tiles", "Photo mosaic"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#5b1a3a", secondary: "#7d2c55", accent: "#b5d334", background: "#fff8ec", text: "#33101f", border: "#f0e2cf", sale: "#e0452b" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 5 }, "hero"],
        ["Marquee", { size: "large", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 4 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "pantry"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["SocialProof", { layout: "mosaic", showProfile: false }, "social"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "refills"]],
    },
  },
  {
    key: "mandi-co-op",
    name: "Mandi Co-op",
    tagline: "The whole organic mandi in one aisle",
    description: "A dense marketplace layout for large organic catalogues and co-ops: full-width container, mega menu, compact spacing, square department tiles, five-column grids for oils and staples, a coupon band, an under-₹299 add-on carousel and a scrolling strip of house ranges. Built for monthly restocks.",
    industry: "organic",
    style: "marketplace",
    bestFor: ["Organic co-ops & big catalogues", "Monthly pantry restocks", "Multi-category natural stores"],
    features: ["Mega menu", "Department tiles", "5-column grids", "Coupon band"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#155e63", secondary: "#2b7a78", accent: "#e9a03b", background: "#f4f7f6", text: "#12302f", border: "#dbe5e3", sale: "#d0342c" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: false, secondImageOnHover: false, offerBadge: "Free delivery ₹799+" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "pantry"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 5 }, "home-care"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductCarousel", { limit: 12 }, "refills"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "refills"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
