import type { MarketplaceTheme } from "../types";

/**
 * Pet Supplies. Content slots (scripts/dev/showcase/data/pawdesh.ts): marquee, hero, categories,
 * toys, promo, social, bestsellers, newsletter, story, collections, beds, feature, lookbook, new,
 * feature-2, cats, faq, dogs, aquarium, brands, trust, sale, deals, treats.
 */
const DEMO = "pawdesh";
const ADDED = "2026-10-01";

export const PETS_THEMES: MarketplaceTheme[] = [
  {
    key: "wag-street",
    name: "Wag Street",
    tagline: "Loud, happy and built for playtime",
    description: "A playful, high-contrast layout for pet shops with personality: a scrolling offer strip, tangerine on deep teal, round shop-by-need bubbles, a toy grid, square promo tiles and a photo mosaic of happy pets. Chunky grotesk capitals and pill buttons keep it bouncy.",
    industry: "pets",
    style: "bold",
    bestFor: ["Toy & accessory brands", "Young pet parents", "Instagram-led pet shops"],
    features: ["Offer marquee", "Round category bubbles", "Pet photo mosaic", "Quick add"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0b4f4a", secondary: "#127a70", accent: "#ff7a2f", background: "#fffaf3", text: "#12302d", border: "#f1e4d2", sale: "#e3462c" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Marquee", { size: "medium", speed: "normal", tone: "accent", separator: "star" }, "marquee"],
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "toys"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["SocialProof", { layout: "mosaic", showProfile: false }, "social"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["Newsletter", { tone: "accent" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "toys"]],
    },
  },
  {
    key: "velvet-paw",
    name: "Velvet Paw",
    tagline: "Quiet luxury for well-loved companions",
    description: "A premium, magazine-like layout for beds, leather and designer accessories: centred logo, full-screen hero, a brand story with numbers, three curated collection tiles, a three-column bed edit, a dark editorial feature and a row lookbook. Display serif headings and outline buttons.",
    industry: "pets",
    style: "premium",
    bestFor: ["Premium beds & furniture", "Leather collars & leads", "Gift-led pet boutiques"],
    features: ["Full-screen hero", "Brand story with stats", "Collection tiles", "Lookbook row"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2420", secondary: "#6b5444", accent: "#b08a5a", background: "#f8f4ee", text: "#2b2420", border: "#e5dccf", sale: "#9c3d2a" }, headingFont: "playfair", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 6, columns: 3 }, "beds"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
    },
  },
  {
    key: "clean-coat",
    name: "Clean Coat",
    tagline: "Calm, white and easy to shop",
    description: "A minimal layout that lets product photos do the work: a short hero, new arrivals first, an editorial note on grooming, a two-column cat edit with large images and an FAQ for first-time pet parents. Clean sans type, sharp cards, no badges and a light footer.",
    industry: "pets",
    style: "minimal",
    bestFor: ["Small curated pet stores", "Cat-first shops", "D2C single-category brands"],
    features: ["Short hero", "Two-column feature grid", "FAQ block", "Badge-free cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1f2a30", secondary: "#55666e", accent: "#7fa7a0", background: "#ffffff", text: "#1f2a30", border: "#e8ecee", sale: "#c2523d" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "none", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["ProductGrid", { limit: 4, columns: 2 }, "cats"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "pet-superstore",
    name: "Pet Superstore",
    tagline: "Every pet, every need, one big aisle",
    description: "A dense marketplace layout for large pet catalogues: full-width container, mega menu, compact spacing, square need-based department tiles, five-column grids for dogs and cats, an aquarium and birds carousel and a scrolling strip of house ranges. Built for repeat shoppers who know what they want.",
    industry: "pets",
    style: "marketplace",
    bestFor: ["Multi-pet superstores", "Dogs, cats, fish & birds", "Large catalogues"],
    features: ["Mega menu", "Department tiles", "5-column grids", "House-range strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#163a63", secondary: "#2d5d8f", accent: "#f2b705", background: "#f3f6fa", text: "#13263d", border: "#dde4ee", sale: "#d62839" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "dogs"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 5 }, "cats"],
        ["ProductCarousel", { limit: 12 }, "aquarium"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "treat-drop",
    name: "Treat Drop",
    tagline: "Offers, refills and a fast checkout",
    description: "Conversion-first for pet stores that run offers and repeat orders: centred logo with a drawer menu, a coupon sale band up top, deal grids with green discount pills, an under-₹499 carousel for add-ons, tall category cards and trust signals on every page.",
    industry: "pets",
    style: "conversion",
    bestFor: ["Sale events", "Repeat-order essentials", "Value pet brands"],
    features: ["Coupon sale band", "Discount pills", "Add-on carousel", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#4a1d6e", secondary: "#6e3a99", accent: "#2ec27e", background: "#ffffff", text: "#24132f", border: "#ece3f3", sale: "#e0245e" }, headingFont: "humanist-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free delivery ₹699+" },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "treats"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["FAQ", { limit: 4 }, "faq"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
