import type { MarketplaceTheme } from "../types";

/**
 * Smart Home & Appliances. Content slots (scripts/dev/showcase/data/griha-smart.ts):
 * hero, marquee, categories, collections, kitchen, lighting, climate, new, bestsellers,
 * deals, feature, feature-2, story, rooms, promo, sale, brands, trust, faq, newsletter.
 */
const DEMO = "griha-smart";
const ADDED = "2026-10-01";

export const SMART_HOME_THEMES: MarketplaceTheme[] = [
  {
    key: "modern-kitchen",
    name: "Modern Kitchen",
    tagline: "Bright, friendly and kitchen-first",
    description: "A clean, modern layout for appliance stores: inline navigation, a large hero, round department shortcuts, a kitchen-appliance carousel, a feature story on cooking smarter, square promo tiles and a four-column new-arrivals grid. Rounded cards and saffron accents on navy.",
    industry: "smart-home",
    style: "modern",
    bestFor: ["Kitchen appliances", "Small appliances", "D2C appliance brands"],
    features: ["Inline menu", "Round department shortcuts", "Kitchen carousel", "Square promo tiles"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#23395b", secondary: "#4f6d8f", accent: "#f4a259", background: "#ffffff", text: "#1c2a3f", border: "#e4e9f0", sale: "#d1495b" }, headingFont: "dm-sans", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "lg", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 6 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "kitchen"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["PromoBanner", { aspect: "square" }, "promo"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "kitchen"], ["TrustBadges", { layout: "grid", tone: "light" }, "trust"]],
    },
  },
  {
    key: "appliance-atelier",
    name: "Appliance Atelier",
    tagline: "Quiet luxury for beautifully made appliances",
    description: "A premium, story-led layout: centred logo with a drawer menu, a full-screen hero, a brand story with numbers, room scenes that link to products, two alternating feature stories and a three-column best-seller grid. Display serif headings, brass accents and square, unrounded cards.",
    industry: "smart-home",
    style: "premium",
    bestFor: ["Premium kitchen appliances", "Designer lighting", "Coffee & tea machines"],
    features: ["Drawer menu", "Full-screen hero", "Shop-the-room scenes", "Brand story with numbers"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#1c1b19", secondary: "#5a554c", accent: "#b08d57", background: "#f6f3ee", text: "#1c1b19", border: "#e5dfd4", sale: "#9b3d2e" }, headingFont: "playfair", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bestsellers"],
        ["EditorialImageText", { imagePosition: "left", tone: "dark" }, "feature"],
        ["Lookbook", { layout: "row" }, "rooms"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature-2"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["BrandStory", {}, "story"]],
    },
  },
  {
    key: "appliance-bazaar",
    name: "Appliance Bazaar",
    tagline: "Every department, one fast aisle",
    description: "A dense marketplace layout for large appliance catalogues: full-width container, mega menu, compact spacing, square department tiles, five-column deal and kitchen grids, a climate carousel, wide promo tiles and a scrolling strip of product ranges.",
    industry: "smart-home",
    style: "marketplace",
    bestFor: ["Multi-category appliance stores", "Large catalogues", "Kitchen to cleaning"],
    features: ["Mega menu", "Department tiles", "5-column grids", "Range strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#102a43", secondary: "#334e68", accent: "#ffb703", background: "#f1f4f8", text: "#102a43", border: "#d9e2ec", sale: "#d62828" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "deals"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 5 }, "kitchen"],
        ["ProductCarousel", { limit: 12 }, "climate"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "calm-home",
    name: "Calm Home",
    tagline: "Fewer, better things for a quieter home",
    description: "A minimal, gallery-like layout: narrow container, uppercase geometric headings, a medium hero with a light overlay, three-column grids without badges, three collection tiles and a single feature story. Outline buttons and a light footer let well-shot lamps and appliances carry the page.",
    industry: "smart-home",
    style: "minimal",
    bestFor: ["Lighting stores", "Design-led appliances", "Small catalogues"],
    features: ["Narrow container", "Three-column grids", "No badges", "Outline buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2b2b2b", secondary: "#7a8b7f", accent: "#7a8b7f", background: "#f8f7f4", text: "#2b2b2b", border: "#e6e3dc", sale: "#8c4a32" }, headingFont: "geometric-sans", bodyFont: "humanist-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 20, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 3, columns: 3 }, "lighting"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature-2"],
        ["ProductGrid", { limit: 6, columns: 3 }, "new"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "appliance-deals",
    name: "Appliance Deals",
    tagline: "Offers, free installation and fast checkout",
    description: "Conversion-focused for appliance sale events: a scrolling offer strip, centred logo with a drawer menu, a coupon sale band before the hero, deal grids with green discount pills, a new-arrivals carousel, quick add and a 'Free installation' badge on every card, and trust signals on every page.",
    industry: "smart-home",
    style: "conversion",
    bestFor: ["Sale events", "Festive offers", "High-volume appliance sellers"],
    features: ["Offer marquee", "Coupon sale band", "Discount pills", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0b1f3a", secondary: "#1d3557", accent: "#ff5a1f", background: "#ffffff", text: "#0b1f3a", border: "#e6e8ec", sale: "#e11d48" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free installation" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "dark", separator: "star" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "new"],
        ["FAQ", { limit: 4 }, "faq"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "star" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
