import type { MarketplaceTheme } from "../types";

/**
 * Sports & Fitness. Content slots (scripts/dev/showcase/data/khel-studio.ts): hero, marquee,
 * categories, trending, feature, feature-2, team, racquet, fitness, promo, newsletter, sale,
 * deals, bestsellers, new, trust, brands, collections, faq, story, lookbook.
 */
const DEMO = "khel-studio";
const ADDED = "2026-10-01";

export const SPORTS_THEMES: MarketplaceTheme[] = [
  {
    key: "arena-bold",
    name: "Arena Bold",
    tagline: "Loud, fast and made for match day",
    description: "High-energy and poster-like: full-screen hero, an uppercase grotesk type system, a scrolling slogan strip, tall portrait category tiles, a trending carousel and a big editorial training story. Square buttons and sharp cards keep it punchy.",
    industry: "sports",
    style: "bold",
    bestFor: ["Cricket & team sports", "D2C sports brands", "Launch campaigns"],
    features: ["Full-screen hero", "Slogan marquee", "Portrait category tiles", "Training story"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0b0b0c", secondary: "#26282c", accent: "#d4ff3a", background: "#ffffff", text: "#0b0b0c", border: "#e4e4e7", sale: "#e5361b" }, headingFont: "grotesk", bodyFont: "modern-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "wide", spacing: "comfortable", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 40, autoplay: 6 }, "hero"],
        ["Marquee", { size: "large", speed: "fast", tone: "dark", separator: "star" }, "marquee"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["ProductCarousel", { limit: 10 }, "trending"],
        ["EditorialImageText", { imagePosition: "right", tone: "dark" }, "feature"],
        ["ProductGrid", { limit: 8, columns: 4 }, "team"],
        ["PromoBanner", { aspect: "portrait" }, "promo"],
        ["Newsletter", { tone: "dark" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "trending"]],
    },
  },
  {
    key: "match-day-deals",
    name: "Match Day Deals",
    tagline: "Offers up front, checkout in a tap",
    description: "Conversion-first for sale seasons: drawer menu with a centred logo, an offer strip and coupon band above the fold, deal grids with green discount pills and a store-wide offer badge, quick add on every card and a scrolling trust strip on every page.",
    industry: "sports",
    style: "conversion",
    bestFor: ["Sale events", "Value fitness gear", "High-volume sellers"],
    features: ["Coupon sale band", "Discount pills", "Offer badge on cards", "Trust strip everywhere"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0a2a66", secondary: "#123a85", accent: "#ff6a13", background: "#ffffff", text: "#0d1b2a", border: "#e2e8f0", sale: "#e11d48" }, headingFont: "geometric-sans", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Combo offers" },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "normal", tone: "accent", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["CategoryGrid", { mode: "manual", shape: "square", limit: 6 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 4 }, "fitness"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "accent", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "deals"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
  {
    key: "sports-megastore",
    name: "Sports Megastore",
    tagline: "Every sport, one dense storefront",
    description: "A multi-sport marketplace layout: full-width container, mega menu, compact spacing, a 2:1 banner hero, round sport shortcuts, five-column grids by sport, a promo tile pair and a scrolling strip of product lines. Built for big catalogues and quick comparison.",
    industry: "sports",
    style: "marketplace",
    bestFor: ["Multi-sport retailers", "Large catalogues", "Academies & clubs"],
    features: ["Mega menu", "Round sport shortcuts", "5-column grids", "Product-line strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#0f3d2e", secondary: "#1d5c45", accent: "#f5b700", background: "#f3f5f4", text: "#10221b", border: "#dde5e1", sale: "#d92d20" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 10, columns: 5 }, "racquet"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 10, columns: 5 }, "fitness"],
        ["ProductCarousel", { limit: 12 }, "new"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "grid", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "studio-fit",
    name: "Studio Fit",
    tagline: "Calm, modern home-workout styling",
    description: "Soft and lifestyle-led for fitness and yoga: centred logo, large centred hero, three collection tiles by goal, three-column grids, a yoga-and-recovery feature story and FAQs that answer sizing and care questions. Pill buttons, rounded cards and airy spacing.",
    industry: "sports",
    style: "modern",
    bestFor: ["Home fitness", "Yoga & recovery", "Activewear"],
    features: ["Goal-based collection tiles", "Feature story", "FAQ block", "Pill buttons"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2d3a4a", secondary: "#5f7d8c", accent: "#e8846b", background: "#f6f4f0", text: "#232b33", border: "#e5e0d8", sale: "#c2410c" }, headingFont: "dm-sans", bodyFont: "dm-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "solid", cardRadius: "lg", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "rotate",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: true, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 30, autoplay: 0 }, "hero"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["ProductGrid", { limit: 6, columns: 3 }, "fitness"],
        ["EditorialImageText", { imagePosition: "left", tone: "light" }, "feature-2"],
        ["ProductCarousel", { limit: 8 }, "new"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
    },
  },
  {
    key: "pro-shop",
    name: "Pro Shop",
    tagline: "Craft-first gear for serious players",
    description: "A premium club-shop feel: classic capital headings, inline navigation, a workshop story with numbers, three-column best sellers, a lookbook row of gear in use, an editorial feature and a racquet-sports carousel. Outline buttons, no quick add, calm and considered.",
    industry: "sports",
    style: "premium",
    bestFor: ["Cricket & racquet specialists", "Hand-made equipment", "Premium gear"],
    features: ["Workshop story with numbers", "Lookbook row", "Outline buttons", "Inline menu"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14261d", secondary: "#5b4a32", accent: "#b08d57", background: "#fbfaf6", text: "#1a1f1b", border: "#e6e1d5", sale: "#9b2c2c" }, headingFont: "marcellus", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "light",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "large", overlay: 35, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 6, columns: 3 }, "bestsellers"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature"],
        ["ProductCarousel", { limit: 8 }, "racquet"],
        ["TrustBadges", { layout: "grid", tone: "light" }, "trust"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "bestsellers"]],
    },
  },
];
