import type { MarketplaceTheme } from "../types";

/**
 * Watches & Luxury Accessories. Content slots (scripts/dev/showcase/data/ghadi-co.ts): hero, story,
 * automatics, feature, collections, lookbook, newsletter, new, feature-2, sport, faq, marquee,
 * bestsellers, social, categories, accessories, promo, pocket, brands, trust, sale, deals, gifts.
 */
const DEMO = "ghadi-co";
const ADDED = "2026-10-01";

export const WATCHES_THEMES: MarketplaceTheme[] = [
  {
    key: "chrono-noir",
    name: "Chrono Noir",
    tagline: "After-dark luxury for fine watches",
    description: "A dark, boutique-style layout for automatic and dress watches: centred logo, full-screen hero, a heritage story with numbers, a three-column automatic edit on near-black, an editorial feature, curated collection tiles and a lookbook row. High-contrast Bodoni capitals, gold accents and outline buttons.",
    industry: "watches",
    style: "luxury",
    bestFor: ["Automatic & mechanical watches", "Premium watch boutiques", "Limited editions"],
    features: ["Full-screen hero", "Dark boutique palette", "Heritage story with stats", "Lookbook row"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#c9a45c", secondary: "#8a7350", accent: "#c9a45c", background: "#111112", text: "#ece6da", border: "#2c2a27", sale: "#d0644a" }, headingFont: "didone", bodyFont: "geometric-sans", headingCase: "uppercase", buttonShape: "square", buttonVariant: "outline", cardRadius: "none", containerWidth: "default", spacing: "airy", sectionHeadingAlign: "center" },
      header: { sticky: false, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "static",
      productCard: { imageRatio: "portrait", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Hero", { height: "full", overlay: 30, autoplay: 0 }, "hero"],
        ["BrandStory", {}, "story"],
        ["ProductGrid", { limit: 6, columns: 3 }, "automatics"],
        ["EditorialImageText", { imagePosition: "right", tone: "muted" }, "feature"],
        ["CollectionGrid", { mode: "manual", columns: 3, limit: 3 }, "collections"],
        ["Lookbook", { layout: "row" }, "lookbook"],
        ["Newsletter", { tone: "muted" }, "newsletter"],
      ],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "bestsellers"]],
    },
  },
  {
    key: "clean-dial",
    name: "Clean Dial",
    tagline: "White space, sharp type, nothing extra",
    description: "A quiet, minimal layout for small watch labels: inline menu, a short left-aligned hero, new arrivals first in a four-column grid, an editorial note on movements, a large two-column weekend and sport edit and an FAQ on water resistance and sizing. Inter type, sharp badge-free cards and a light footer.",
    industry: "watches",
    style: "minimal",
    bestFor: ["Independent watch labels", "Single-collection D2C brands", "Minimalist dress watches"],
    features: ["Short hero", "Two-column feature grid", "Movement FAQ", "Badge-free cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#16181b", secondary: "#5b6168", accent: "#3d6e8f", background: "#ffffff", text: "#16181b", border: "#e7e9ec", sale: "#b8432f" }, headingFont: "modern-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "square", buttonVariant: "solid", cardRadius: "none", containerWidth: "narrow", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: false },
      headerLayout: "logo-left",
      inlineMenu: true,
      menuStyle: "bar",
      announcementTone: "muted",
      announcementMode: "static",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "minimal", showBadges: false, showQuickAdd: false, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false },
      footerTone: "light",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 25, autoplay: 0 }, "hero"],
        ["ProductGrid", { limit: 8, columns: 4 }, "new"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["ProductGrid", { limit: 4, columns: 2 }, "sport"],
        ["FAQ", { limit: 6 }, "faq"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "wrist-journal",
    name: "Wrist Journal",
    tagline: "Tell the story behind every watch",
    description: "A magazine-style layout for brands with something to say: centred logo with a drawer menu, a slow ticker of house values, a large hero, a masonry lookbook, two alternating editorial stories around a best-seller carousel and a photo grid. Cormorant headings, tall cards and a muted footer.",
    industry: "watches",
    style: "editorial",
    bestFor: ["Story-led watch brands", "Vintage-inspired designs", "Content and gifting campaigns"],
    features: ["Masonry lookbook", "Alternating editorials", "Value ticker", "Drawer menu"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#2e3b33", secondary: "#5d6b5f", accent: "#a5714a", background: "#f6f2ea", text: "#26302a", border: "#e2dccf", sale: "#a34a2c" }, headingFont: "editorial-serif", bodyFont: "humanist-sans", headingCase: "normal", buttonShape: "pill", buttonVariant: "outline", cardRadius: "sm", containerWidth: "wide", spacing: "airy", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-center",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "muted",
      announcementMode: "rotate",
      productCard: { imageRatio: "tall", textAlign: "left", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showSizes: false, showBrand: true, secondImageOnHover: true },
      footerTone: "muted",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "slow", tone: "light", separator: "none" }, "marquee"],
        ["Hero", { height: "large", overlay: 25, autoplay: 7 }, "hero"],
        ["Lookbook", { layout: "masonry" }, "lookbook"],
        ["EditorialImageText", { imagePosition: "right", tone: "light" }, "feature"],
        ["ProductCarousel", { limit: 10 }, "bestsellers"],
        ["EditorialImageText", { imagePosition: "left", tone: "muted" }, "feature-2"],
        ["SocialProof", { layout: "grid", showProfile: false }, "social"],
        ["Newsletter", { tone: "light" }, "newsletter"],
      ],
    },
  },
  {
    key: "time-bazaar",
    name: "Time Bazaar",
    tagline: "Every watch and accessory in one big aisle",
    description: "A dense marketplace layout for large watch and accessory catalogues: full-width container, mega menu, compact spacing, round category bubbles, five-column grids for automatics and accessories, a wide promo, a pocket-watch carousel and a scrolling strip of house ranges. Brand names and sizes on every card.",
    industry: "watches",
    style: "marketplace",
    bestFor: ["Multi-category watch stores", "Watches plus accessories", "Large catalogues"],
    features: ["Mega menu", "Round category bubbles", "5-column grids", "House-range strip"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#14324f", secondary: "#2a5379", accent: "#e0a526", background: "#f4f6f8", text: "#122233", border: "#dce2e8", sale: "#c8283c" }, headingFont: "humanist-sans", bodyFont: "modern-sans", headingCase: "normal", buttonShape: "rounded", buttonVariant: "solid", cardRadius: "sm", containerWidth: "full", spacing: "compact", sectionHeadingAlign: "left" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "bar",
      announcementTone: "dark",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: true, showBrand: true, secondImageOnHover: false },
      footerTone: "dark",
      hero: { align: "left", textTone: "light" },
      home: [
        ["Hero", { height: "medium", overlay: 30, autoplay: 5 }, "hero"],
        ["CategoryGrid", { mode: "manual", shape: "circle", limit: 8 }, "categories"],
        ["ProductGrid", { limit: 8, columns: 5 }, "automatics"],
        ["PromoBanner", { aspect: "wide" }, "promo"],
        ["ProductGrid", { limit: 8, columns: 5 }, "accessories"],
        ["ProductCarousel", { limit: 12 }, "pocket"],
        ["BrandStrip", { layout: "marquee", tone: "light" }, "brands"],
        ["TrustBadges", { layout: "grid", tone: "muted" }, "trust"],
      ],
      collection: [["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"], ["PageContent", {}]],
    },
  },
  {
    key: "tick-tock-deals",
    name: "Tick Tock Deals",
    tagline: "Festive offers and gifting, fast",
    description: "Conversion-first for watch stores that run sales and gifting seasons: a fast offer ticker, a coupon sale band up top, deal grids with discount pills, a medium hero, an under-₹2,999 gift carousel, tall category cards and trust signals on every page. Bold grotesk capitals and pill buttons.",
    industry: "watches",
    style: "conversion",
    bestFor: ["Festive and wedding-season sales", "Gifting stores", "Value watch brands"],
    features: ["Coupon sale band", "Discount pills", "Gift carousel", "Offer badge on cards"],
    demo: DEMO,
    version: "1.0.0",
    added: ADDED,
    preset: {
      tokens: { colors: { primary: "#7a1022", secondary: "#a3283c", accent: "#f2b134", background: "#fffdf9", text: "#2a1216", border: "#f0e2dc", sale: "#d61f3c" }, headingFont: "grotesk", bodyFont: "dm-sans", headingCase: "uppercase", buttonShape: "pill", buttonVariant: "solid", cardRadius: "md", containerWidth: "wide", spacing: "compact", sectionHeadingAlign: "center" },
      header: { sticky: true, showStoreName: true, showWishlist: true },
      headerLayout: "logo-left",
      inlineMenu: false,
      menuStyle: "drawer",
      announcementTone: "accent",
      announcementMode: "rotate",
      productCard: { imageRatio: "square", textAlign: "center", badgeStyle: "pill", showQuickAdd: true, showRating: false, showSizes: false, showBrand: false, secondImageOnHover: false, offerBadge: "Free gift box" },
      footerTone: "dark",
      hero: { align: "center", textTone: "light" },
      home: [
        ["Marquee", { size: "small", speed: "fast", tone: "dark", separator: "dot" }, "marquee"],
        ["SaleBanner", {}, "sale"],
        ["ProductGrid", { limit: 8, columns: 4 }, "deals"],
        ["Hero", { height: "medium", overlay: 35, autoplay: 5 }, "hero"],
        ["ProductCarousel", { limit: 10 }, "gifts"],
        ["CategoryGrid", { mode: "manual", shape: "portrait", limit: 6 }, "categories"],
        ["FAQ", { limit: 4 }, "faq"],
        ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"],
      ],
      collection: [["Marquee", { size: "small", tone: "dark", separator: "dot" }, "marquee"], ["PageContent", {}], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
      product: [["PageContent", {}], ["ProductCarousel", { limit: 8 }, "gifts"], ["TrustBadges", { layout: "marquee", tone: "muted" }, "trust"]],
    },
  },
];
