import { z } from "zod";

/**
 * Safe building blocks for theme settings. Every value that reaches CSS, an href, an <img>
 * or an <iframe> goes through one of these, so theme JSON can never inject markup, script,
 * CSS or arbitrary embeds. Pure module: shared by the editor (client) and renderer (server).
 */

/** #rrggbb only. Anything else could break out of a CSS declaration. */
export const HEX_COLOR_RE = /^#[0-9a-fA-F]{6}$/;
export const hexColor = z.string().trim().regex(HEX_COLOR_RE, "Use a colour like #1c1917").transform((v) => v.toLowerCase());

/** Plain text (rendered as a React text node, never as HTML). Control characters stripped. */
export function plainText(max: number) {
  return z
    .string()
    .max(max * 2)
    .transform((v) => v.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, "").trim())
    .pipe(z.string().max(max, `At most ${max} characters`));
}

/** Same-origin path ("/collections/sale") or https URL. Rejects //host, backslashes, javascript:, data:, etc. */
export function isSafeHref(href: string): boolean {
  if (href.length === 0 || href.length > 500) return false;
  if (/[\s\\\u0000-\u001f\u007f]/.test(href)) return false;
  if (href.startsWith("/")) return !href.startsWith("//");
  if (href.startsWith("#")) return /^#[A-Za-z0-9_-]{1,64}$/.test(href);
  try {
    const u = new URL(href);
    return u.protocol === "https:" && !!u.hostname && !u.username && !u.password;
  } catch {
    return false;
  }
}

/** Optional link: empty string allowed (= no link). */
export const safeHref = z
  .string()
  .trim()
  .max(500)
  .refine((v) => v === "" || isSafeHref(v), "Use a link starting with / or https://");

/** Public store-assets path for THIS tenant is enforced at save time (see assertAssetsOwned). */
export const STORAGE_PATH_RE = /^tenant\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/[a-z]+\/[A-Za-z0-9._-]{1,120}$/;
export const imagePath = z
  .string()
  .trim()
  .refine((v) => v === "" || STORAGE_PATH_RE.test(v), "Upload an image");

/** Section instance ids: short, url-safe, generated by the editor. */
export const SECTION_ID_RE = /^[a-z0-9][a-z0-9-]{2,39}$/;

export const uuidOrEmpty = z
  .string()
  .trim()
  .refine((v) => v === "" || /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v), "Pick an item");

export const menuHandle = z
  .string()
  .trim()
  .refine((v) => v === "" || /^[a-z0-9-]{2,40}$/.test(v), "Pick a menu");

// -----------------------------------------------------------------------------
// Video: allowlisted providers only. The stored value is the seller's URL; the
// renderer embeds ONLY the canonical player URL rebuilt from the parsed id.
// -----------------------------------------------------------------------------
export type ParsedVideo =
  | { provider: "youtube"; id: string; embedUrl: string }
  | { provider: "vimeo"; id: string; embedUrl: string }
  | { provider: "file"; path: string };

export function parseVideoUrl(input: string): ParsedVideo | null {
  const value = input.trim();
  if (!value) return null;
  if (STORAGE_PATH_RE.test(value) && value.endsWith(".mp4")) return { provider: "file", path: value };
  let u: URL;
  try {
    u = new URL(value);
  } catch {
    return null;
  }
  if (u.protocol !== "https:" || u.username || u.password) return null;
  const host = u.hostname.replace(/^www\./, "").replace(/^m\./, "");
  const YT_ID = /^[A-Za-z0-9_-]{11}$/;
  if (host === "youtube.com" || host === "youtube-nocookie.com") {
    let id: string | null = null;
    if (u.pathname === "/watch") id = u.searchParams.get("v");
    else {
      const m = /^\/(?:embed|shorts|live)\/([^/]+)$/.exec(u.pathname);
      id = m?.[1] ?? null;
    }
    return id && YT_ID.test(id) ? { provider: "youtube", id, embedUrl: `https://www.youtube-nocookie.com/embed/${id}` } : null;
  }
  if (host === "youtu.be") {
    const id = u.pathname.slice(1);
    return YT_ID.test(id) ? { provider: "youtube", id, embedUrl: `https://www.youtube-nocookie.com/embed/${id}` } : null;
  }
  if (host === "vimeo.com" || host === "player.vimeo.com") {
    const m = /^\/(?:video\/)?(\d{6,12})$/.exec(u.pathname);
    return m ? { provider: "vimeo", id: m[1]!, embedUrl: `https://player.vimeo.com/video/${m[1]}` } : null;
  }
  return null;
}

export const videoUrl = z
  .string()
  .trim()
  .max(500)
  .refine((v) => v === "" || parseVideoUrl(v) !== null, "Use a YouTube or Vimeo link, or upload an MP4");

/** Instagram / social profile links: https on a small set of hosts. */
const SOCIAL_HOSTS = ["instagram.com", "facebook.com", "youtube.com", "pinterest.com", "x.com", "twitter.com", "linkedin.com", "threads.net"];
export function isSocialUrl(v: string): boolean {
  try {
    const u = new URL(v);
    const host = u.hostname.replace(/^www\./, "");
    return u.protocol === "https:" && SOCIAL_HOSTS.some((h) => host === h || host.endsWith(`.${h}`));
  } catch {
    return false;
  }
}
export const socialUrl = z
  .string()
  .trim()
  .max(300)
  .refine((v) => v === "" || isSocialUrl(v), "Use an https link to Instagram, Facebook, YouTube, Pinterest or X");
