import type { StoreSpec } from "./types";

/* Placeholders resolved by the generator:
 *   "$collection:<slug>" → collection id      "$category:<slug>" → category id
 *   "$img:<key>"         → generated banner/editorial image path (hero, heroMobile, editorial, story, promo1-3)
 *   "$product:<i>"       → front image of product i;  "$productId:<i>" → product id
 */

// ----------------------------------------------------------------------------- 01 · Kashmir heritage
const chinar: StoreSpec = {
  slug: "chinar",
  name: "Chinar & Loom",
  tagline: "Heirloom shawls and pherans from the looms of Srinagar",
  story:
    "Chinar & Loom works with eleven weaving and embroidery families in downtown Srinagar. Every shawl is spun, woven and finished by hand over weeks, sometimes months, and signed by the artisan who made it.",
  email: "care@chinarandloom.test",
  phone: "+919419012345",
  address: { line1: "Zaina Kadal, Old City", city: "Srinagar", state: "Jammu and Kashmir", postal_code: "190002" },
  social: { instagram: "https://instagram.com/chinarandloom", facebook: "https://facebook.com/chinarandloom", pinterest: "https://pinterest.com/chinarandloom" },
  seo: { title: "Chinar & Loom — Handwoven Kashmiri shawls, stoles and pherans", description: "Handwoven Kashmiri pashmina-blend shawls, sozni embroidered stoles and wool pherans, made by artisan families in Srinagar." },
  legalName: "Chinar Loom Crafts LLP",
  gstin: "01AAHFC1234M1Z5",
  backdrop: ["#efe9e0", "#d3c7b6"],
  bannerBackdrop: ["#d8c9b3", "#2a1d16"],
  hero: { eyebrow: "Autumn in the valley", heading: "Woven slowly, worn for generations", subheading: "Sozni, kani and tilla work from artisan families in Srinagar.", ctaLabel: "Explore the collection", ctaHref: "/collections/heirloom-edit", textTone: "light", align: "left" },
  announcement: ["Complimentary gift wrap on every shawl", "Each piece comes with an artisan certificate"],
  tokens: {
    colors: { primary: "#2b1d16", secondary: "#6b3a22", accent: "#b8732f", background: "#f7f2ea", text: "#2b1d16", border: "#e4d8c8", sale: "#8f2d1f" },
    headingFont: "editorial-serif",
    bodyFont: "humanist-sans",
    headingCase: "normal",
    buttonShape: "square",
    buttonVariant: "solid",
    cardRadius: "none",
    containerWidth: "wide",
    spacing: "airy",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-center",
  productCard: { imageRatio: "tall", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, secondImageOnHover: true },
  footerTone: "dark",
  home: [
    ["Hero", { height: "full", overlay: 30 }],
    ["BrandStory", { eyebrow: "The makers", heading: "Eleven families, one river city", body: "Our shawls begin as raw wool on the banks of the Jhelum. They are spun on the charkha, woven on wooden looms and embroidered by hand in sozni needlework that can take a single artisan three months. We pay above guild rates and credit every maker by name.", imagePath: "$img:story", alt: "Hand embroidery in progress", stats: [{ value: "11", label: "Artisan families" }, { value: "90+", label: "Days per sozni shawl" }, { value: "100%", label: "Handwoven" }] }],
    ["CategoryGrid", { eyebrow: "Shop by craft", heading: "From the looms", mode: "auto", limit: 4, shape: "portrait" }],
    ["ProductGrid", { eyebrow: "The heirloom edit", heading: "Pieces to pass down", source: "collection", collectionId: "$collection:heirloom-edit", limit: 6, columns: 3, viewAllHref: "/collections/heirloom-edit" }],
    ["EditorialImageText", { eyebrow: "The craft", heading: "What sozni means", body: "Sozni is needlework so fine it reads as painting. Artisans trace chinar leaves, paisleys and vines in silk thread, a few millimetres at a time, so the pattern appears on both faces of the shawl.", imagePath: "$img:editorial", alt: "Close-up of a paisley shawl", imagePosition: "right", tone: "muted", ctaLabel: "Read our story", ctaHref: "/pages/about" }],
    ["Testimonials", { heading: "Letters from our patrons" }],
    ["Newsletter", { heading: "Notes from the valley", subheading: "Stories from our workshops and first access to each season's shawls.", buttonLabel: "Join", tone: "muted" }],
  ],
  categories: [
    { slug: "shawls", name: "Shawls", description: "Full-length shawls in pashmina blends and fine wool." },
    { slug: "stoles", name: "Stoles", description: "Lighter stoles for year-round layering." },
    { slug: "pherans", name: "Pherans", description: "The traditional Kashmiri overgarment, cut for today." },
    { slug: "kurtas", name: "Kurtas", description: "Wool and cotton kurtas with Kashmiri embroidery." },
  ],
  collections: [
    { slug: "heirloom-edit", title: "The Heirloom Edit", description: "Our most intricate pieces, made to be passed down." },
    { slug: "winter-layers", title: "Winter Layers", description: "Warm wool for the coldest months.", rules: { tag: "winter" } },
    { slug: "gifting", title: "Gifting", description: "Boxed and ready to give.", rules: { tag: "gift" } },
  ],
  menu: [
    { title: "Shawls", to: "/categories/shawls", children: [{ title: "Sozni embroidered", to: "/search?q=sozni" }, { title: "Kani weave", to: "/search?q=kani" }, { title: "Jamawar", to: "/search?q=jamawar" }] },
    { title: "Stoles", to: "/categories/stoles" },
    { title: "Pherans", to: "/categories/pherans" },
    { title: "Kurtas", to: "/categories/kurtas" },
    { title: "Heirloom Edit", to: "/collections/heirloom-edit" },
    { title: "Gifting", to: "/collections/gifting" },
  ],
  faqs: [
    ["Are your shawls pure pashmina?", "Our shawls are labelled precisely: pashmina-blend pieces combine hand-spun pashmina with fine merino for durability. Each listing states the fibre content."],
    ["How long does an embroidered shawl take to make?", "A full sozni shawl takes between two and four months. Stock is limited because each piece is made by hand."],
    ["How should I store my shawl?", "Fold loosely in the muslin bag provided with a few neem leaves or cedar blocks, away from direct sunlight. Dry clean only."],
    ["Do you ship internationally?", "We currently ship within India. International shipping is on our list for next season."],
  ],
  testimonials: [
    { quote: "The sozni work is even finer in person. My mother cried when I gave it to her.", name: "Rukhsana A.", place: "Hyderabad" },
    { quote: "Beautifully packed, with a handwritten note from the artisan. Worth every rupee.", name: "Devika P.", place: "Pune" },
    { quote: "I wear my pheran every winter morning. Warm, soft and so well cut.", name: "Arjun M.", place: "Delhi" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "An heirloom already", body: "The embroidery is dense and even on both sides. Came with an artisan card.", author: "Nazia" },
    { product: 0, rating: 5, title: "Worth the wait", body: "Soft, warm and the colour is exactly as shown.", author: "Meenal" },
    { product: 3, rating: 4, title: "Cosy pheran", body: "Lovely wool, runs a little roomy which I like.", author: "Irfan" },
    { product: 1, rating: 5, title: "Perfect gift", body: "Bought for my sister's wedding. Everyone asked where it was from.", author: "Sana" },
  ],
  products: [
    { title: "Chinar Leaf Sozni Shawl", type: "accessory", category: "shawls", price: 38500, mrp: 42000, sizes: "free", fabric: "Pashmina blend", work: "Sozni embroidery", occasion: ["Festive", "Wedding"], tags: ["sozni", "heirloom", "gift", "winter"], featured: true, short: "Chinar leaves in silk sozni on ivory pashmina blend.", description: "An ivory pashmina-blend shawl embroidered edge to edge with chinar leaves in muted rust and moss silk. Sozni needlework, finished by hand over roughly ninety days.", art: { silhouette: "shawl", print: "paisley", colors: { ground: "#efe4d0", ink: "#7a3b22", accent: "#4f6b4a", leaf: "#8a6a3a", altGround: "#7a3b22", altPrint: "solid" } }, collections: ["heirloom-edit"] },
    { title: "Kani Weave Jamawar Stole", type: "accessory", category: "stoles", price: 14800, sizes: "free", fabric: "Fine wool", work: "Kani weave", occasion: ["Festive"], tags: ["kani", "gift"], featured: true, short: "Kani-woven jamawar stole in madder and indigo.", description: "Woven on a traditional kani loom with small wooden bobbins called tojlis, this stole carries a dense jamawar pattern in madder red and indigo across its full width.", art: { silhouette: "shawl", print: "ajrakh", colors: { ground: "#7a1f22", ink: "#1f2a44", accent: "#d9a44a", leaf: "#2f4a3a", altGround: "#1f2a44", altPrint: "solid" } }, collections: ["heirloom-edit"] },
    { title: "Saffron Fields Tilla Shawl", type: "accessory", category: "shawls", price: 26500, mrp: 29000, sizes: "free", fabric: "Wool", work: "Tilla embroidery", occasion: ["Wedding", "Festive"], tags: ["tilla", "gift", "winter"], short: "Gold tilla border on deep saffron wool.", description: "A warm saffron wool shawl with a hand-couched tilla border in antique gold thread, inspired by crocus fields in Pampore at harvest.", art: { silhouette: "shawl", print: "zari", colors: { ground: "#b35a1f", ink: "#e2c06a", accent: "#e8c877", leaf: "#e2c06a", altGround: "#5a2a14", altPrint: "zari" } }, collections: ["heirloom-edit", "winter-layers"] },
    { title: "Walnut Wool Pheran", type: "kurta", category: "pherans", price: 7800, sizes: "standard", fabric: "Wool tweed", work: "Aari embroidery", occasion: ["Casual", "Winter"], tags: ["winter", "pheran"], featured: true, short: "A roomy walnut pheran with aari-worked neckline.", description: "Cut in soft walnut wool tweed with a traditional wide sleeve and side pockets. The neckline carries fine aari embroidery in tonal thread.", art: { silhouette: "kurtaAline", print: "solid", colors: { ground: "#6b4a34", ink: "#3a261a", accent: "#caa46a", leaf: "#caa46a" } }, collections: ["winter-layers"] },
    { title: "Snowline Ivory Pheran", type: "kurta", category: "pherans", price: 8200, sizes: "standard", fabric: "Merino wool", work: "Sozni embroidery", occasion: ["Casual", "Winter"], tags: ["winter", "pheran", "gift"], short: "Ivory merino pheran with a sozni yoke.", description: "An ivory merino pheran with a hand-embroidered sozni yoke of vines and small birds. Relaxed through the body, cuffed at the sleeve.", art: { silhouette: "kurtaAline", print: "vine", colors: { ground: "#efe7da", ink: "#7a6a5a", accent: "#b8732f", leaf: "#7a6a5a" } }, collections: ["winter-layers", "gifting"] },
    { title: "Dal Lake Blue Stole", type: "accessory", category: "stoles", price: 6400, sizes: "free", fabric: "Wool silk", work: "Hand woven", occasion: ["Everyday"], tags: ["gift"], short: "Soft wool-silk stole in lake blue.", description: "Lightweight wool and silk, hand woven in a fine herringbone and dyed the grey-blue of Dal Lake at dawn.", art: { silhouette: "shawl", print: "chevron", colors: { ground: "#8fa6b8", ink: "#5f7a90", accent: "#dfe7ee", leaf: "#5f7a90", altGround: "#5f7a90", altPrint: "solid" } }, collections: ["gifting"] },
    { title: "Paisley Aari Kurta", type: "kurta", category: "kurtas", price: 5600, mrp: 6400, sizes: "apparel", fabric: "Cotton silk", work: "Aari embroidery", occasion: ["Festive"], tags: ["aari"], short: "Cotton-silk kurta with an aari paisley panel.", description: "A straight kurta in cotton silk with an aari-embroidered paisley panel down the front placket.", art: { silhouette: "kurtaStraight", print: "paisley", colors: { ground: "#243447", ink: "#d7b56d", accent: "#b8732f", leaf: "#d7b56d" } } },
    { title: "Almond Blossom Sozni Stole", type: "accessory", category: "stoles", price: 11200, sizes: "free", fabric: "Pashmina blend", work: "Sozni embroidery", occasion: ["Festive", "Everyday"], tags: ["sozni", "gift"], short: "Pale pink almond blossoms in sozni work.", description: "Spring in Srinagar: almond blossom sprigs embroidered in pale pink and sage on a dove-grey pashmina-blend stole.", art: { silhouette: "shawl", print: "sanganeri", colors: { ground: "#cfc8c2", ink: "#d99aa5", accent: "#8aa07a", leaf: "#8aa07a", altGround: "#9a8f86", altPrint: "solid" } }, collections: ["gifting"] },
  ],
  shippingNote: "Free insured shipping across India. Shawls ship in a muslin bag inside a keepsake box within 3 working days.",
  returnsNote: "Unworn pieces with their artisan tag can be returned within 10 days. Made-to-order pieces are final sale.",
};

// ----------------------------------------------------------------------------- 02 · Colourful Jaipur block print
const gulaab: StoreSpec = {
  slug: "gulaabrang",
  name: "Gulaab Rang",
  tagline: "Happy prints from Jaipur's block-printing lanes",
  story: "Gulaab Rang started with a single table in Sanganer and a love of loud colour. Today we print small batches with local printers and turn them into easy kurtas, sets and dresses for everyday joy.",
  email: "hello@gulaabrang.test",
  phone: "+919829045678",
  address: { line1: "12 Printers Colony, Sanganer", city: "Jaipur", state: "Rajasthan", postal_code: "302029" },
  social: { instagram: "https://instagram.com/gulaabrang", facebook: "https://facebook.com/gulaabrang", youtube: "https://youtube.com/@gulaabrang" },
  seo: { title: "Gulaab Rang — Colourful block print kurtas, sets & dresses from Jaipur", description: "Shop hand block printed kurtas, kurta sets, co-ords and dresses in bright, happy colours. Made in small batches in Jaipur." },
  legalName: "Gulaab Rang Fashions Pvt Ltd",
  gstin: "08AAICG5678K1Z2",
  backdrop: ["#fff1e6", "#ffd6c0"],
  bannerBackdrop: ["#ffd1dc", "#c2185b"],
  hero: { eyebrow: "New drop · Holi edit", heading: "Wear your happy colours", subheading: "Fresh hand block prints in rani pink, marigold and mint.", ctaLabel: "Shop new arrivals", ctaHref: "/collections/new-in", textTone: "light", align: "left" },
  announcement: ["Buy 2, get 10% off — code DUO10", "Free shipping above ₹999", "COD available"],
  tokens: {
    colors: { primary: "#c2185b", secondary: "#ff9f1c", accent: "#ff9f1c", background: "#fff9f4", text: "#2d1b24", border: "#f3d9d2", sale: "#d62839" },
    headingFont: "playfair",
    bodyFont: "dm-sans",
    headingCase: "normal",
    buttonShape: "pill",
    buttonVariant: "solid",
    cardRadius: "md",
    containerWidth: "wide",
    spacing: "comfortable",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-center",
  productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: true, showDiscountPercent: true, secondImageOnHover: true },
  footerTone: "dark",
  home: [
    ["Hero", { height: "large", overlay: 15 }],
    ["CategoryGrid", { eyebrow: "Shop by style", heading: "Pick your print", mode: "auto", limit: 6, shape: "circle" }],
    ["NewArrivals", { eyebrow: "Just landed", heading: "Fresh off the tables", limit: 8, layout: "carousel", viewAllHref: "/collections/new-in" }],
    ["PromoBanner", { tiles: [{ imagePath: "$img:promo1", alt: "Pink block print kurta set", heading: "Kurta sets under ₹2,499", text: "Three pieces, zero effort.", ctaLabel: "Shop sets", ctaHref: "/categories/kurta-sets" }, { imagePath: "$img:promo2", alt: "Marigold co-ord set", heading: "Co-ords for weekends", text: "Relaxed shirts and pants.", ctaLabel: "Shop co-ords", ctaHref: "/categories/co-ords" }], aspect: "square" }],
    ["Bestseller", { eyebrow: "Most loved", heading: "Bestsellers", limit: 8, layout: "grid" }],
    ["SaleBanner", { eyebrow: "This week only", heading: "Buy 2, get 10% off", subheading: "Mix and match anything in store.", code: "DUO10", endsText: "Ends Sunday midnight", ctaLabel: "Start shopping", ctaHref: "/collections/new-in", background: "#c2185b", textColor: "#fff9f4" }],
    ["SocialProof", { heading: "#GulaabRangGirls", handle: "gulaabrang", profileUrl: "https://instagram.com/gulaabrang" }],
    ["Reviews", { heading: "Real reviews, real smiles", minRating: 4, limit: 6 }],
    ["Newsletter", { heading: "Get first dibs on new prints", subheading: "New drops every fortnight. Subscribers hear first.", buttonLabel: "Count me in", tone: "accent" }],
  ],
  categories: [
    { slug: "kurtas", name: "Kurtas", description: "Straight, A-line and flared kurtas in hand block print." },
    { slug: "kurta-sets", name: "Kurta Sets", description: "Kurta, pant and dupatta sets." },
    { slug: "dresses", name: "Dresses", description: "Block print dresses for sunny days." },
    { slug: "co-ords", name: "Co-ords", description: "Shirt and pant co-ord sets." },
    { slug: "dupattas", name: "Dupattas", description: "Printed and tie-dye dupattas." },
  ],
  collections: [
    { slug: "new-in", title: "New In", description: "The latest prints.", rules: { tag: "new" } },
    { slug: "holi-edit", title: "The Holi Edit", description: "Bright colours for the festival of colour." },
    { slug: "under-1999", title: "Under ₹1,999", description: "Easy prices, happy prints.", rules: { tag: "value" } },
  ],
  menu: [
    { title: "New In", to: "/collections/new-in" },
    { title: "Kurtas", to: "/categories/kurtas", children: [{ title: "Straight kurtas", to: "/search?q=straight" }, { title: "A-line kurtas", to: "/search?q=a-line" }, { title: "Short kurtis", to: "/search?q=short" }] },
    { title: "Kurta Sets", to: "/categories/kurta-sets" },
    { title: "Dresses", to: "/categories/dresses" },
    { title: "Co-ords", to: "/categories/co-ords" },
    { title: "Holi Edit", to: "/collections/holi-edit" },
    { title: "Under ₹1,999", to: "/collections/under-1999", highlight: true },
  ],
  faqs: [
    ["Will the colours run?", "Block prints use fixed dyes, but some colour can release in the first wash. Wash separately in cold water and dry in shade."],
    ["How do your sizes fit?", "Our kurtas have a relaxed fit. Check the size guide on each product; if you're between sizes, pick the smaller one."],
    ["Can I pay cash on delivery?", "Yes, COD is available on orders up to ₹7,500 across most PIN codes."],
    ["How long does delivery take?", "Orders ship in 1–2 working days and usually arrive in 3–6 days."],
  ],
  testimonials: [
    { quote: "The pink is SO pink. Got compliments all day at office.", name: "Tanvi", place: "Mumbai" },
    { quote: "Fabric is soft even after many washes. Ordered three more.", name: "Pooja", place: "Indore" },
    { quote: "Fast delivery and the fit is spot on.", name: "Shruti", place: "Bengaluru" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "Obsessed", body: "The print is so cheerful and the cotton breathes well.", author: "Ananya" },
    { product: 1, rating: 5, title: "Perfect set", body: "Dupatta is super soft, pants have pockets!", author: "Riya" },
    { product: 2, rating: 4, title: "Cute dress", body: "Loved it, slightly long for me at 5'1.", author: "Neha" },
    { product: 4, rating: 5, title: "Weekend favourite", body: "Wore the co-ord on a trip, got so many compliments.", author: "Kavya" },
  ],
  products: [
    { title: "Rani Pink Buti A-line Kurta", type: "kurta", category: "kurtas", price: 1499, mrp: 1999, sizes: "apparel", fabric: "Cotton", work: "Hand block print", occasion: ["Casual", "Work"], tags: ["new", "bestseller", "a-line", "value"], featured: true, short: "Tiny white butis on rani pink cotton.", description: "An A-line kurta in breathable cambric cotton, hand block printed with small white butis on rani pink. Three-quarter sleeves and side pockets.", art: { silhouette: "kurtaAline", print: "sanganeri", colors: { ground: "#d81b60", ink: "#fff3f6", accent: "#ffcf56", leaf: "#fff3f6" } }, collections: ["holi-edit"] },
    { title: "Marigold Bagh Kurta Set", type: "kurta_set", category: "kurta-sets", price: 2399, mrp: 2999, sizes: "apparel", fabric: "Cotton", work: "Hand block print", occasion: ["Festive", "Casual"], tags: ["new", "bestseller"], featured: true, short: "Marigold kurta, pants and mulmul dupatta.", description: "A three-piece set in marigold cotton with a tonal bagh print, straight pants with pockets and a soft mulmul dupatta edged in pompoms.", art: { silhouette: "suitSet", print: "bagru", colors: { ground: "#ffb703", ink: "#9a3412", accent: "#d81b60", leaf: "#2a9d8f", altGround: "#9a3412", altPrint: "solid", drapePrint: "leheriya", drapeGround: "#ffe0ea" } }, collections: ["holi-edit"] },
    { title: "Mint Leheriya Tiered Dress", type: "dress", category: "dresses", price: 1899, mrp: 2299, sizes: "standard", fabric: "Cotton", work: "Leheriya print", occasion: ["Casual", "Vacation"], tags: ["new", "value"], short: "Tiered midi in mint and pink leheriya.", description: "A tiered midi dress in soft cotton with a leheriya wave print in mint and candy pink. Smocked back and a tie at the waist.", art: { silhouette: "maxi", print: "leheriya", colors: { ground: "#c8f1e4", ink: "#ff6fa3", accent: "#2a9d8f", leaf: "#ffb703" } } },
    { title: "Sunset Bandhani Kurta", type: "kurta", category: "kurtas", price: 1299, sizes: "apparel", fabric: "Rayon", work: "Bandhani print", occasion: ["Casual"], tags: ["value", "straight"], short: "Orange bandhani dots on a straight kurta.", description: "A straight kurta in fluid rayon with an all-over bandhani dot print in sunset orange and cream.", art: { silhouette: "kurtaStraight", print: "bandhani", colors: { ground: "#f3722c", ink: "#fff1e0", accent: "#ffd166", leaf: "#fff1e0" } }, collections: ["under-1999", "holi-edit"] },
    { title: "Parrot Green Co-ord Set", type: "co_ord_set", category: "co-ords", price: 2199, mrp: 2599, sizes: "apparel", fabric: "Cotton linen", work: "Hand block print", occasion: ["Vacation", "Casual"], tags: ["new", "bestseller"], featured: true, short: "Relaxed shirt and pant in parrot green.", description: "A boxy shirt and straight pant co-ord in cotton-linen, printed with little parrots and leaves.", art: { silhouette: "coord", print: "kalamkari", colors: { ground: "#80b918", ink: "#1b4332", accent: "#ff9f1c", leaf: "#1b4332" } } },
    { title: "Candy Stripe Short Kurti", type: "kurta", category: "kurtas", price: 999, mrp: 1299, sizes: "apparel", fabric: "Cotton", work: "Printed", occasion: ["Casual", "College"], tags: ["value", "short"], short: "Pink-and-white striped short kurti.", description: "A hip-length kurti in candy stripes, perfect with jeans. Mandarin collar and roll-up sleeves.", art: { silhouette: "tee", print: "stripes", colors: { ground: "#ffe5ec", ink: "#e5386d", accent: "#ffb703", leaf: "#e5386d" } }, collections: ["under-1999"] },
    { title: "Indigo Anar Kurta Set", type: "kurta_set", category: "kurta-sets", price: 2599, sizes: "apparel", fabric: "Cotton", work: "Dabu print", occasion: ["Festive", "Work"], tags: ["bestseller"], short: "Indigo dabu kurta with pomegranate motifs.", description: "An indigo dabu kurta set printed with pomegranate motifs, paired with straight pants and a white kota dupatta.", art: { silhouette: "suitSet", print: "dabu", colors: { ground: "#2b3a67", ink: "#f1e9da", accent: "#e76f51", leaf: "#f1e9da", altGround: "#f1e9da", altPrint: "solid", drapePrint: "polka", drapeGround: "#f7f3ea" } } },
    { title: "Lemon Leheriya Dupatta", type: "dupatta", category: "dupattas", price: 799, sizes: "free", fabric: "Kota doria", work: "Leheriya", occasion: ["Festive"], tags: ["value", "new"], short: "Lemon and pink leheriya on kota.", description: "A sheer kota doria dupatta tie-dyed in lemon and pink leheriya with tassel edges.", art: { silhouette: "dupatta", print: "leheriya", colors: { ground: "#fff3b0", ink: "#f15bb5", accent: "#fee440", leaf: "#00bbf9" } }, collections: ["under-1999", "holi-edit"] },
    { title: "Coral Polka Wrap Dress", type: "dress", category: "dresses", price: 2099, mrp: 2499, sizes: "standard", fabric: "Cotton", work: "Printed", occasion: ["Brunch", "Casual"], tags: ["new"], short: "Wrap dress in coral polka.", description: "A cotton wrap dress with a flutter sleeve and white polka dots on coral.", art: { silhouette: "dress", print: "polka", colors: { ground: "#ff7b6b", ink: "#fff7f2", accent: "#fff7f2", leaf: "#fff7f2" } } },
  ],
  shippingNote: "Free shipping above ₹999. Orders ship in 1–2 working days; delivery in 3–6 days across India.",
  returnsNote: "Easy 7-day returns and exchanges on unworn items with tags.",
};

// ----------------------------------------------------------------------------- 03 · Contemporary ethnic, commercial
const pinkcity: StoreSpec = {
  slug: "pinkcity",
  name: "Pinkcity Threads",
  tagline: "Contemporary ethnic wear for every day of the week",
  story: "Pinkcity Threads designs modern ethnic wear for women who want comfort at work and polish at dinner. We cut in Jaipur, print with partner units and restock our bestsellers every month.",
  email: "support@pinkcitythreads.test",
  phone: "+919799123456",
  address: { line1: "Plot 44, Sitapura Industrial Area", city: "Jaipur", state: "Rajasthan", postal_code: "302022" },
  social: { instagram: "https://instagram.com/pinkcitythreads", facebook: "https://facebook.com/pinkcitythreads" },
  seo: { title: "Pinkcity Threads — Kurtas, kurta sets & co-ords for women", description: "Shop contemporary ethnic wear: straight kurtas, kurta sets, palazzo sets and co-ords. New styles weekly, easy returns." },
  legalName: "Pinkcity Threads Pvt Ltd",
  gstin: "08AAHCP4321L1Z9",
  backdrop: ["#f5f4f2", "#e3e0dc"],
  bannerBackdrop: ["#f7d6e0", "#3a2331"],
  hero: { eyebrow: "The workwear edit", heading: "Kurtas that work as hard as you do", subheading: "Breathable fabrics, pockets and easy fits.", ctaLabel: "Shop kurtas", ctaHref: "/categories/kurtas", textTone: "light", align: "left" },
  announcement: ["Flat 15% off your first order — code FIRST15", "Free returns within 15 days"],
  tokens: {
    colors: { primary: "#1e1e24", secondary: "#d6336c", accent: "#d6336c", background: "#ffffff", text: "#1e1e24", border: "#ececef", sale: "#d6336c" },
    headingFont: "dm-sans",
    bodyFont: "dm-sans",
    headingCase: "normal",
    buttonShape: "rounded",
    buttonVariant: "solid",
    cardRadius: "sm",
    containerWidth: "wide",
    spacing: "compact",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-left",
  productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: true, showDiscountPercent: true, secondImageOnHover: true },
  footerTone: "light",
  home: [
    ["Hero", { height: "medium", overlay: 20 }],
    ["TrustBadges", { items: [{ icon: "truck", title: "Free shipping", text: "On orders above ₹799" }, { icon: "return", title: "15-day returns", text: "Free pickup" }, { icon: "cod", title: "Cash on delivery", text: "All over India" }, { icon: "secure", title: "Secure payments", text: "UPI, cards, net banking" }], tone: "muted" }],
    ["CategoryGrid", { eyebrow: "Categories", heading: "Shop by category", mode: "auto", limit: 6, shape: "square" }],
    ["ProductGrid", { eyebrow: "Trending now", heading: "Kurtas", source: "category", categoryId: "$category:kurtas", limit: 8, columns: 4, viewAllHref: "/categories/kurtas" }],
    ["ProductGrid", { eyebrow: "Complete looks", heading: "Kurta & palazzo sets", source: "category", categoryId: "$category:kurta-sets", limit: 4, columns: 4, viewAllHref: "/categories/kurta-sets" }],
    ["CollectionGrid", { eyebrow: "Collections", heading: "Shop the edits", mode: "auto", limit: 3, columns: 3 }],
    ["Bestseller", { heading: "Bestsellers", limit: 8, layout: "carousel" }],
    ["FAQ", { heading: "Questions, answered", source: "store", limit: 5 }],
  ],
  categories: [
    { slug: "kurtas", name: "Kurtas", description: "Straight, A-line and angrakha kurtas." },
    { slug: "kurta-sets", name: "Kurta Sets", description: "Coordinated kurta, pant and dupatta sets." },
    { slug: "palazzo-sets", name: "Palazzo Sets", description: "Kurtas paired with flowing palazzos." },
    { slug: "co-ords", name: "Co-ords", description: "Matching tops and bottoms." },
    { slug: "tops", name: "Tops & Tunics", description: "Short kurtis and tunics." },
    { slug: "dupattas", name: "Dupattas", description: "Printed and embroidered dupattas." },
  ],
  collections: [
    { slug: "workwear", title: "Workwear", description: "Polished, breathable, pocketed.", rules: { tag: "work" } },
    { slug: "festive-lite", title: "Festive Lite", description: "Dressy without the fuss.", rules: { tag: "festive" } },
    { slug: "new-this-week", title: "New This Week", description: "Just added.", rules: { tag: "new" } },
  ],
  menu: [
    { title: "New", to: "/collections/new-this-week" },
    { title: "Kurtas", to: "/categories/kurtas", children: [{ title: "Straight", to: "/search?q=straight" }, { title: "A-line", to: "/search?q=a-line" }, { title: "Angrakha", to: "/search?q=angrakha" }] },
    { title: "Sets", to: "/categories/kurta-sets", children: [{ title: "Kurta sets", to: "/categories/kurta-sets" }, { title: "Palazzo sets", to: "/categories/palazzo-sets" }, { title: "Co-ords", to: "/categories/co-ords" }] },
    { title: "Tops", to: "/categories/tops" },
    { title: "Workwear", to: "/collections/workwear" },
    { title: "Festive", to: "/collections/festive-lite" },
  ],
  faqs: [
    ["What is your return policy?", "Return or exchange unworn items within 15 days. We arrange a free pickup from your address."],
    ["How do I choose my size?", "Use the size guide on each product page. Our garments follow standard Indian sizing with a regular fit."],
    ["When will my order arrive?", "Metro cities: 2–4 days. Rest of India: 4–7 days. You'll get tracking by SMS and email."],
    ["Do you offer COD?", "Yes, on orders up to ₹10,000."],
    ["Can I cancel my order?", "You can cancel from your account until the order is shipped."],
  ],
  testimonials: [
    { quote: "Finally kurtas with real pockets. I own four now.", name: "Harleen", place: "Gurugram" },
    { quote: "The fit is consistent every time, which is rare online.", name: "Sneha", place: "Chennai" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "Office staple", body: "Doesn't crush, pockets are deep, colour is smart.", author: "Vaishali" },
    { product: 0, rating: 4, title: "Good fit", body: "True to size. Sleeves a touch long.", author: "Rohini" },
    { product: 2, rating: 5, title: "Love the palazzo", body: "Flowy and comfy for long days.", author: "Megha" },
    { product: 6, rating: 5, title: "Wedding guest win", body: "Wore it to a mehendi, looked dressy but was so comfortable.", author: "Isha" },
    { product: 4, rating: 4, title: "Nice co-ord", body: "Good quality, wish there were more colours.", author: "Aditi" },
  ],
  products: [
    { title: "Graphite Pintuck Straight Kurta", type: "kurta", category: "kurtas", price: 1599, mrp: 1999, sizes: "apparel", colors: [{ name: "Graphite", hex: "#3b3d45" }, { name: "Olive", hex: "#6b7248" }], fabric: "Cotton flex", work: "Pintucks", occasion: ["Work"], tags: ["work", "bestseller", "straight"], featured: true, short: "Pintucked yoke, side pockets, office-ready.", description: "A straight kurta in wrinkle-resistant cotton flex with a pintucked yoke, button placket and deep side pockets.", art: { silhouette: "kurtaStraight", print: "stripes", colors: { ground: "#3b3d45", ink: "#2c2e35", accent: "#4a4c55", leaf: "#2c2e35" } } },
    { title: "Blush Angrakha Kurta", type: "kurta", category: "kurtas", price: 1799, sizes: "apparel", fabric: "Viscose", work: "Embroidered", occasion: ["Work", "Festive"], tags: ["work", "festive", "angrakha", "new"], short: "Overlap angrakha front with tonal thread work.", description: "An angrakha kurta in soft viscose with an overlapping front, tie detail and tonal thread embroidery at the neckline.", art: { silhouette: "kurtaAline", print: "vine", colors: { ground: "#f2c4ce", ink: "#c98a96", accent: "#fff", leaf: "#c98a96" } } },
    { title: "Teal Ikat Palazzo Set", type: "kurta_set", category: "palazzo-sets", price: 2299, mrp: 2799, sizes: "apparel", fabric: "Cotton", work: "Ikat print", occasion: ["Work", "Casual"], tags: ["work", "new"], featured: true, short: "Ikat kurta with flared palazzos.", description: "A teal ikat-print kurta paired with solid flared palazzos in breathable cotton.", art: { silhouette: "palazzoSet", print: "ikat", colors: { ground: "#1b7a78", ink: "#f2efe6", accent: "#f4a261", leaf: "#f2efe6", altGround: "#135e5c", altPrint: "solid" } } },
    { title: "Ivory Chikan Kurta Set", type: "kurta_set", category: "kurta-sets", price: 3299, mrp: 3999, sizes: "apparel", fabric: "Cotton mul", work: "Chikankari", occasion: ["Festive"], tags: ["festive", "bestseller"], short: "Ivory mul with chikankari and a matching dupatta.", description: "Kurta, pants and dupatta in ivory cotton mul with delicate chikankari at the yoke and hem.", art: { silhouette: "suitSet", print: "vine", colors: { ground: "#f4efe6", ink: "#c8bda9", accent: "#e8dfcf", leaf: "#c8bda9", altGround: "#e8dfcf", altPrint: "solid", drapePrint: "polka", drapeGround: "#fbf8f2" } } },
    { title: "Rust Linen Co-ord", type: "co_ord_set", category: "co-ords", price: 2699, sizes: "apparel", fabric: "Linen blend", work: "Solid", occasion: ["Work", "Travel"], tags: ["work"], short: "Linen shirt-kurta and straight pants.", description: "A relaxed shirt-kurta and straight pant in rust linen blend. Pairs as a set or separates.", art: { silhouette: "coord", print: "solid", colors: { ground: "#b5562f", ink: "#8e4224", accent: "#8e4224", leaf: "#8e4224" } } },
    { title: "Navy Printed Tunic", type: "top", category: "tops", price: 999, mrp: 1299, sizes: "apparel", fabric: "Rayon", work: "Printed", occasion: ["Casual", "Work"], tags: ["work", "value"], short: "Hip-length tunic in a navy geometric print.", description: "A hip-length tunic in rayon with a small geometric print, notch neck and three-quarter sleeves.", art: { silhouette: "tee", print: "check", colors: { ground: "#1f2d4d", ink: "#3a4f7a", accent: "#e9c46a", leaf: "#3a4f7a" } } },
    { title: "Mauve Mirror-work Kurta Set", type: "kurta_set", category: "kurta-sets", price: 3599, mrp: 4299, sizes: "apparel", fabric: "Chanderi", work: "Mirror work", occasion: ["Festive", "Wedding"], tags: ["festive", "new"], featured: true, short: "Chanderi kurta set with mirror work.", description: "A mauve chanderi kurta with mirror and thread work at the neck, straight pants and an organza dupatta.", art: { silhouette: "suitSet", print: "zari", colors: { ground: "#9d6b84", ink: "#e9d8a6", accent: "#f1e3b8", leaf: "#e9d8a6", altGround: "#7a4f65", altPrint: "solid", drapePrint: "zari", drapeGround: "#d9b8c8" } } },
    { title: "Sage Chevron A-line Kurta", type: "kurta", category: "kurtas", price: 1399, sizes: "apparel", fabric: "Cotton", work: "Printed", occasion: ["Casual"], tags: ["a-line", "value"], short: "Soft chevron print on sage.", description: "An A-line kurta with a subtle chevron print in sage and ivory. Round neck, keyhole placket.", art: { silhouette: "kurtaAline", print: "chevron", colors: { ground: "#b7c4a6", ink: "#6e7f5a", accent: "#f1efe6", leaf: "#6e7f5a" } } },
    { title: "Ochre Palazzo Set with Dupatta", type: "kurta_set", category: "palazzo-sets", price: 2499, mrp: 2999, sizes: "apparel", fabric: "Cotton", work: "Block print", occasion: ["Festive", "Casual"], tags: ["festive"], short: "Ochre kurta, palazzo and printed dupatta.", description: "A three-piece palazzo set in ochre cotton with a delicate floral block print and a contrast dupatta.", art: { silhouette: "palazzoSet", print: "sanganeri", colors: { ground: "#d9a441", ink: "#8a3b12", accent: "#fff5e0", leaf: "#5a6b2f", altGround: "#8a3b12", altPrint: "solid" } } },
    { title: "Printed Mul Dupatta", type: "dupatta", category: "dupattas", price: 699, sizes: "free", fabric: "Cotton mul", work: "Printed", occasion: ["Everyday"], tags: ["value"], short: "Featherlight mul dupatta.", description: "A soft printed mul dupatta with a delicate border. Pairs with plain kurtas.", art: { silhouette: "dupatta", print: "sanganeri", colors: { ground: "#fbe7ec", ink: "#d6336c", accent: "#f4a261", leaf: "#6a994e" } } },
  ],
  shippingNote: "Free shipping above ₹799. Delivery in 2–7 days depending on your city.",
  returnsNote: "15-day free returns with doorstep pickup. Refunds within 5 working days of pickup.",
};

// ----------------------------------------------------------------------------- 04 · Earthy minimal handloom
const mitti: StoreSpec = {
  slug: "mitti",
  name: "Mitti & Maati",
  tagline: "Handloom clothing in the colours of the earth",
  story: "Mitti & Maati is a small studio working with handloom weavers in western India. We use natural dyes — madder, indigo, pomegranate, iron rust — and cut simple, generous shapes meant to be worn for years.",
  email: "studio@mittimaati.test",
  phone: "+919414056789",
  address: { line1: "Near Ajmer Gate, Old City", city: "Udaipur", state: "Rajasthan", postal_code: "313001" },
  social: { instagram: "https://instagram.com/mittimaati", pinterest: "https://pinterest.com/mittimaati" },
  seo: { title: "Mitti & Maati — Natural dye handloom clothing", description: "Slow, handloom clothing dyed with madder, indigo and iron. Kurtas, dresses and co-ords in earthy colours." },
  legalName: "Mitti Maati Studio",
  backdrop: ["#efe8dc", "#d8cab5"],
  bannerBackdrop: ["#cdb79a", "#3b2e22"],
  hero: { eyebrow: "Season four", heading: "Clothes that age like the earth", subheading: "Handloom cottons, natural dyes, generous shapes.", ctaLabel: "See the collection", ctaHref: "/collections/season-four", textTone: "light", align: "center" },
  announcement: ["Naturally dyed · handloom · made in small runs"],
  tokens: {
    colors: { primary: "#3b2e22", secondary: "#9c4a2f", accent: "#9c4a2f", background: "#f4efe7", text: "#33291f", border: "#ddd2c1", sale: "#9c4a2f" },
    headingFont: "classic-serif",
    bodyFont: "humanist-sans",
    headingCase: "normal",
    buttonShape: "square",
    buttonVariant: "outline",
    cardRadius: "none",
    containerWidth: "default",
    spacing: "airy",
  },
  header: { sticky: false, showStoreName: true },
  headerLayout: "logo-left",
  productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showDiscountPercent: false, secondImageOnHover: true },
  footerTone: "muted",
  home: [
    ["Hero", { height: "large", overlay: 25 }],
    ["EditorialImageText", { eyebrow: "Our materials", heading: "Colour from roots, bark and rust", body: "Madder root gives us terracotta and rose. Indigo leaves, the blues. Pomegranate rind and iron make our olives and greys. Natural dyes shift gently with light and wash, and that's the point.", imagePath: "$img:editorial", alt: "Naturally dyed handloom fabric", imagePosition: "left", tone: "light", ctaLabel: "About the studio", ctaHref: "/pages/about" }],
    ["ProductGrid", { eyebrow: "Season four", heading: "The collection", source: "collection", collectionId: "$collection:season-four", limit: 6, columns: 3, viewAllHref: "/collections/season-four" }],
    ["Lookbook", { eyebrow: "Worn", heading: "In the old city", layout: "row" }],
    ["BrandStory", { eyebrow: "Slow by design", heading: "Six weavers, one small studio", body: "We release four small collections a year and never discount our handloom. What doesn't sell becomes quilts and bags in our studio.", imagePath: "$img:story", alt: "Handloom weaving", stats: [{ value: "6", label: "Weaving households" }, { value: "4", label: "Natural dyes" }, { value: "0", label: "Synthetic fibres" }] }],
    ["Newsletter", { heading: "Letters from the studio", subheading: "One email when a new season is ready.", buttonLabel: "Subscribe", tone: "light" }],
  ],
  categories: [
    { slug: "kurtas", name: "Kurtas", description: "Handloom kurtas in natural dyes." },
    { slug: "dresses", name: "Dresses", description: "Easy, generous dresses." },
    { slug: "co-ords", name: "Co-ords", description: "Sets you can wear apart." },
    { slug: "stoles", name: "Stoles", description: "Handwoven stoles and dupattas." },
  ],
  collections: [
    { slug: "season-four", title: "Season Four", description: "Madder, indigo and iron." },
    { slug: "indigo-room", title: "The Indigo Room", description: "Everything dyed in indigo.", rules: { tag: "indigo" } },
  ],
  menu: [
    { title: "Season Four", to: "/collections/season-four" },
    { title: "Kurtas", to: "/categories/kurtas" },
    { title: "Dresses", to: "/categories/dresses" },
    { title: "Co-ords", to: "/categories/co-ords" },
    { title: "Stoles", to: "/categories/stoles" },
    { title: "Indigo", to: "/collections/indigo-room" },
  ],
  faqs: [
    ["Will natural dyes fade?", "Natural dyes soften gently over time. Wash in cold water with a mild detergent and dry in shade to keep them rich longer."],
    ["Why do colours vary between pieces?", "Each dye bath is different, so every piece is slightly unique. We photograph representative pieces."],
    ["Do you use any synthetic fibres?", "No. Everything we make is handloom cotton, linen or wool."],
  ],
  testimonials: [
    { quote: "The madder kurta has softened beautifully over a year.", name: "Anjali", place: "Ahmedabad" },
    { quote: "Quiet, thoughtful clothes. I feel good wearing them.", name: "Meera", place: "Kochi" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "Softens beautifully", body: "Gets better with every wash.", author: "Gauri" },
    { product: 2, rating: 5, title: "Perfect weight", body: "Breezy for summer, structured enough for work.", author: "Nandini" },
    { product: 5, rating: 4, title: "Lovely indigo", body: "Colour is deep and even. Slightly boxy fit.", author: "Parul" },
  ],
  products: [
    { title: "Madder Rose Handloom Kurta", type: "kurta", category: "kurtas", price: 3400, sizes: "apparel", fabric: "Handloom cotton", work: "Natural dye", occasion: ["Everyday", "Work"], tags: ["madder"], featured: true, short: "Madder-dyed handloom kurta in dusty rose.", description: "A straight handloom kurta dyed in madder root to a dusty rose. Hand-finished seams, patch pockets and a relaxed shoulder.", art: { silhouette: "kurtaStraight", print: "solid", colors: { ground: "#b56a5c", ink: "#8e4e43", accent: "#8e4e43", leaf: "#8e4e43" } }, collections: ["season-four"] },
    { title: "Iron Grey Khadi Dress", type: "dress", category: "dresses", price: 4200, sizes: "standard", fabric: "Khadi", work: "Natural dye", occasion: ["Everyday"], tags: ["iron"], featured: true, short: "Iron-rust grey khadi midi.", description: "A generous khadi dress dyed with iron and pomegranate rind to a soft charcoal. Gathered yoke, deep pockets.", art: { silhouette: "maxi", print: "solid", colors: { ground: "#5c5a55", ink: "#44423e", accent: "#44423e", leaf: "#44423e" } }, collections: ["season-four"] },
    { title: "Olive Handloom Co-ord", type: "co_ord_set", category: "co-ords", price: 5200, sizes: "apparel", fabric: "Handloom cotton", work: "Natural dye", occasion: ["Work", "Travel"], tags: ["pomegranate"], short: "Olive kurta-shirt and pant.", description: "A shirt-kurta and straight pant in olive handloom, dyed with pomegranate rind and iron.", art: { silhouette: "coord", print: "solid", colors: { ground: "#6b6a3f", ink: "#55542f", accent: "#55542f", leaf: "#55542f" } }, collections: ["season-four"] },
    { title: "Terracotta Stripe Kurta", type: "kurta", category: "kurtas", price: 3100, sizes: "apparel", fabric: "Handloom cotton", work: "Woven stripe", occasion: ["Everyday"], tags: ["madder"], short: "Woven terracotta stripe on ecru.", description: "A handloom kurta with woven terracotta stripes on ecru, cut straight with side slits.", art: { silhouette: "kurtaStraight", print: "stripes", colors: { ground: "#e9dfcd", ink: "#a4533a", accent: "#6b6a3f", leaf: "#a4533a" } }, collections: ["season-four"] },
    { title: "Ecru Linen Wrap Dress", type: "dress", category: "dresses", price: 4600, sizes: "standard", fabric: "Linen", work: "Undyed", occasion: ["Everyday", "Vacation"], tags: ["linen"], short: "Undyed linen wrap dress.", description: "A wrap dress in undyed handloom linen with a wide sash. Softens with every wear.", art: { silhouette: "dress", print: "solid", colors: { ground: "#e3d8c3", ink: "#cabda4", accent: "#cabda4", leaf: "#cabda4" } } },
    { title: "Deep Indigo Kurta", type: "kurta", category: "kurtas", price: 3300, sizes: "apparel", fabric: "Handloom cotton", work: "Indigo vat dye", occasion: ["Everyday", "Work"], tags: ["indigo"], short: "Vat-dyed indigo handloom kurta.", description: "Dipped fourteen times in a fermented indigo vat for a deep, even blue. Straight cut with a band collar.", art: { silhouette: "kurtaStraight", print: "solid", colors: { ground: "#243b5e", ink: "#1a2c47", accent: "#1a2c47", leaf: "#1a2c47" } }, collections: ["indigo-room", "season-four"] },
    { title: "Indigo Shibori Stole", type: "dupatta", category: "stoles", price: 1800, sizes: "free", fabric: "Handloom cotton", work: "Shibori", occasion: ["Everyday"], tags: ["indigo"], short: "Hand-bound shibori in indigo.", description: "A handwoven cotton stole, hand-bound and dyed in indigo shibori.", art: { silhouette: "dupatta", print: "bandhani", colors: { ground: "#2a4470", ink: "#dfe6f0", accent: "#dfe6f0", leaf: "#dfe6f0" } }, collections: ["indigo-room"] },
    { title: "Rust Kala Cotton Pants", type: "bottom", category: "co-ords", price: 2400, sizes: "apparel", fabric: "Kala cotton", work: "Natural dye", occasion: ["Everyday"], tags: ["madder"], short: "Rain-fed kala cotton pants in rust.", description: "Straight pants in rain-fed kala cotton from Kutch, dyed rust with madder. Elastic back waist and pockets.", art: { silhouette: "palazzoSet", print: "solid", colors: { ground: "#e9dfcd", ink: "#cabda4", accent: "#cabda4", leaf: "#cabda4", altGround: "#a4533a", altPrint: "solid" } } },
  ],
  shippingNote: "Free shipping across India. Each piece is packed in recycled paper and ships within 4 working days.",
  returnsNote: "Returns accepted within 7 days on unworn pieces. We don't accept returns on stoles for hygiene reasons.",
};

// ----------------------------------------------------------------------------- 05 · High-conversion D2C
const rangeela: StoreSpec = {
  slug: "rangeela",
  name: "Rangeela Jaipur",
  tagline: "New styles every week. Prices you'll love.",
  story: "Rangeela Jaipur brings fresh ethnic and fusion styles every week at honest prices. We design in-house, produce in Jaipur and ship fast across India.",
  email: "hello@rangeelajaipur.test",
  phone: "+919950112233",
  address: { line1: "B-12 Malviya Nagar Industrial Area", city: "Jaipur", state: "Rajasthan", postal_code: "302017" },
  social: { instagram: "https://instagram.com/rangeelajaipur", facebook: "https://facebook.com/rangeelajaipur", youtube: "https://youtube.com/@rangeelajaipur" },
  seo: { title: "Rangeela Jaipur — Kurtas, sets & dresses on sale | Up to 50% off", description: "Shop trending kurtas, kurta sets, dresses and co-ords. New styles weekly, big sales, COD and easy returns." },
  legalName: "Rangeela Retail Pvt Ltd",
  gstin: "08AAJCR7788Q1Z1",
  backdrop: ["#f7f7f7", "#e7e7e7"],
  bannerBackdrop: ["#ffe0e3", "#111111"],
  hero: { eyebrow: "End of season sale", heading: "Up to 50% off", subheading: "Kurtas from ₹699. Sets from ₹1,299. This week only.", ctaLabel: "Shop the sale", ctaHref: "/collections/sale", textTone: "light", align: "center" },
  announcement: ["SALE: Up to 50% off", "Extra 10% off on prepaid orders", "Free shipping above ₹599"],
  tokens: {
    colors: { primary: "#111111", secondary: "#e63946", accent: "#e63946", background: "#ffffff", text: "#111111", border: "#e9e9e9", sale: "#e63946" },
    headingFont: "geometric-sans",
    bodyFont: "geometric-sans",
    headingCase: "uppercase",
    buttonShape: "square",
    buttonVariant: "solid",
    cardRadius: "none",
    containerWidth: "full",
    spacing: "compact",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-left",
  productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: true, showDiscountPercent: true, secondImageOnHover: true },
  footerTone: "dark",
  home: [
    ["Hero", { height: "medium", overlay: 25 }],
    ["SaleBanner", { eyebrow: "Limited time", heading: "Extra 10% off prepaid", subheading: "Applied automatically at checkout on UPI and cards.", code: "PREPAID10", endsText: "Ends in 48 hours", ctaLabel: "Shop now", ctaHref: "/collections/sale", background: "#e63946", textColor: "#ffffff" }],
    ["CategoryGrid", { heading: "Shop by category", mode: "auto", limit: 6, shape: "square" }],
    ["ProductCarousel", { eyebrow: "Hot right now", heading: "Sale picks", source: "sale", limit: 10, viewAllHref: "/collections/sale" }],
    ["PromoBanner", { tiles: [{ imagePath: "$img:promo1", alt: "Kurtas on sale", heading: "Kurtas from ₹699", ctaLabel: "Shop kurtas", ctaHref: "/categories/kurtas" }, { imagePath: "$img:promo2", alt: "Kurta sets", heading: "Sets from ₹1,299", ctaLabel: "Shop sets", ctaHref: "/categories/kurta-sets" }, { imagePath: "$img:promo3", alt: "Dresses", heading: "Dresses under ₹999", ctaLabel: "Shop dresses", ctaHref: "/categories/dresses" }], aspect: "portrait" }],
    ["NewArrivals", { heading: "New this week", limit: 10, layout: "carousel", viewAllHref: "/collections/new" }],
    ["Bestseller", { heading: "Bestsellers", limit: 8, layout: "grid" }],
    ["TrustBadges", { items: [{ icon: "truck", title: "Free shipping", text: "Above ₹599" }, { icon: "cod", title: "COD available", text: "Pay on delivery" }, { icon: "return", title: "7-day returns", text: "No questions asked" }, { icon: "secure", title: "100% secure", text: "Encrypted payments" }], tone: "dark" }],
  ],
  categories: [
    { slug: "kurtas", name: "Kurtas", description: "Trending kurtas at great prices." },
    { slug: "kurta-sets", name: "Kurta Sets", description: "Complete sets." },
    { slug: "dresses", name: "Dresses", description: "Fusion and ethnic dresses." },
    { slug: "co-ords", name: "Co-ords", description: "Matching sets." },
    { slug: "tops", name: "Tops", description: "Short kurtis and tops." },
  ],
  collections: [
    { slug: "sale", title: "Sale", description: "Up to 50% off.", rules: { tag: "sale" } },
    { slug: "new", title: "New This Week", description: "Fresh styles.", rules: { tag: "new" } },
    { slug: "under-999", title: "Under ₹999", description: "Great styles under ₹999.", rules: { tag: "under999" } },
  ],
  menu: [
    { title: "Sale", to: "/collections/sale", highlight: true },
    { title: "New", to: "/collections/new" },
    { title: "Kurtas", to: "/categories/kurtas" },
    { title: "Sets", to: "/categories/kurta-sets" },
    { title: "Dresses", to: "/categories/dresses" },
    { title: "Co-ords", to: "/categories/co-ords" },
    { title: "Under ₹999", to: "/collections/under-999" },
  ],
  faqs: [
    ["How long does delivery take?", "2–5 days in metros, up to 7 days elsewhere."],
    ["Is COD available?", "Yes. Prepaid orders get an extra 10% off."],
    ["What's the return policy?", "Returns and exchanges within 7 days, free pickup."],
  ],
  testimonials: [
    { quote: "Unbelievable prices for this quality.", name: "Kritika", place: "Lucknow" },
    { quote: "Delivered in two days! The set fits perfectly.", name: "Simran", place: "Chandigarh" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "Steal deal", body: "Got it at half price, looks premium.", author: "Payal" },
    { product: 1, rating: 4, title: "Good set", body: "Nice quality, dupatta is thin.", author: "Swati" },
    { product: 3, rating: 5, title: "So cute", body: "Perfect for college.", author: "Diya" },
    { product: 5, rating: 5, title: "Value for money", body: "Wore it for Karva Chauth, loved it.", author: "Preeti" },
  ],
  products: [
    { title: "Magenta Floral Straight Kurta", type: "kurta", category: "kurtas", price: 699, mrp: 1399, sizes: "apparel", fabric: "Rayon", work: "Printed", occasion: ["Casual"], tags: ["sale", "bestseller", "under999"], featured: true, short: "Bold magenta florals at 50% off.", description: "A straight rayon kurta with a bold magenta floral print, round neck and three-quarter sleeves.", art: { silhouette: "kurtaStraight", print: "bigfloral", colors: { ground: "#ffe3ec", ink: "#d6246e", accent: "#ffb703", leaf: "#2a9d8f" } } },
    { title: "Emerald Gota Kurta Set", type: "kurta_set", category: "kurta-sets", price: 1299, mrp: 2599, sizes: "apparel", fabric: "Rayon", work: "Gota patti", occasion: ["Festive"], tags: ["sale", "bestseller"], featured: true, short: "Emerald set with gota trims.", description: "An emerald kurta with gota patti trims, matching pants and a printed dupatta.", art: { silhouette: "suitSet", print: "zari", colors: { ground: "#047857", ink: "#f4d58d", accent: "#f4d58d", leaf: "#f4d58d", altGround: "#065f46", altPrint: "solid", drapePrint: "leheriya", drapeGround: "#f4d58d" } } },
    { title: "Black Mirror Kurta", type: "kurta", category: "kurtas", price: 899, mrp: 1599, sizes: "apparel", fabric: "Cotton blend", work: "Mirror work", occasion: ["Festive", "Party"], tags: ["sale", "new", "under999"], short: "Black kurta with mirror yoke.", description: "A black A-line kurta with a mirror-work yoke that catches the light.", art: { silhouette: "kurtaAline", print: "zari", colors: { ground: "#111111", ink: "#d9d9d9", accent: "#e5e5e5", leaf: "#d9d9d9" } } },
    { title: "Yellow Checks Shirt Dress", type: "dress", category: "dresses", price: 899, mrp: 1499, sizes: "standard", fabric: "Cotton", work: "Checks", occasion: ["College", "Casual"], tags: ["sale", "new", "under999"], short: "Sunny checks, belted.", description: "A belted shirt dress in yellow and white checks with roll-up sleeves.", art: { silhouette: "dress", print: "check", colors: { ground: "#fff3b0", ink: "#f4c20d", accent: "#ffffff", leaf: "#f4c20d" } } },
    { title: "Lilac Co-ord Set", type: "co_ord_set", category: "co-ords", price: 1199, mrp: 1999, sizes: "apparel", fabric: "Rayon", work: "Printed", occasion: ["Casual", "Vacation"], tags: ["sale", "new"], short: "Printed lilac shirt and pants.", description: "A relaxed printed shirt and flared pant set in lilac.", art: { silhouette: "coord", print: "sanganeri", colors: { ground: "#d9c6f5", ink: "#7b4fb7", accent: "#ffd166", leaf: "#4c956c" } } },
    { title: "Red Bandhani Anarkali", type: "kurta", category: "kurtas", price: 1499, mrp: 2999, sizes: "apparel", fabric: "Georgette", work: "Bandhani print", occasion: ["Festive"], tags: ["sale", "bestseller"], short: "Flared bandhani anarkali in red.", description: "A flared anarkali in red georgette with a bandhani print and gota-trimmed hem.", art: { silhouette: "anarkali", print: "bandhani", colors: { ground: "#c1121f", ink: "#fdf0d5", accent: "#ffd166", leaf: "#fdf0d5" } } },
    { title: "White Schiffli Top", type: "top", category: "tops", price: 649, mrp: 999, sizes: "apparel", fabric: "Cotton", work: "Schiffli", occasion: ["Casual"], tags: ["under999", "new"], short: "Airy white schiffli top.", description: "A short white kurti in cotton schiffli with scalloped hem.", art: { silhouette: "tee", print: "polka", colors: { ground: "#fafafa", ink: "#e0e0e0", accent: "#e0e0e0", leaf: "#e0e0e0" } } },
    { title: "Peach Printed Palazzo Set", type: "kurta_set", category: "kurta-sets", price: 1399, mrp: 2299, sizes: "apparel", fabric: "Rayon", work: "Printed", occasion: ["Casual", "Work"], tags: ["sale"], short: "Peach kurta with palazzo.", description: "A peach printed kurta with flowing palazzos.", art: { silhouette: "palazzoSet", print: "sanganeri", colors: { ground: "#ffcdb2", ink: "#e5989b", accent: "#6d6875", leaf: "#6d6875", altGround: "#e5989b", altPrint: "solid" } } },
    { title: "Navy Chevron Maxi", type: "dress", category: "dresses", price: 1099, mrp: 1799, sizes: "standard", fabric: "Rayon", work: "Printed", occasion: ["Vacation"], tags: ["sale"], short: "Chevron maxi for holidays.", description: "A floor-length maxi with a navy and white chevron print.", art: { silhouette: "maxi", print: "chevron", colors: { ground: "#1d3557", ink: "#f1faee", accent: "#e63946", leaf: "#f1faee" } } },
  ],
  shippingNote: "Free shipping above ₹599. Most orders ship the same day.",
  returnsNote: "7-day returns and exchanges with free pickup. Sale items are exchange-only.",
};

export const STORES_A: StoreSpec[] = [chinar, gulaab, pinkcity, mitti, rangeela];
