import type { StoreSpec } from "./types";

// ----------------------------------------------------------------------------- 06 · Contemporary feminine ethnic
const noor: StoreSpec = {
  slug: "noor",
  name: "Noor Ethnica",
  tagline: "Graceful kurta sets and suits for every celebration",
  story: "Noor Ethnica designs contemporary ethnic wear with a soft, feminine hand: easy silhouettes, delicate embroidery and colours that flatter. Designed in Delhi, made with care.",
  email: "care@noorethnica.test",
  phone: "+919811223344",
  address: { line1: "F-21 Okhla Phase 1", city: "New Delhi", state: "Delhi", postal_code: "110020" },
  social: { instagram: "https://instagram.com/noorethnica", facebook: "https://facebook.com/noorethnica", pinterest: "https://pinterest.com/noorethnica" },
  seo: { title: "Noor Ethnica — Kurta sets, suits & festive wear for women", description: "Shop graceful kurta sets, suit sets, dresses and festive wear with delicate embroidery. Designed in Delhi." },
  legalName: "Noor Ethnica Pvt Ltd",
  gstin: "07AAFCN2468P1Z4",
  backdrop: ["#f8eeea", "#e9d2cb"],
  bannerBackdrop: ["#f3d9d1", "#4a2c34"],
  hero: { eyebrow: "The festive season", heading: "Soft colours, quiet sparkle", subheading: "New kurta sets with hand embroidery, in blush, sage and ivory.", ctaLabel: "Shop festive", ctaHref: "/collections/festive", textTone: "light", align: "left" },
  announcement: ["Free shipping on all orders", "Festive gifting: complimentary potli with every set"],
  tokens: {
    colors: { primary: "#4a2c34", secondary: "#c9776b", accent: "#c9776b", background: "#fcf7f5", text: "#3d2a2f", border: "#efdfd9", sale: "#b5485b" },
    headingFont: "playfair",
    bodyFont: "dm-sans",
    headingCase: "normal",
    buttonShape: "rounded",
    buttonVariant: "solid",
    cardRadius: "sm",
    containerWidth: "wide",
    spacing: "comfortable",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-center",
  productCard: { imageRatio: "tall", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: true, showDiscountPercent: true, secondImageOnHover: true },
  footerTone: "muted",
  home: [
    ["Hero", { height: "large", overlay: 20 }],
    ["CollectionGrid", { eyebrow: "Shop by occasion", heading: "Dressed for the moment", mode: "auto", limit: 4, columns: 4 }],
    ["NewArrivals", { eyebrow: "Just in", heading: "New arrivals", limit: 8, layout: "carousel", viewAllHref: "/search?sort=newest" }],
    ["EditorialImageText", { eyebrow: "The details", heading: "Embroidered by hand, one motif at a time", body: "Our karigars in Lucknow and Delhi work each floral by hand in resham and sequins. Look closely and you'll find tiny differences — the mark of a human hand.", imagePath: "$img:editorial", alt: "Close-up of embroidery", imagePosition: "right", tone: "light", ctaLabel: "Shop embroidered", ctaHref: "/collections/festive" }],
    ["ProductGrid", { eyebrow: "Suit sets", heading: "Three-piece favourites", source: "category", categoryId: "$category:suit-sets", limit: 4, columns: 4, viewAllHref: "/categories/suit-sets" }],
    ["Testimonials", { heading: "What our customers say" }],
    ["Reviews", { heading: "Recent reviews", minRating: 4, limit: 3 }],
    ["Newsletter", { heading: "Be the first to know", subheading: "New collections, restocks and private sales.", buttonLabel: "Subscribe", tone: "muted" }],
  ],
  categories: [
    { slug: "kurta-sets", name: "Kurta Sets", description: "Kurta and pant sets." },
    { slug: "suit-sets", name: "Suit Sets", description: "Three-piece suits with dupattas." },
    { slug: "dresses", name: "Dresses", description: "Ethnic and fusion dresses." },
    { slug: "kurtas", name: "Kurtas", description: "Standalone kurtas." },
  ],
  collections: [
    { slug: "festive", title: "Festive", description: "For pujas, sangeets and Diwali nights.", rules: { tag: "festive" } },
    { slug: "everyday-grace", title: "Everyday Grace", description: "Easy pieces for work and weekends.", rules: { tag: "everyday" } },
    { slug: "wedding-guest", title: "Wedding Guest", description: "Dressy, comfortable, photo-ready.", rules: { tag: "wedding" } },
    { slug: "summer-whites", title: "Summer Whites", description: "Ivory and white.", rules: { tag: "white" } },
  ],
  menu: [
    { title: "New In", to: "/search?sort=newest" },
    { title: "Kurta Sets", to: "/categories/kurta-sets" },
    { title: "Suit Sets", to: "/categories/suit-sets" },
    { title: "Dresses", to: "/categories/dresses" },
    { title: "Occasions", children: [{ title: "Festive", to: "/collections/festive" }, { title: "Wedding guest", to: "/collections/wedding-guest" }, { title: "Everyday", to: "/collections/everyday-grace" }, { title: "Summer whites", to: "/collections/summer-whites" }] },
  ],
  faqs: [
    ["Is the embroidery done by hand?", "Yes, all embroidered pieces are hand-worked by our karigars. Machine-printed pieces are labelled as printed."],
    ["Can I get alterations?", "We offer free sleeve and length alterations on suit sets. Add a note at checkout."],
    ["How long is delivery?", "3–6 working days across India."],
  ],
  testimonials: [
    { quote: "The blush set photographed beautifully at my cousin's sangeet.", name: "Aishwarya", place: "Jaipur" },
    { quote: "Embroidery is so delicate and the fabric falls well.", name: "Farah", place: "Hyderabad" },
    { quote: "Customer care helped me with an exchange in two days.", name: "Nidhi", place: "Nagpur" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "So pretty", body: "Colour is exactly as shown and the embroidery is lovely.", author: "Pallavi" },
    { product: 1, rating: 5, title: "Elegant", body: "Wore it for Diwali, got compliments.", author: "Kiran" },
    { product: 4, rating: 4, title: "Comfy dress", body: "Lovely flow, slightly long.", author: "Juhi" },
  ],
  products: [
    { title: "Blush Resham Kurta Set", type: "kurta_set", category: "kurta-sets", price: 4499, mrp: 5299, sizes: "apparel", fabric: "Viscose chanderi", work: "Resham embroidery", occasion: ["Festive", "Wedding"], tags: ["festive", "wedding"], featured: true, short: "Blush chanderi kurta with resham florals.", description: "A blush chanderi kurta with resham floral embroidery at the yoke, paired with straight pants.", art: { silhouette: "suitSet", print: "sanganeri", colors: { ground: "#f3cfc6", ink: "#c9776b", accent: "#e9c46a", leaf: "#8aa07a", altGround: "#e3b5aa", altPrint: "solid", drapePrint: "zari", drapeGround: "#f7e3dd" } } },
    { title: "Sage Anarkali Suit Set", type: "suit", category: "suit-sets", price: 5299, mrp: 5999, sizes: "apparel", fabric: "Georgette", work: "Sequin embroidery", occasion: ["Festive", "Wedding"], tags: ["festive", "wedding"], featured: true, short: "Flared sage anarkali with a sequin dupatta.", description: "A flared anarkali in sage georgette with sequin embroidery, straight pants and an organza dupatta.", art: { silhouette: "anarkali", print: "zari", colors: { ground: "#a7b89a", ink: "#f2e6c9", accent: "#f2e6c9", leaf: "#f2e6c9" } } },
    { title: "Ivory Chikan Kurta", type: "kurta", category: "kurtas", price: 2799, sizes: "apparel", fabric: "Cotton", work: "Chikankari", occasion: ["Everyday", "Work"], tags: ["everyday", "white"], short: "Hand chikankari on ivory cotton.", description: "A straight ivory kurta with hand chikankari all over the front.", art: { silhouette: "kurtaStraight", print: "vine", colors: { ground: "#f5efe4", ink: "#d8ccb6", accent: "#ece2d0", leaf: "#d8ccb6" } } },
    { title: "Dusty Rose Suit Set", type: "suit", category: "suit-sets", price: 3899, mrp: 4499, sizes: "apparel", fabric: "Cotton silk", work: "Thread work", occasion: ["Festive"], tags: ["festive"], short: "Dusty rose suit with thread-work dupatta.", description: "A cotton-silk kurta with tonal thread work, straight pants and a printed dupatta.", art: { silhouette: "suitSet", print: "vine", colors: { ground: "#d8a7a0", ink: "#b3776f", accent: "#f1e0d8", leaf: "#b3776f", altGround: "#b3776f", altPrint: "solid", drapePrint: "sanganeri", drapeGround: "#f3dfd9" } } },
    { title: "Mauve Tiered Ethnic Dress", type: "dress", category: "dresses", price: 3299, sizes: "standard", fabric: "Cotton", work: "Printed", occasion: ["Everyday", "Brunch"], tags: ["everyday"], short: "Tiered mauve dress with a tie waist.", description: "A tiered midi in soft cotton with a delicate floral print and a tie waist.", art: { silhouette: "maxi", print: "sanganeri", colors: { ground: "#c9a3b8", ink: "#8a5a74", accent: "#f2e6c9", leaf: "#6b8a6a" } } },
    { title: "White Lace Kurta Set", type: "kurta_set", category: "kurta-sets", price: 3599, sizes: "apparel", fabric: "Cotton", work: "Lace", occasion: ["Everyday", "Summer"], tags: ["white", "everyday"], short: "White cotton set with lace trims.", description: "A white cotton kurta set with lace inserts at the hem and sleeves.", art: { silhouette: "suitSet", print: "polka", colors: { ground: "#fbfaf7", ink: "#ece8df", accent: "#ece8df", leaf: "#ece8df", altGround: "#f1efe9", altPrint: "solid", drapePrint: "polka", drapeGround: "#fbfaf7" } } },
    { title: "Teal Gota Kurta", type: "kurta", category: "kurtas", price: 2499, mrp: 2899, sizes: "apparel", fabric: "Rayon", work: "Gota", occasion: ["Festive"], tags: ["festive"], short: "Teal kurta with gota detail.", description: "An A-line teal kurta with gota detailing at the neckline and hem.", art: { silhouette: "kurtaAline", print: "zari", colors: { ground: "#1e6f72", ink: "#e9c46a", accent: "#e9c46a", leaf: "#e9c46a" } } },
    { title: "Lavender Wedding Guest Set", type: "kurta_set", category: "kurta-sets", price: 5799, mrp: 6499, sizes: "apparel", fabric: "Organza", work: "Sequin", occasion: ["Wedding"], tags: ["wedding", "festive"], short: "Organza set with scattered sequins.", description: "A lavender organza kurta with scattered sequins, a satin lining and flared pants.", art: { silhouette: "palazzoSet", print: "zari", colors: { ground: "#c8b6e2", ink: "#f5f0ff", accent: "#fff", leaf: "#f5f0ff", altGround: "#a48bc9", altPrint: "solid" } } },
  ],
  shippingNote: "Free shipping on all orders, delivered in 3–6 working days.",
  returnsNote: "Returns within 10 days on unused items. Altered pieces cannot be returned.",
};

// ----------------------------------------------------------------------------- 07 · Wedding & occasion couture
const vivaah: StoreSpec = {
  slug: "vivaah",
  name: "Vivaah Couture",
  tagline: "Bridal and occasion wear, handcrafted in Jaipur",
  story: "Vivaah Couture creates lehengas, sarees and occasion ensembles for weddings and celebrations. Every piece is embroidered in our Jaipur atelier with zardozi, gota and resham, and finished to order.",
  email: "atelier@vivaahcouture.test",
  phone: "+919828099887",
  address: { line1: "C-Scheme, Prithviraj Road", city: "Jaipur", state: "Rajasthan", postal_code: "302001" },
  social: { instagram: "https://instagram.com/vivaahcouture", pinterest: "https://pinterest.com/vivaahcouture", youtube: "https://youtube.com/@vivaahcouture" },
  seo: { title: "Vivaah Couture — Bridal lehengas, wedding sarees & occasion wear", description: "Handcrafted bridal lehengas, zardozi sarees and occasion ensembles from our Jaipur atelier. Book a video consultation." },
  legalName: "Vivaah Couture Atelier Pvt Ltd",
  gstin: "08AAKCV1357R1Z6",
  backdrop: ["#221b1c", "#0e0b0c"],
  bannerBackdrop: ["#c59d5f", "#1a0c10"],
  hero: { eyebrow: "The bridal edit · 2026", heading: "For the day you'll remember forever", subheading: "Hand-embroidered lehengas and sarees, finished to order in our Jaipur atelier.", ctaLabel: "Explore bridal", ctaHref: "/collections/bridal", textTone: "light", align: "center" },
  announcement: ["Book a free video consultation with our stylist", "Complimentary alterations on bridal orders"],
  tokens: {
    colors: { primary: "#4a0f1c", secondary: "#c59d5f", accent: "#c59d5f", background: "#faf6ef", text: "#2b1418", border: "#eadfcd", sale: "#8c1c2c" },
    headingFont: "marcellus",
    bodyFont: "humanist-sans",
    headingCase: "uppercase",
    buttonShape: "square",
    buttonVariant: "solid",
    cardRadius: "none",
    containerWidth: "wide",
    spacing: "airy",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-center",
  productCard: { imageRatio: "tall", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showDiscountPercent: false, secondImageOnHover: true },
  footerTone: "dark",
  home: [
    ["Hero", { height: "full", overlay: 35 }],
    ["CollectionGrid", { eyebrow: "Occasions", heading: "Every ceremony, considered", mode: "auto", limit: 4, columns: 4 }],
    ["Lookbook", { eyebrow: "Lookbook", heading: "The wedding season", layout: "masonry" }],
    ["ProductGrid", { eyebrow: "Bridal", heading: "Lehengas", source: "category", categoryId: "$category:lehengas", limit: 3, columns: 3, viewAllHref: "/categories/lehengas" }],
    ["EditorialImageText", { eyebrow: "The atelier", heading: "Zardozi, the old way", body: "Our karigars stitch zardozi with gold-coated wire and dabka coils on a wooden adda, just as their fathers did. A bridal lehenga carries more than 400 hours of handwork.", imagePath: "$img:editorial", alt: "Zardozi embroidery detail", imagePosition: "left", tone: "dark", ctaLabel: "Book a consultation", ctaHref: "/pages/contact" }],
    ["ProductGrid", { eyebrow: "Sarees", heading: "Heirloom sarees", source: "category", categoryId: "$category:sarees", limit: 3, columns: 3, viewAllHref: "/categories/sarees" }],
    ["Testimonials", { heading: "Our brides" }],
    ["FAQ", { heading: "Bridal questions", source: "store", limit: 5 }],
  ],
  categories: [
    { slug: "lehengas", name: "Lehengas", description: "Bridal and occasion lehengas." },
    { slug: "sarees", name: "Sarees", description: "Wedding and festive sarees." },
    { slug: "anarkalis", name: "Anarkalis", description: "Floor-length anarkalis." },
    { slug: "sharara-sets", name: "Sharara Sets", description: "Sharara and gharara sets." },
  ],
  collections: [
    { slug: "bridal", title: "Bridal", description: "For the bride.", rules: { tag: "bridal" } },
    { slug: "sangeet", title: "Sangeet & Mehendi", description: "Colour and movement for the dance floor.", rules: { tag: "sangeet" } },
    { slug: "reception", title: "Reception", description: "Evening glamour.", rules: { tag: "reception" } },
    { slug: "family-of-the-bride", title: "Family of the Bride", description: "Elegant pieces for mothers, sisters and friends.", rules: { tag: "family" } },
  ],
  menu: [
    { title: "Bridal", to: "/collections/bridal" },
    { title: "Lehengas", to: "/categories/lehengas" },
    { title: "Sarees", to: "/categories/sarees" },
    { title: "Anarkalis", to: "/categories/anarkalis" },
    { title: "Occasions", children: [{ title: "Sangeet & Mehendi", to: "/collections/sangeet" }, { title: "Reception", to: "/collections/reception" }, { title: "Family of the bride", to: "/collections/family-of-the-bride" }] },
    { title: "Consultation", to: "/pages/contact" },
  ],
  faqs: [
    ["How far in advance should I order a bridal lehenga?", "We recommend ordering 10–12 weeks before your wedding. Express timelines are possible on select designs."],
    ["Can I customise colours and embroidery?", "Yes. Book a video consultation and our stylist will guide you through fabric, colour and embroidery options."],
    ["Do you take measurements?", "We send a guided measurement sheet and review it with you on a video call. Two fittings are included for bridal orders."],
    ["Are alterations included?", "Complimentary alterations are included on bridal orders."],
    ["What is your cancellation policy?", "Made-to-order pieces cannot be cancelled once production begins."],
  ],
  testimonials: [
    { quote: "My lehenga was everything I dreamed of. The team held my hand through every fitting.", name: "Ritika & Karan", place: "Udaipur wedding" },
    { quote: "The zardozi is museum-quality. My mother cried.", name: "Sanya", place: "Delhi" },
    { quote: "Ordered the saree for my sister's reception. Perfect drape.", name: "Mehak", place: "Mumbai" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "A dream", body: "Heavy, rich and still comfortable to dance in.", author: "Ritika" },
    { product: 2, rating: 5, title: "Heirloom saree", body: "The zari is gorgeous.", author: "Anushka" },
  ],
  products: [
    { title: "Sindoor Zardozi Bridal Lehenga", type: "lehenga", category: "lehengas", price: 185000, sizes: "standard", fabric: "Raw silk", work: "Zardozi and dabka", occasion: ["Bridal", "Wedding"], tags: ["bridal"], featured: true, short: "Sindoor red raw silk with zardozi.", description: "A bridal lehenga in sindoor red raw silk, hand-embroidered in zardozi, dabka and pearls, with a net dupatta and matching blouse. Made to order in 10–12 weeks.", art: { silhouette: "lehenga", print: "zari", colors: { ground: "#9b111e", ink: "#d8b25a", accent: "#e2c06a", leaf: "#c09a48", altGround: "#9b111e", altPrint: "zari", drapePrint: "zari", drapeGround: "#c4424f" } } },
    { title: "Pastel Mint Sangeet Lehenga", type: "lehenga", category: "lehengas", price: 68000, mrp: 74000, sizes: "standard", fabric: "Georgette", work: "Mirror and resham", occasion: ["Sangeet", "Mehendi"], tags: ["sangeet"], featured: true, short: "Mint georgette with mirror work.", description: "A light mint georgette lehenga with mirror and resham work that moves beautifully on the dance floor.", art: { silhouette: "lehenga", print: "bandhani", colors: { ground: "#bfe3d0", ink: "#f7f1e1", accent: "#e2c06a", leaf: "#8fbfa6", altGround: "#bfe3d0", altPrint: "zari", drapePrint: "bandhani", drapeGround: "#f3d6df" } } },
    { title: "Kanjeevaram Zari Saree", type: "saree", category: "sarees", price: 54000, sizes: "free", fabric: "Pure silk", work: "Zari weave", occasion: ["Wedding", "Reception"], tags: ["reception", "family"], featured: true, short: "Temple-border silk in deep aubergine.", description: "A pure silk saree in deep aubergine with a woven gold temple border and pallu. Unstitched blouse piece included.", art: { silhouette: "saree", print: "zari", colors: { ground: "#4b1d3f", ink: "#d8b25a", accent: "#e2c06a", leaf: "#c09a48", altGround: "#d8b25a", altPrint: "solid", drapePrint: "zari", drapeGround: "#6a2a58" } } },
    { title: "Midnight Sequin Reception Saree", type: "saree", category: "sarees", price: 42000, mrp: 46000, sizes: "free", fabric: "Georgette", work: "Sequin", occasion: ["Reception", "Cocktail"], tags: ["reception"], short: "Midnight blue with scattered sequins.", description: "A midnight blue georgette saree with hand-scattered sequins and a ready-to-wear blouse.", art: { silhouette: "saree", print: "zari", colors: { ground: "#15203b", ink: "#c7cbd6", accent: "#d9dde6", leaf: "#c7cbd6", altGround: "#15203b", altPrint: "zari", drapePrint: "zari", drapeGround: "#15203b" } } },
    { title: "Ivory Gota Anarkali", type: "kurta", category: "anarkalis", price: 36000, sizes: "standard", fabric: "Chanderi silk", work: "Gota patti", occasion: ["Mehendi", "Family"], tags: ["family", "sangeet"], short: "Ivory anarkali with gota patti.", description: "A floor-length ivory chanderi anarkali with gota patti borders and a matching dupatta.", art: { silhouette: "anarkali", print: "zari", colors: { ground: "#efe6d4", ink: "#c9a45a", accent: "#d8b25a", leaf: "#c9a45a" } } },
    { title: "Rani Pink Sharara Set", type: "suit", category: "sharara-sets", price: 28000, mrp: 31000, sizes: "standard", fabric: "Silk", work: "Resham and zari", occasion: ["Sangeet", "Family"], tags: ["sangeet", "family"], short: "Rani pink kurti with sharara.", description: "A short rani pink kurti with zari and resham work, flared sharara and a tissue dupatta.", art: { silhouette: "palazzoSet", print: "zari", colors: { ground: "#c2185b", ink: "#e2c06a", accent: "#e2c06a", leaf: "#e2c06a", altGround: "#9d1149", altPrint: "zari" } } },
    { title: "Champagne Reception Lehenga", type: "lehenga", category: "lehengas", price: 96000, sizes: "standard", fabric: "Net", work: "Sequin and cutdana", occasion: ["Reception"], tags: ["reception", "bridal"], short: "Champagne net lehenga with cutdana.", description: "A champagne net lehenga with sequin and cutdana embroidery and a cape-style dupatta.", art: { silhouette: "lehenga", print: "zari", colors: { ground: "#d8c3a5", ink: "#fff3dd", accent: "#fff3dd", leaf: "#b89d78", altGround: "#d8c3a5", altPrint: "zari", drapePrint: "polka", drapeGround: "#e9dcc8" } } },
  ],
  shippingNote: "Insured, signature-on-delivery shipping across India. Ready pieces ship in 5 working days; made-to-order in 8–12 weeks.",
  returnsNote: "Ready-to-ship sarees can be returned within 7 days unworn with tags. Made-to-order and altered pieces are final sale.",
};

// ----------------------------------------------------------------------------- 08 · Modern minimal monochrome
const neel: StoreSpec = {
  slug: "studioneel",
  name: "Studio Neel",
  tagline: "Considered basics for modern Indian wardrobes",
  story: "Studio Neel makes a small wardrobe of essentials: kurtas, shirts and sets in solid colours and honest fabrics. Fewer pieces, better made.",
  email: "hello@studioneel.test",
  phone: "+918048001122",
  address: { line1: "3rd Floor, 80 Feet Road, Indiranagar", city: "Bengaluru", state: "Karnataka", postal_code: "560038" },
  social: { instagram: "https://instagram.com/studioneel" },
  seo: { title: "Studio Neel — Minimal kurtas, shirts and sets", description: "Minimal, well-made kurtas, shirts and co-ords in solid colours. Designed in Bengaluru." },
  legalName: "Neel Studio Pvt Ltd",
  gstin: "29AAGCS9753K1Z3",
  backdrop: ["#f4f4f2", "#e4e4e1"],
  bannerBackdrop: ["#e8e8e5", "#1b1b1b"],
  hero: { eyebrow: "Collection 07", heading: "Less, but better", subheading: "Solid colours. Honest fabrics. Clean lines.", ctaLabel: "Shop the collection", ctaHref: "/collections/essentials", textTone: "light", align: "left" },
  announcement: ["Complimentary shipping and returns"],
  tokens: {
    colors: { primary: "#111111", secondary: "#111111", accent: "#111111", background: "#fafafa", text: "#111111", border: "#e6e6e6", sale: "#111111" },
    headingFont: "modern-sans",
    bodyFont: "modern-sans",
    headingCase: "normal",
    buttonShape: "square",
    buttonVariant: "solid",
    cardRadius: "none",
    containerWidth: "wide",
    spacing: "airy",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-left",
  productCard: { imageRatio: "portrait", textAlign: "left", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showDiscountPercent: false, showBadges: false, secondImageOnHover: true },
  footerTone: "light",
  home: [
    ["Hero", { height: "full", overlay: 10 }],
    ["ProductGrid", { heading: "Essentials", source: "collection", collectionId: "$collection:essentials", limit: 8, columns: 4, viewAllHref: "/collections/essentials" }],
    ["EditorialImageText", { heading: "Made to be worn often", body: "We cut every piece from a small set of fabrics we trust: 120 GSM cotton poplin, washed linen and a soft cotton twill. Seams are French-finished, buttons are corozo.", imagePath: "$img:editorial", alt: "Detail of cotton fabric", imagePosition: "right", tone: "light" }],
    ["ProductGrid", { heading: "Shirts", source: "category", categoryId: "$category:shirts", limit: 4, columns: 4, viewAllHref: "/categories/shirts" }],
    ["Newsletter", { heading: "Studio notes", subheading: "Occasional. Never promotional.", buttonLabel: "Subscribe", tone: "light" }],
  ],
  categories: [
    { slug: "kurtas", name: "Kurtas", description: "Solid kurtas." },
    { slug: "shirts", name: "Shirts", description: "Band-collar and relaxed shirts." },
    { slug: "sets", name: "Sets", description: "Matching sets." },
    { slug: "dresses", name: "Dresses", description: "Minimal dresses." },
  ],
  collections: [{ slug: "essentials", title: "Essentials", description: "The core wardrobe." }],
  menu: [
    { title: "Kurtas", to: "/categories/kurtas" },
    { title: "Shirts", to: "/categories/shirts" },
    { title: "Sets", to: "/categories/sets" },
    { title: "Dresses", to: "/categories/dresses" },
    { title: "About", to: "/pages/about" },
  ],
  faqs: [
    ["What fabrics do you use?", "Cotton poplin, washed linen and cotton twill, all from mills in Tamil Nadu and Gujarat."],
    ["How do your sizes run?", "True to size with a relaxed fit. Measurements are listed on every product."],
  ],
  testimonials: [{ quote: "Exactly the shirt I was looking for. Wore it three days in a row.", name: "Rohan", place: "Bengaluru" }],
  reviews: [
    { product: 0, rating: 5, title: "Perfect basic", body: "Crisp, cool, and the length is right.", author: "Vikram" },
    { product: 2, rating: 5, title: "Great shirt", body: "The corozo buttons are a nice touch.", author: "Aditya" },
  ],
  products: [
    { title: "Kurta 01 — Black", type: "kurta", category: "kurtas", price: 2900, sizes: "apparel", fabric: "Cotton poplin", occasion: ["Everyday", "Work"], tags: ["essentials"], featured: true, short: "A straight black poplin kurta.", description: "A straight kurta in 120 GSM cotton poplin with a band collar and hidden placket.", art: { silhouette: "kurtaStraight", print: "solid", colors: { ground: "#1b1b1b", ink: "#111", accent: "#111", leaf: "#111" } }, collections: ["essentials"] },
    { title: "Kurta 01 — Ecru", type: "kurta", category: "kurtas", price: 2900, sizes: "apparel", fabric: "Cotton poplin", occasion: ["Everyday", "Work"], tags: ["essentials"], short: "A straight ecru poplin kurta.", description: "Our core kurta in ecru poplin. Band collar, hidden placket, side slits.", art: { silhouette: "kurtaStraight", print: "solid", colors: { ground: "#ece6da", ink: "#d8d0c1", accent: "#d8d0c1", leaf: "#d8d0c1" } }, collections: ["essentials"] },
    { title: "Shirt 03 — Indigo Linen", type: "shirt", category: "shirts", price: 3200, sizes: "apparel", fabric: "Washed linen", occasion: ["Everyday"], tags: ["essentials"], featured: true, short: "Relaxed indigo linen shirt.", description: "A relaxed shirt in washed linen with a band collar and corozo buttons.", art: { silhouette: "jacket", print: "solid", colors: { ground: "#2d3a5a", ink: "#222c45", accent: "#222c45", leaf: "#222c45" } }, collections: ["essentials"] },
    { title: "Shirt 03 — White Linen", type: "shirt", category: "shirts", price: 3200, sizes: "apparel", fabric: "Washed linen", occasion: ["Everyday"], tags: ["essentials"], short: "Relaxed white linen shirt.", description: "The same relaxed shirt in white washed linen.", art: { silhouette: "jacket", print: "solid", colors: { ground: "#f3f2ee", ink: "#e1dfd8", accent: "#e1dfd8", leaf: "#e1dfd8" } }, collections: ["essentials"] },
    { title: "Set 02 — Charcoal Twill", type: "co_ord_set", category: "sets", price: 5400, sizes: "apparel", fabric: "Cotton twill", occasion: ["Work", "Travel"], tags: ["essentials"], short: "Charcoal twill shirt and trouser.", description: "An overshirt and straight trouser in soft charcoal cotton twill.", art: { silhouette: "coord", print: "solid", colors: { ground: "#3a3a3a", ink: "#2b2b2b", accent: "#2b2b2b", leaf: "#2b2b2b" } }, collections: ["essentials"] },
    { title: "Dress 01 — Black", type: "dress", category: "dresses", price: 4200, sizes: "standard", fabric: "Cotton poplin", occasion: ["Everyday", "Evening"], tags: ["essentials"], short: "A column dress in black poplin.", description: "A sleeveless column dress with a halter strap and deep pockets.", art: { silhouette: "maxi", print: "solid", colors: { ground: "#1d1d1d", ink: "#000", accent: "#000", leaf: "#000" } }, collections: ["essentials"] },
    { title: "Kurta 02 — Olive Linen", type: "kurta", category: "kurtas", price: 3400, sizes: "apparel", fabric: "Washed linen", occasion: ["Everyday"], tags: [], short: "Olive linen kurta.", description: "A slightly longer kurta in olive washed linen.", art: { silhouette: "kurtaStraight", print: "solid", colors: { ground: "#6b6b4f", ink: "#55553f", accent: "#55553f", leaf: "#55553f" } }, collections: ["essentials"] },
    { title: "Set 01 — Sand Linen", type: "co_ord_set", category: "sets", price: 5200, sizes: "apparel", fabric: "Washed linen", occasion: ["Vacation"], tags: [], short: "Sand linen shirt and pant.", description: "A camp-collar shirt and drawstring pant in sand linen.", art: { silhouette: "coord", print: "solid", colors: { ground: "#d9ccb4", ink: "#c3b59b", accent: "#c3b59b", leaf: "#c3b59b" } }, collections: ["essentials"] },
  ],
  shippingNote: "Complimentary shipping across India in 2–5 days.",
  returnsNote: "Complimentary returns within 14 days.",
};

// ----------------------------------------------------------------------------- 09 · Gen-Z fashion
const drip: StoreSpec = {
  slug: "desidrip",
  name: "Desi Drip",
  tagline: "Indie prints, streetwear fits. Drops every Friday.",
  story: "Desi Drip mashes up Indian prints with streetwear cuts. We drop small runs every Friday, and when they're gone, they're gone.",
  email: "yo@desidrip.test",
  phone: "+919167001234",
  address: { line1: "Unit 7, Lower Parel Mills", city: "Mumbai", state: "Maharashtra", postal_code: "400013" },
  social: { instagram: "https://instagram.com/desidrip", youtube: "https://youtube.com/@desidrip", x: "https://x.com/desidrip" },
  seo: { title: "Desi Drip — Indie print tees, co-ords & streetwear", description: "Indian prints meet streetwear. Oversized tees, co-ords and shirts in limited Friday drops." },
  legalName: "Desi Drip Apparel LLP",
  gstin: "27AAQFD8642L1Z8",
  backdrop: ["#d6f3ff", "#9fdcf5"],
  bannerBackdrop: ["#ffe45e", "#7b61ff"],
  hero: { eyebrow: "DROP 23 · LIVE NOW", heading: "Block print, but make it street", subheading: "Oversized tees and co-ords in limited runs. When they're gone, they're gone.", ctaLabel: "Cop the drop", ctaHref: "/collections/drop-23", textTone: "light", align: "left" },
  announcement: ["🔥 Drop 23 is live", "Free shipping over ₹999", "Easy exchanges"],
  tokens: {
    colors: { primary: "#0f0f0f", secondary: "#7b61ff", accent: "#7b61ff", background: "#fffdf5", text: "#0f0f0f", border: "#0f0f0f", sale: "#ff3d71" },
    headingFont: "grotesk",
    bodyFont: "grotesk",
    headingCase: "uppercase",
    buttonShape: "pill",
    buttonVariant: "solid",
    cardRadius: "lg",
    containerWidth: "full",
    spacing: "compact",
  },
  header: { sticky: true, showStoreName: true },
  headerLayout: "logo-left",
  productCard: { imageRatio: "square", textAlign: "left", badgeStyle: "filled", showQuickAdd: true, showRating: true, showDiscountPercent: true, secondImageOnHover: true },
  footerTone: "dark",
  home: [
    ["AnnouncementBar", { messages: [{ text: "Next drop: Friday 7 PM · turn on notifications", href: "" }], tone: "accent" }],
    ["Hero", { height: "large", overlay: 10 }],
    ["NewArrivals", { eyebrow: "Drop 23", heading: "New drops", limit: 10, layout: "carousel", viewAllHref: "/collections/drop-23" }],
    ["SocialProof", { heading: "Seen on the gram", handle: "desidrip", profileUrl: "https://instagram.com/desidrip" }],
    ["PromoBanner", { tiles: [{ imagePath: "$img:promo1", alt: "Oversized tee", heading: "Oversized tees", text: "From ₹899", ctaLabel: "Shop tees", ctaHref: "/categories/tees" }, { imagePath: "$img:promo2", alt: "Co-ord set", heading: "Co-ord season", text: "Matching is a personality.", ctaLabel: "Shop co-ords", ctaHref: "/categories/co-ords" }, { imagePath: "$img:promo3", alt: "Printed shirt", heading: "Resort shirts", text: "Loud prints only.", ctaLabel: "Shop shirts", ctaHref: "/categories/shirts" }], aspect: "square" }],
    ["Bestseller", { eyebrow: "Trending", heading: "Everyone's wearing", limit: 8, layout: "grid" }],
    ["Testimonials", { heading: "The fam says" }],
    ["Newsletter", { heading: "Get drop alerts", subheading: "Be first in line. We only email on drop days.", buttonLabel: "I'm in", tone: "accent" }],
  ],
  categories: [
    { slug: "tees", name: "Tees", description: "Oversized printed tees." },
    { slug: "shirts", name: "Shirts", description: "Resort and camp shirts." },
    { slug: "co-ords", name: "Co-ords", description: "Matching sets." },
    { slug: "dresses", name: "Dresses", description: "Slip and shirt dresses." },
    { slug: "bottoms", name: "Bottoms", description: "Pants and shorts." },
  ],
  collections: [
    { slug: "drop-23", title: "Drop 23", description: "This week's drop.", rules: { tag: "drop23" } },
    { slug: "under-999", title: "Under ₹999", description: "Pocket-friendly.", rules: { tag: "under999" } },
  ],
  menu: [
    { title: "Drop 23", to: "/collections/drop-23", highlight: true },
    { title: "Tees", to: "/categories/tees" },
    { title: "Shirts", to: "/categories/shirts" },
    { title: "Co-ords", to: "/categories/co-ords" },
    { title: "Dresses", to: "/categories/dresses" },
    { title: "Under ₹999", to: "/collections/under-999" },
  ],
  faqs: [
    ["When are new drops?", "Every Friday at 7 PM IST. Sign up for alerts so you don't miss out."],
    ["Will sold-out items come back?", "Sometimes! Hit 'notify me' and we'll email you if we restock."],
    ["How do oversized tees fit?", "Boxy and dropped-shoulder. Size down for a regular fit."],
  ],
  testimonials: [
    { quote: "Got so many DMs asking where my tee is from 😭", name: "Aarav", place: "Pune" },
    { quote: "Quality is insane for the price. Fabric is thick.", name: "Zoya", place: "Delhi" },
    { quote: "Missed drop 21, not making that mistake again.", name: "Kabir", place: "Mumbai" },
  ],
  reviews: [
    { product: 0, rating: 5, title: "Obsessed", body: "The print is fire and it's so comfy.", author: "Tara" },
    { product: 1, rating: 5, title: "Fit is 🔥", body: "Perfect oversized fit.", author: "Rehan" },
    { product: 3, rating: 4, title: "Cute set", body: "Shorts could be a bit longer.", author: "Mira" },
  ],
  products: [
    { title: "Phool Bomb Oversized Tee", type: "top", category: "tees", price: 899, mrp: 1199, sizes: "standard", colors: [{ name: "Sunshine", hex: "#ffd23f" }, { name: "Lilac", hex: "#c7b8ff" }], fabric: "240 GSM cotton", work: "Screen print", occasion: ["Streetwear"], tags: ["drop23", "under999", "bestseller"], featured: true, short: "Big florals on a boxy tee.", description: "A heavyweight oversized tee with a giant phool print across the front. Dropped shoulders, ribbed collar.", art: { silhouette: "tee", print: "bigfloral", colors: { ground: "#ffd23f", ink: "#ff5da2", accent: "#3a86ff", leaf: "#06d6a0" } }, collections: ["drop-23"] },
    { title: "Ajrakh Grid Tee", type: "top", category: "tees", price: 999, sizes: "standard", fabric: "240 GSM cotton", work: "Screen print", occasion: ["Streetwear"], tags: ["drop23", "bestseller"], short: "Ajrakh-inspired grid on black.", description: "An oversized black tee with an ajrakh-inspired grid print in red and indigo.", art: { silhouette: "tee", print: "ajrakh", colors: { ground: "#141414", ink: "#e63946", accent: "#4361ee", leaf: "#2f4a3a" } }, collections: ["drop-23"] },
    { title: "Checkmate Resort Shirt", type: "shirt", category: "shirts", price: 1499, mrp: 1799, sizes: "standard", fabric: "Rayon", work: "Printed", occasion: ["Vacation", "Party"], tags: ["drop23"], short: "Loud checks, camp collar.", description: "A camp-collar resort shirt in fluid rayon with a pink and green check.", art: { silhouette: "jacket", print: "check", colors: { ground: "#ff8fab", ink: "#2ec4b6", accent: "#ffbf69", leaf: "#2ec4b6" } }, collections: ["drop-23"] },
    { title: "Bandhani Co-ord Shorts Set", type: "co_ord_set", category: "co-ords", price: 1899, mrp: 2299, sizes: "standard", fabric: "Cotton", work: "Bandhani print", occasion: ["Vacation"], tags: ["drop23", "bestseller"], featured: true, short: "Bandhani shirt and shorts.", description: "A boxy shirt and relaxed shorts in electric blue bandhani print.", art: { silhouette: "coord", print: "bandhani", colors: { ground: "#3a86ff", ink: "#fff", accent: "#ffbe0b", leaf: "#fff" } }, collections: ["drop-23"] },
    { title: "Leheriya Slip Dress", type: "dress", category: "dresses", price: 1699, sizes: "standard", fabric: "Satin", work: "Printed", occasion: ["Party"], tags: ["drop23"], short: "Satin slip dress in leheriya waves.", description: "A bias-cut satin slip dress with a leheriya wave print in lime and violet.", art: { silhouette: "maxi", print: "leheriya", colors: { ground: "#caffbf", ink: "#7b61ff", accent: "#ff3d71", leaf: "#00bbf9" } }, collections: ["drop-23"] },
    { title: "Kalamkari Cargo Pants", type: "bottom", category: "bottoms", price: 1799, sizes: "standard", fabric: "Cotton twill", work: "Printed", occasion: ["Streetwear"], tags: ["drop23"], short: "Cargos with kalamkari pocket prints.", description: "Relaxed cargo pants in olive twill with kalamkari-printed pocket flaps.", art: { silhouette: "palazzoSet", print: "kalamkari", colors: { ground: "#e8e2d0", ink: "#3d4a33", accent: "#9c4b2f", leaf: "#6a5a3a", altGround: "#5a6a3a", altPrint: "solid" } } },
    { title: "Mirror Work Crop Tee", type: "top", category: "tees", price: 799, sizes: "standard", fabric: "Cotton", work: "Mirror work", occasion: ["Party"], tags: ["under999"], short: "Cropped tee with mirror patches.", description: "A cropped tee in white with hand-stitched mirror patches on the chest.", art: { silhouette: "tee", print: "polka", colors: { ground: "#fafafa", ink: "#c0c0c0", accent: "#c0c0c0", leaf: "#c0c0c0" } }, collections: ["under-999"] },
    { title: "Ikat Bomber Jacket", type: "other", category: "shirts", price: 2799, mrp: 3299, sizes: "standard", fabric: "Cotton", work: "Ikat weave", occasion: ["Streetwear"], tags: ["drop23"], short: "Ikat bomber, ribbed cuffs.", description: "A bomber jacket in handwoven ikat with ribbed cuffs and hem.", art: { silhouette: "jacket", print: "ikat", colors: { ground: "#1d1d1d", ink: "#ff3d71", accent: "#ffd23f", leaf: "#7b61ff" } }, collections: ["drop-23"] },
  ],
  shippingNote: "Free shipping over ₹999. Drops ship within 48 hours.",
  returnsNote: "Size exchanges within 7 days. Drop items can't be returned for refund.",
};

// ----------------------------------------------------------------------------- 10 · Premium luxury
const anaya: StoreSpec = {
  slug: "anaya",
  name: "Maison Anaya",
  tagline: "Indian craft, quietly luxurious",
  story: "Maison Anaya is a luxury house working with master weavers in Varanasi and Chanderi and embroiderers in Lucknow. Our collections are small, seasonless and made to last a lifetime.",
  email: "concierge@maisonanaya.test",
  phone: "+912240012345",
  address: { line1: "Kala Ghoda, Fort", city: "Mumbai", state: "Maharashtra", postal_code: "400001" },
  social: { instagram: "https://instagram.com/maisonanaya", pinterest: "https://pinterest.com/maisonanaya" },
  seo: { title: "Maison Anaya — Luxury handwoven sarees and couture", description: "Luxury handwoven Banarasi and Chanderi sarees, lehengas and jackets from India's master artisans." },
  legalName: "Maison Anaya Private Limited",
  gstin: "27AAHCM1122N1Z0",
  backdrop: ["#1e1c1a", "#0d0c0b"],
  bannerBackdrop: ["#8c6d46", "#0d0c0b"],
  hero: { eyebrow: "Collection I", heading: "The Art of the Loom", subheading: "Handwoven Banarasi and Chanderi, made by master artisans.", ctaLabel: "Discover", ctaHref: "/collections/collection-one", textTone: "light", align: "center" },
  announcement: ["Private appointments available in Mumbai and Delhi"],
  tokens: {
    colors: { primary: "#1a1a1a", secondary: "#8c6d46", accent: "#8c6d46", background: "#f8f5f0", text: "#1a1a1a", border: "#e7e0d4", sale: "#6e4a2a" },
    headingFont: "didone",
    bodyFont: "geometric-sans",
    headingCase: "uppercase",
    buttonShape: "square",
    buttonVariant: "outline",
    cardRadius: "none",
    containerWidth: "wide",
    spacing: "airy",
  },
  header: { sticky: false, showStoreName: true },
  headerLayout: "logo-center",
  productCard: { imageRatio: "tall", textAlign: "center", badgeStyle: "minimal", showQuickAdd: false, showRating: false, showDiscountPercent: false, showBadges: false, secondImageOnHover: true },
  footerTone: "light",
  home: [
    ["Hero", { height: "full", overlay: 40 }],
    ["CollectionGrid", { heading: "The collections", mode: "auto", limit: 2, columns: 2 }],
    ["BrandStory", { eyebrow: "The Maison", heading: "Time, made visible", body: "A single Kadhwa Banarasi can take a master weaver and his apprentice six weeks. We work with seven such looms in Varanasi and credit every weaver by name on the garment's certificate.", imagePath: "$img:story", alt: "Weaver at a handloom", stats: [{ value: "7", label: "Master looms" }, { value: "6 wks", label: "Per Kadhwa saree" }] }],
    ["ProductGrid", { heading: "Collection I", source: "collection", collectionId: "$collection:collection-one", limit: 6, columns: 3, viewAllHref: "/collections/collection-one" }],
    ["EditorialImageText", { heading: "Kadhwa, the slowest weave", body: "In Kadhwa weaving each motif is woven separately with its own shuttle, so the back of the fabric is as clean as the front. It is the rarest and most demanding Banarasi technique.", imagePath: "$img:editorial", alt: "Gold zari motif detail", imagePosition: "left", tone: "dark" }],
    ["Newsletter", { heading: "The Maison journal", subheading: "Stories of craft, collections and private previews.", buttonLabel: "Subscribe", tone: "light" }],
  ],
  categories: [
    { slug: "sarees", name: "Sarees", description: "Handwoven sarees." },
    { slug: "lehengas", name: "Lehengas", description: "Couture lehengas." },
    { slug: "jackets", name: "Jackets", description: "Brocade jackets." },
    { slug: "ensembles", name: "Ensembles", description: "Kurta sets and ensembles." },
  ],
  collections: [
    { slug: "collection-one", title: "Collection I", description: "Banarasi and Chanderi, woven by master artisans." },
    { slug: "evening", title: "Evening", description: "For evenings of consequence.", rules: { tag: "evening" } },
  ],
  menu: [
    { title: "Collection I", to: "/collections/collection-one" },
    { title: "Sarees", to: "/categories/sarees" },
    { title: "Lehengas", to: "/categories/lehengas" },
    { title: "Jackets", to: "/categories/jackets" },
    { title: "Ensembles", to: "/categories/ensembles" },
    { title: "The Maison", to: "/pages/about" },
  ],
  faqs: [
    ["Do you offer private appointments?", "Yes, at our Mumbai and Delhi salons, or by video. Write to our concierge to book."],
    ["How do I care for a Banarasi saree?", "Store folded in muslin, refold every few months along different lines, and dry clean only with a specialist."],
    ["Is each piece certified?", "Every handwoven piece carries a certificate naming the weaver and the loom."],
  ],
  testimonials: [
    { quote: "The Kadhwa saree is the most beautiful thing I own.", name: "Leela R.", place: "Mumbai" },
    { quote: "Impeccable service, from appointment to delivery.", name: "Anjana K.", place: "Delhi" },
  ],
  reviews: [{ product: 0, rating: 5, title: "Extraordinary", body: "The weave is flawless. An heirloom.", author: "Leela" }],
  products: [
    { title: "Kadhwa Banarasi Saree — Noir", type: "saree", category: "sarees", price: 245000, sizes: "free", fabric: "Katan silk", work: "Kadhwa zari weave", occasion: ["Wedding", "Evening"], tags: ["evening"], featured: true, short: "Noir katan silk with kadhwa gold.", description: "A noir katan silk saree hand-woven in the kadhwa technique with real gold zari butis and a woven border. Six weeks on the loom.", art: { silhouette: "saree", print: "zari", colors: { ground: "#141414", ink: "#c6a664", accent: "#d4b574", leaf: "#b8955a", altGround: "#141414", altPrint: "zari", drapePrint: "zari", drapeGround: "#1c1c1c" } }, collections: ["collection-one"] },
    { title: "Chanderi Tissue Saree — Ivory", type: "saree", category: "sarees", price: 86000, sizes: "free", fabric: "Chanderi tissue", work: "Hand woven", occasion: ["Day", "Wedding"], tags: [], short: "Ivory chanderi tissue with a gold selvedge.", description: "Featherlight chanderi tissue in ivory with a fine gold selvedge.", art: { silhouette: "saree", print: "solid", colors: { ground: "#efe7d6", ink: "#d8cbb2", accent: "#d8cbb2", leaf: "#d8cbb2", altGround: "#c9ad73", altPrint: "solid", drapePrint: "zari", drapeGround: "#efe7d6" } }, collections: ["collection-one"] },
    { title: "Brocade Bandhgala Jacket — Bronze", type: "other", category: "jackets", price: 64000, sizes: "standard", fabric: "Banarasi brocade", work: "Hand woven", occasion: ["Evening"], tags: ["evening"], featured: true, short: "Bronze brocade bandhgala.", description: "A tailored bandhgala jacket in bronze Banarasi brocade with horn buttons.", art: { silhouette: "jacket", print: "zari", colors: { ground: "#6e5231", ink: "#c6a664", accent: "#d4b574", leaf: "#c6a664" } }, collections: ["collection-one"] },
    { title: "Ghatchola Lehenga — Oxblood", type: "lehenga", category: "lehengas", price: 320000, sizes: "standard", fabric: "Silk", work: "Zardozi", occasion: ["Wedding"], tags: ["evening"], short: "Oxblood silk, zardozi grid.", description: "An oxblood silk lehenga with a hand-embroidered zardozi grid inspired by Gujarati gharchola.", art: { silhouette: "lehenga", print: "check", colors: { ground: "#4a1418", ink: "#c6a664", accent: "#c6a664", leaf: "#c6a664", altGround: "#4a1418", altPrint: "zari", drapePrint: "zari", drapeGround: "#5e1c21" } }, collections: ["collection-one"] },
    { title: "Chikankari Ensemble — Mist", type: "kurta_set", category: "ensembles", price: 58000, sizes: "apparel", fabric: "Cotton mul", work: "Chikankari", occasion: ["Day"], tags: [], short: "Hand chikankari on mist grey mul.", description: "A long kurta and palazzo in mist grey mul, entirely hand-worked in shadow chikankari.", art: { silhouette: "palazzoSet", print: "vine", colors: { ground: "#c9c7c2", ink: "#e9e7e2", accent: "#e9e7e2", leaf: "#e9e7e2", altGround: "#b3b1ac", altPrint: "solid" } }, collections: ["collection-one"] },
    { title: "Jamdani Saree — Dove", type: "saree", category: "sarees", price: 72000, sizes: "free", fabric: "Cotton jamdani", work: "Hand woven", occasion: ["Day"], tags: [], short: "Dove grey jamdani.", description: "A dove grey jamdani with white woven motifs across the field.", art: { silhouette: "saree", print: "zari", colors: { ground: "#a9a6a1", ink: "#f4f2ee", accent: "#f4f2ee", leaf: "#f4f2ee", altGround: "#8f8c87", altPrint: "solid", drapePrint: "zari", drapeGround: "#a9a6a1" } }, collections: ["collection-one"] },
  ],
  shippingNote: "Complimentary insured delivery with signature. Private delivery available in Mumbai and Delhi.",
  returnsNote: "Returns within 7 days for unworn pieces with the certificate. Couture orders are final sale.",
};

export const STORES_B: StoreSpec[] = [noor, vivaah, neel, drip, anaya];
